### PR TITLE
Service Mapping Update for Communication

### PR DESCRIPTION
**Pull request by scbedd**

### CODE REVIEW

**Comment by weshaggard** [comment]
I thought I did this with https://github.com/Azure/azure-sdk-for-python/commit/379d0129c20eb942934c6e8d2bd00b39c6806665.

**Comment by scbedd** [comment]
> I thought I did this with [379d012](https://github.com/Azure/azure-sdk-for-python/commit/379d0129c20eb942934c6e8d2bd00b39c6806665).

Yeah you're right. I locally had some git shenanigans from messing up a couple commands. Meant to only add `azure-communication-administration` :/

**Comment by scbedd** [comment]
@weshaggard  that looks better now.

**Review by weshaggard — APPROVED** [review]

**Comment by weshaggard** [comment]
Thanks for fixing my typo.

**Pull request merged**
