### PR TITLE
[ml] Switched compute operations to go through 2022-10-01-preview API version

### PR DESCRIPTION
**Pull request by luigiw**
# Description

Please add an informative description that covers that changes made by the pull request and link all relevant issues.

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by needuv** [comment]
https://github.com/Azure/azure-sdk-for-python/blob/f89414fc2b050f04b9426d57536ebd297c834854/sdk/ml/azure-ai-ml/azure/ai/ml/operations/_compute_operations.py need to change this import/the respective type hint

**Comment by needuv** [comment]
Change these test files too: 

https://github.com/Azure/azure-sdk-for-python/blob/e40e73df1c0349adb128b962ca25719724d5f99d/sdk/ml/azure-ai-ml/tests/compute/unittests/test_compute_operations.py
https://github.com/Azure/azure-sdk-for-python/blob/e40e73df1c0349adb128b962ca25719724d5f99d/sdk/ml/azure-ai-ml/tests/compute/unittests/test_compute_entity.py

**Review by nthandeMS — CHANGES_REQUESTED** [review]
Can you update the schema files as well? Some compute schemas draw from the API classes, so giving it a once-over would be good.

**Comment by needuv** [comment]
Sorry to pile more onto this PR, but this PR: https://github.com/Azure/azure-sdk-for-python/pull/27004/files#diff-3943aaba3b12a19c69427a9135e998e1d3f91baf7be45ffc0060f8f5ae3e23fc Disabled tests in `tests/compute/unittests/test_compute_operations.py` on Py3.11. Could you take a look and try to remove the skip condition for python 3.11? We definitely don't want to miss this validation

**Comment by luigiw** [comment]
> Sorry to pile more onto this PR, but this PR: https://github.com/Azure/azure-sdk-for-python/pull/27004/files#diff-3943aaba3b12a19c69427a9135e998e1d3f91baf7be45ffc0060f8f5ae3e23fc disabled tests in `tests/compute/unittests/test_compute_operations.py` on Py3.11. Could you take a look and try to remove the skip condition for python 3.11? We definitely don't want to miss this validation

It's interesting that some tests don't run with Python 3.11. Do we have a work item for this? I'll be happy to do that in another PR.

**Comment by luigiw** [comment]
> Can you update the schema files as well? Some compute schemas draw from the API classes, so giving it a once-over would be good.

Good catch. Done.

**Review by nthandeMS — APPROVED** [review]

**Pull request merged**
