### PR TITLE
Added Azure files support to the SDK

### PR DESCRIPTION
**Pull request by schaefi**
Starting with Azure file share support. This pull requests add

* list shares
* add shares
* delete shares

### CODE REVIEW

**Comment by emgerner-msft** [comment]
As mentioned in our [other thread](https://github.com/Azure/azure-sdk-for-python/issues/394), we would like to build on your work whilst we complete support for the entire file service. In the last week we were actually able to put together a [full file service implementation]( https://github.com/Azure/azure-sdk-for-python/pull/425) based very heavily on the blob service code, as it looks like your implementation is. There are some difference between our implementations. The full file service pull request should be ready to go now, so we have two options: 

1.	We can close this pull request down, you can (optionally) CR the full file service pull request to make sure it meets your needs, and then we can merge the full service pull request and call it a day. Or,
2.	We can do a full CR process on this pull request, merge it, rebase the other on top of it, and then do a final merge.

I’m open to doing either, though of course 1 is easier. :) Thoughts?

Best,
Emily

**Comment by schaefi** [comment]
Ah I see you submitted #425. Well your one contains everything around file shares. That makes the stuff I did obsolete of course. Therefore let's go with option 1) everything else wouldn't make much sense to me, your implementation looks pretty good to me. It's a pity the stuff I did seemed to be a pointless exercise except for getting familiar with the SDK code and structure, anyway maybe my timing to start with this was bad

Feel free to close this one once #425 is merged, I will adapt my code accordingly afterwards

Thanks

**Comment by emgerner-msft** [comment]
Great, I'll have my stuff merged later today and let you close this pull request down at your leisure.

It's too bad things didn't work out this time with timing and communication issues. Hopefully next time with all these details ironed out we can work together more smoothly. Looking forward to working with you in the future!

**Comment by schaefi** [comment]
All right your code works nicely, you chose the class name FileService while I used FilesService :)

Thanks for your support

Closing this one

**Pull request closed without merging**
