### PR TITLE
[Pylint] Bump version disabling checkers

### PR DESCRIPTION
**Pull request by l0lawrence**
disabling the difference between pylint --list-msgs-enabled for version 2.14.5 versus 2.9.3, until can take a closer look at what we want to keep

Diff: Total  Approx 40 differences
typevar-name-incorrect-variance  
typevar-double-variance
typevar-name-mismatch 
use-sequence-for-iteration
consider-using-f-string - yes there are quite a few
use-implicit-booleaness-not-len -
use-implicit-booleaness-not-comparison
non-ascii-module-import 
bad-file-encoding 
unnecessary-dunder-call 
unnecessary-lambda-assignment
unnecessary-direct-lambda-call 
bad-configuration-section
unrecognized-option
invalid-enum-extension 
potential-index-error
invalid-unicode-codec 
bidirectional-unicode 
invalid-character-backspace
invalid-character-carriage-return
invalid-character-sub 
invalid-character-esc 
invalid-character-nul
invalid-character-zero-width-space 
modified-iterating-dict
modified-iterating-set 
config-parse-error 
useless-option-value 
comparison-of-constants 
use-list-literal
use-dict-literal
unnecessary-list-index-lookup
unknown-option-value 
duplicate-value
overridden-final-method
subclassed-final-class 
redefined-slots-in-subclass
super-without-brackets
format-string-without-interpolation
redundant-u-string-prefix
unspecified-encoding 
forgotten-debug-statement
method-cache-max-size-none
useless-with-lock
unnecessary-ellipsis 
non-ascii-file-name
using-f-string-in-unsupported-versio 
using-final-decorator-in-unsupported-version
modified-iterating-list

### CODE REVIEW

**Review by tjprescott — CHANGES_REQUESTED** [review]
Yikes that's a massive list! Is there any way to break it up so it's obvious what was "permanent" and what is "temporary"?

**Comment by l0lawrence** [comment]
> Yikes that's a massive list! Is there any way to break it up so it's obvious what was "permanent" and what is "temporary"?

I can order them so that permanently/currently disabled checkers go first and then put a space before the temporarily/new version added disabled checkers are listed

**Comment by tjprescott** [comment]
@l0lawrence how many violations are there of the new checks?

**Comment by l0lawrence** [comment]
> @l0lawrence how many violations are there of the new checks?

It is running - I will update the violations above next to the check name ^

**Review by tjprescott — APPROVED** [review]
Let's work on trimming this list once we verify this fixes the Const is not iterable issue.

**Comment by tjprescott** [comment]
@l0lawrence is this PR still relevant or should it be closed?

**Comment by l0lawrence** [comment]
It is still relevant! I will be addressing pylint bumps during MQ

**Comment by tjprescott** [comment]
@l0lawrence then should we resolve the conflicts and merge this or close it until MQ?

**Comment by l0lawrence** [comment]
Close until MQ

**Pull request closed without merging**
