### PR TITLE
put less popular parameters into kwargs

### PR DESCRIPTION
**Pull request by xiangyan99**

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by johanste** [comment]
Using azure.**data**.appconfiguration would require us to create a namespace package for azure.data.

**Comment by johanste** [comment]
AzureAppConfigurationClient's constructor should not take a connection string. The connection string parsing logic should be in the `from_connection_string` class method.

**Comment by johanste** [comment]
I'm not seeing a retry policy in the pipeline?

**Comment by johanste** [comment]
The network logging policy should be after the request credentials/signing policy.

**Comment by johanste** [comment]
get_configuration_setting's mapping of 412 errors to ResourceNotFoundError does not look correct. Under what circumstances would this happen?

**Comment by johanste** [comment]
How can I clear a value using update_configuration_setting?

**Comment by johanste** [comment]
There is duplicated code between the sync and async client that I'm not sure why it is there (e.g. escape_reserved)

**Comment by xiangyan99** [comment]
> How can I clear a value using update_configuration_setting?

In our design, set value to None or not setting a value means "not change", set to empty string can clear a value

**Comment by xiangyan99** [comment]
> There is duplicated code between the sync and async client that I'm not sure why it is there (e.g. escape_reserved)

Good catch. I moved the shared code into utils.

**Comment by xiangyan99** [comment]
> get_configuration_setting's mapping of 412 errors to ResourceNotFoundError does not look correct. Under what circumstances would this happen?

Good catch. Get_Config_Setting will not get 412

**Comment by xiangyan99** [comment]
> I'm not seeing a retry policy in the pipeline?

Added

**Comment by xiangyan99** [comment]
> The network logging policy should be after the request credentials/signing policy.

Updated

**Comment by johanste** [comment]
> > How can I clear a value using update_configuration_setting?
> 
> In our design, set value to None or not setting a value means "not change", set to empty string can clear a value

I would strongly prefer omitting the parameter for "not change" and setting to `None` to clear. Which implies that they are `kwargs`. The alternative is to have them as parameters with an explicit `clear` sentinel value.

**Pull request merged**
