### PR TITLE
Use HttpLoggingPolicy

### PR DESCRIPTION
**Pull request by chlowell**
Adds `HttpLoggingPolicy` to pipelines throughout azure-identity and azure-keyvault-*. I also noticed the tracing policy takes kwargs now, so I pass them now.

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by lmazuel** [comment]
@johanste @chlowell https://github.com/Azure/azure-sdk-for-python/pull/8059

**Comment by lmazuel** [comment]
Might need this to get CI happy: https://github.com/Azure/azure-sdk-for-python/pull/8083

**Comment by lmazuel** [comment]
@chlowell please use this opportunity to update minimal dependency of identy and keyvault-xxx to core 1.0.0b5

**Pull request merged**
