### PR TITLE
[Service Bus] readdress fix for preparer "resource does not exist" error (potentially)

### PR DESCRIPTION
**Pull request by swathipil**
fixes: #13747

### CODE REVIEW

**Review by yunhaoling — COMMENTED** [review]
do we also need this part for: 
- topics.create_or_update
- queues.create_or_update
- namespaces.create_or_update

**Comment by swathipil** [comment]
> do we also need this part for:
> 
> * topics.create_or_update
> * queues.create_or_update
> * namespaces.create_or_update

I decided not to add it for now, because the original issue only mentioned `SBNamespace` and `SBQueueAuth` as having these errors. If these errors show up for the topics/queues as well, I thought I could add the same fix later. Thoughts @yunhaoling ?

**Comment by yunhaoling** [comment]
me personally prefixing fixing them in one shot as this seems be a general error which will occur when creating resources -- but you're correct as well.

I'll leave the judgement to you :P

**Review by yunhaoling — APPROVED** [review]

**Comment by swathipil** [comment]
> me personally prefer fixing them in one shot as this seems be a general error which will occur when creating resources -- but you're correct as well.
> 
> I'll leave the judgement to you :P

makes sense, will do that!

**Pull request merged**
