### PR TITLE
Unified Pipelines clean-up.

### PR DESCRIPTION
**Pull request by mitchdenny**
This PR removes the client.yml pipeline that was in use before unified pipelines was rolled out. As part of this clean-up we will also be doing the following:

- [x] Disable the internal ```python - client``` pipeline.
- [x] Removing the internal ```python - client``` pipeline.
- [x] Disable the public ```python - client - ci``` pipeline.
- [x] Removing the public ```python - client - ci``` pipeline.
- [x] Remove the old python release pipeline.
- [x] What else do we need to do here?

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by mitchdenny** [comment]
@scbedd are you good with removing the python - client - ci pipeline or are you still depending on it?

**Comment by scbedd** [comment]
Before we do this, I gotta write up instructions for the management team. They still need the ability to do this.

Also, our nightly build (which the management team also uses to release) is using the `client.yml`. I can swap that to just leverage the `archtype-sdk-nightly.yml` specifically.

However, I don't want to remove the nightly build entirely. I want to use it to test some of our other scenarios.

**Comment by mitchdenny** [comment]
> I want to use it to test some of our other scenarios. I do not agree with the complete removal of this pipeline by any stretch.

The ```python - client``` build has been failing since Friday. If a build fails in the forest and no-one hears it ...

I think we should try to figure out a way of detecting the issues we want to detect more efficiently and ideally within the bounds of the scoped unified pipelines. I don't know how we do that though. 

One issue you highlighted when we discussed was namespace corruption. It's a specific instance of socialization testing where we see whether modules if loaded into the same process step on each other. That was one of the stated goals of smoke tests, which seemed lighter weight than the test runs.

Currently ```python - client``` consumes 18 hours of agent time each time it runs.

**Comment by scbedd** [comment]
It's been failing since Friday except for last night where it was disabled. Praveen checked in the fix to resolve the failure yesterday :) We definitely knew it was blowing up.

You have a good point about the smoke-testing. Maybe we move the socialization build and test to a separate in the `smoke-test` build? If we do that. Yeah, I'm cool with killing this thing.

**Comment by mitchdenny** [comment]
> You have a good point about the smoke-testing. Maybe we move the socialization build and test to a separate in the `smoke-test` build? If we do that. Yeah, I'm cool with killing this thing.

The smoke test would be strictly a subset of the current test scenarios?

**Comment by mitchdenny** [comment]
I believe that this PR is ready to go @scbedd  --- I've moved the ```python - client``` definition into ```\python\legacy``` rather than delete it (just for services issues that might come up) - but the pipeline itself is disabled so won't run unless someone explicitly re-enables it.

**Pull request merged**
