### PR TITLE
Lint code for Python syntax errors and undefined names

### PR DESCRIPTION
**Pull request by cclauss**
Many of these _undefined names_ can be solved with [__import typing__](https://pypi.org/project/typing) or by importing other modules while others can be solved by using __six.string_types__ and __six.text_type__ or by following Python porting best practice [use feature detection instead of version detection](https://docs.python.org/3/howto/pyporting.html#use-feature-detection-instead-of-version-detection).

The F63 issues are about the confusion between identity and equality in Python.  __Use ==/!= to compare str, bytes, and int literals__ are instances where __a == b__ is True but __a is b__ is False (or vice versa).

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by cclauss** [comment]
The F63 instances will raise SyntaxWarnings on Python >= 3.8 so it is best to fix them now. https://docs.python.org/3.8/whatsnew/3.8.html#porting-to-python-3-8

**Comment by Petermarcu** [comment]
@mayurid @lmazuel can you take a look?

**Comment by lmazuel** [comment]
Hi @cclauss 
Sorry for the very late discussion on this one, missed your PR :(
We are using a combination of pylint/black nowadays in our main CI, and we don't plan to integrate flake8 in our pipelines.
Also, you introduced it in the "updated_pr" pipeline, which is not designed for that (that's a bot to update packaging information automatically).

For all those reasons, I'm closing this PR for now, but I'll be happy to discuss our engsys in an issue if you believe there is important improvement we should still do.

Thanks for your contribution!

**Pull request closed without merging**
