### PR TITLE
[translator] rename package/namespace

### PR DESCRIPTION
**Pull request by kristapratico**
Resolves https://github.com/Azure/azure-sdk-for-python/issues/17043

This does the rename from azure-ai-documenttranslation to azure-ai-translator

(rename pending on more discussion from architects)

### CODE REVIEW

**Review by maririos — APPROVED** [review]

**Comment by maririos** [comment]
can you trigger the live tests too just in case?

**Comment by kristapratico** [comment]
> can you trigger the live tests too just in case?

Yes, was planning to :)

**Comment by kristapratico** [comment]
Decided not to go with this naming after architect discussion. New namespace/package naming in https://github.com/Azure/azure-sdk-for-python/pull/17792

**Pull request closed without merging**
