### PR TITLE
update samples & rename datasource methods

### PR DESCRIPTION
**Pull request by xiangyan99**

### CODE REVIEW

**Comment by xiangyan99** [comment]
#11693

**Comment by xiangyan99** [comment]
> I don't see a rename for `get_data_source_connection_names`. Is that not implemented yet?

Do you mean "get_data_source_connections"?

**Comment by heaths** [comment]
It's a method to be added from https://github.com/Azure/azure-sdk-for-python/issues/11320.

**Comment by xiangyan99** [comment]
No. It is not in the PR. I will add it in a separate PR.

**Pull request merged**
