### PR TITLE
strict sphinx easm

### PR DESCRIPTION
**Pull request by kristapratico**
Resolves https://github.com/Azure/azure-sdk-for-python/issues/33583

### CODE REVIEW

**Comment by kristapratico** [comment]
Failing pyright and pylint. Tried regenerating to fix, but too many changes + new features being added(?) for me to feel comfortable committing. 

Tracked in https://github.com/Azure/azure-sdk-for-python/issues/33231 https://github.com/Azure/azure-sdk-for-python/issues/33230

**Review by annatisch — APPROVED** [review]

**Pull request merged**
