### PR TITLE
git: add pre-commit configuration to .gitignore

### PR DESCRIPTION
**Pull request by elliotzh**
# Description

Add pre-commit configuration file to .gitignore.

We don't want to enable git hooks in root level as package specific hooks may bring delay and in some cases error to all developers.

By adding the configuration file to .gitignore, package developers may enable pre-commit locally if needed without impact the repo.

# All SDK Contribution checklist:
- [ ] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by jsquire** [comment]
//cc: @lmazuel, @weshaggard:   Please offer your thoughts, as this would impact pipelines for all of Python.

**Comment by jsquire** [comment]
@elliotzh :  Please do not merge this without explicit sign-off from Laurent or Wes.

**Review by weshaggard — CHANGES_REQUESTED** [review]
For our mono repositories we avoid having any commit hooks because they often cause reliability issues, and they cannot be depended on because it requires that everyone that clones the repo do a setup step to enable them. Instead, we suggest adding checks in the CI pipeline for whatever you are trying to enforce.

**Comment by luigiw** [comment]
@weshaggard Thx for looking into this. We already have the pylint check in ML's CI pipeline. The problem is that the pylint error in CI pipeline show up too late, our engineers often find themselves waiting for CI pipeline for ~20 minutes just to find out a simple pylint error. This impacts our engineering productivity.  Is there a way to add pre commit at sub folder level?

**Comment by weshaggard** [comment]
>CI pipeline show up too late, our engineers often find themselves waiting for CI pipeline for ~20 minutes just to find out a simple pylint error. This impacts our engineering productivity. Is there a way to add pre commit at sub folder level?

There is not a way to configure a git commit to a given directory only as it is a global repo hook and will intercept all git commit calls if configured locally. There is also no way to enforce that the git commit hook is enabled on a local clone. 

CI should only be the enforcer so folks shouldn't ever hit it if they are correctly running the pylint commands locally before they submit a PR. It should simply be part of the workflow folks use to do development locally and CI is only there to enforce they did that work.

**Comment by kristapratico** [comment]
@luigiw take a look at using `tox` for running pylint locally: https://github.com/Azure/azure-sdk-for-python/blob/main/doc/dev/tests.md#tox

The `lint` environment command is identical to what's run in CI.

**Comment by elliotzh** [comment]
@weshaggard @kristapratico Thank you for your explanation! Then what if we add the configuration file to .gitignore? Then we may enable pre-commit locally without impacting other developers. And we may maintain related files & docs inside azure-ai-ml.

cc @luigiw @wangchao1230 

PS: using `tox` to run pylint locally is great, I just usually forget to do it before committing and it will take longer than just running pylint on changed files. Actually, current pre-commit required the developer to run pylint with `tox` first to set up the environment.

**Comment by needuv** [comment]
@elliotzh @luigiw @jsquire @weshaggard @kristapratico 

During the ML SDK migration, we identified not having pre-commit hooks as one of our process gaps-- we had it in our internal repo to do automated code quality checks. @scbedd suggested I create an issue for this so that the Azure SDK team could look into this, which I did back in September: https://github.com/Azure/azure-sdk-for-python/issues/26509. Something that we discussed was enabling it **just** for the ML SDK, and other teams could opt in if they wanted to (but they are not forced to). In addition to the pylint check, we would like to have things like black, new line end of file checker, flake8, isort, etc run on our commits, and I've included the pre-commit file we had in our internal repo in the issue. Let me know your thoughts?

**Comment by weshaggard** [comment]
I will say from our past experiences that doing this as part of a git hook is likely going to cause more issues than you might want (i.e. it causes performance and reliability issues during git operations that can leave the repo in odd states). There is also still the problem that folks have to remember to do something post-cloning of the repo in order to get these hooks setup otherwise they will also not be ran. 

If you are worried about folks forgetting to run locally before submitting a PR I'd recommend hooking it up to a command folks already run all the time like running tests or perhaps a wrapper script that does tests and these other things you want to be sure folks don't forget. Also depending on things like .editorconfig files will help folks do a number of these linting and formatting things directly while editing which is a more natural way to get these integrated.

**Comment by weshaggard** [comment]
After talking I'm OK with adding this to the gitignore so folks can opt into this if wish. As we talked we should ensure any commands ran as part of the git hook should be consistent with what we run in CI.

**Review by wangchao1230 — APPROVED** [review]

**Pull request merged**
