### PR TITLE
T1 Netapp 2021-02-25

### PR DESCRIPTION
**Pull request by 00Kai0**
https://github.com/Azure/sdk-release-request/issues/1269
--

### CODE REVIEW

**Comment by hildurhodd** [comment]
@00Kai0 if you give me access to push to your branch then I have updated tests and recordings. I see that you marked all tests to be skipped.

**Comment by 00Kai0** [comment]
@hildurhodd , I have invited you to my repo, thanks for your help.

**Comment by 00Kai0** [comment]
You can fix all test on my branch ;)

**Comment by hildurhodd** [comment]
@00Kai0 I have pushed updated tests and recordings and all checks have passed :)

**Review by msyyc — APPROVED** [review]

**Pull request merged**
