### PR TITLE
Update python SDK for Purview Catalog

### PR DESCRIPTION
**Pull request by yifan-zhou922**
# Description

Please add an informative description that covers that changes made by the pull request and link all relevant issues.

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [ ] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by msyyc** [comment]
Hi @yifan-zhou922 `_purview_catalog_client.py` is renamed to `_client.py` by DPG so the [commit](https://github.com/Azure/azure-sdk-for-python/pull/24674/commits/e472210818e057ebd42993fa3fec4dae2e76f6ad) is unnecessary which cause failure of CI

**Comment by yifan-zhou922** [comment]
We will add e2e tests for import business metadata and glossary term later.

**Comment by msyyc** [comment]
Hi @yifan-zhou922 The CI shows that the endpoint in recording files are not same: 
image
`metamodeldemo02.purview.azure.com` seems your real service which shall be replaced by [fake endpoint](https://github.com/Azure/azure-sdk-for-python/blob/bf5307142113438a099bfde3b37f72c3a84611e0/sdk/purview/azure-purview-catalog/tests/testcase.py#L26). Please make sure you run live test with guidance.

**Comment by msyyc** [comment]
Hi @johanste  @lmazuel The PR pass all the CI, please help review it. Thanks!

**Review by msyyc — APPROVED** [review]

**Pull request merged**
