### PR TITLE
[service management] add certificate as string support

### PR DESCRIPTION
**Pull request by drewrothstein**
This adds support to be able to provide a string to `sms` for the required client certificate in addition to a filesystem path and windows certificate store.

The reasoning for adding this support is to support key management services in the public cloud where you will be making an API call to store/get your certificate.  There is no reason to also write it to disk.

Tests have been run under the different connection types.  I have updated `legacy_mgmt_settings_fake.py` with this to show that I clearly added this and tested it locally.

Having not contributed to this repository before, please let me know your thoughts on this change and if you think it is reasonable or not.  I have signed the CLA and it should match my user appropriately if you choose to proceed with the merge.

Thank you,
-d

### CODE REVIEW

**Comment by lmazuel** [comment]
Hi @drewrothstein 
This is interesting! However, give me a few days to investigate in more details, just got back from vacation and there's fire everywhere :)

**Comment by drewrothstein** [comment]
CLA was already signed, do I need to re-sign?

**Comment by lmazuel** [comment]
The CLA bot is then supposed to change the label automatically :/ Do you have any email confirmation or something, so I could yell at the bot team? :)

**Comment by drewrothstein** [comment]
I do have an email confirmation from Docusign.  Please let me know how you would like me to share that.

**Comment by drewrothstein** [comment]
Closing my PRs that haven't received any love in a long while.

**Comment by drewrothstein** [comment]
No worries; I understand.

**Pull request closed without merging**
