### PR TITLE
Log Analytics package 0.1.0

### PR DESCRIPTION
**Pull request by lmazuel**

### CODE REVIEW

**Comment by lmazuel** [comment]
Waiting for https://github.com/Azure/azure-rest-api-specs/pull/662

**Comment by jmalobicky** [comment]
@lmazuel is Log Analytics still able to be merged in? It looks like the comment regarding Azure/azure-rest-api-specs#662 is merged. I am interested to utilize the package and would willing to help test it out.

**Comment by lmazuel** [comment]
Hi @jmalobicky 
It can't be merge right now, I have to regenerate the code with more recent content. But I up my task since you have the opportunity to test it. Thanks!

**Comment by jmalobicky** [comment]
Hello @lmazuel  that would be awesome.

**Comment by lmazuel** [comment]
@jmalobicky I updated the PR. You can pip install from the branch using this command:
`pip install "git+https://github.com/lmazuel/azure-sdk-for-python#subdirectory=azure-mgmt-loganalytics&egg=azure-mgmt-loganalytics"`

Please let me know what you think, I will continue to test it on my side to eventually release on PyPI. Thanks for your help!

**Comment by jmalobicky** [comment]
Outstanding! That was a fast turn around. I will pull it down shortly to see what I can do with it.

**Comment by jmalobicky** [comment]
@lmazuel I am getting the following error when trying to install the package into my venv:
```
# pip install "git+https://github.com/lmazuel/azure-sdk-for-python#subdirectory=azure-mgmt-loganalytics&egg=azure-mgmt-loganalytics"
Collecting azure-mgmt-loganalytics from git+https://github.com/lmazuel/azure-sdk-for-python#subdirectory=azure-mgmt-loganalytics&egg=azure-mgmt-loganalytics
  Cloning https://github.com/lmazuel/azure-sdk-for-python to /tmp/pip-build-r2ol39fh/azure-mgmt-loganalytics
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/mpower/env/lib/python3.5/tokenize.py", line 454, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-r2ol39fh/azure-mgmt-loganalytics/azure-mgmt-loganalytics/setup.py'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-r2ol39fh/azure-mgmt-loganalytics/azure-mgmt-loganalytics
```

**Comment by lmazuel** [comment]
My bad, I forgot the branch:
```shell
pip install "git+https://github.com/lmazuel/azure-sdk-for-python@log_analytics#subdirectory=azure-mgmt-loganalytics&egg=azure-mgmt-loganalytics"
```

**Comment by jmalobicky** [comment]
Yep that worked. Thanks

**Comment by jmalobicky** [comment]
@lmazuel Looking good so far. Client is connected and workspace is created. Will work on some of the solution packs next.

**Comment by jmalobicky** [comment]
@lmazuel I ran into a road block with add the Azure Activity Log as a data source after the solution pack is enable for the workspace. I am not sure if it is the RestAPI (which it might be by the error). Can you give me your thoughts?

```
client.loganalytics_client.data_sources.list_by_workspace(
    resource_group,
    workspace_name,
    filter=DataSourceFilter('AzureActivityLog'),
)
```

I get a response error about the filter being incorrect
```
msrestazure.azure_exceptions.CloudError: Azure Error: KindNotSpecified
Message: Must specify a valid kind filter. For example, $filter=kind eq 'windowsPerformanceCounter'.
```

**Comment by lmazuel** [comment]
`filter` should be a string only, we don't have models to generate this string you. Assuming `AzureActivityLog` is a `kind`, this would look like:
```python
client.loganalytics_client.data_sources.list_by_workspace(
    resource_group,
    workspace_name,
    filter="kind eq 'AzureActivityLog'"
)
```

Just curious, where is DataSourceFilter coming from?

**Comment by jmalobicky** [comment]
Let me give that a try. The code was confusing as I was thinking it needed an object since just using the 'AzureActivityLog' did not work. Thought DataSourceFilter would have been needed.

```
from azure.mgmt.loganalytics.models import DataSourceFilter
```

**Comment by jmalobicky** [comment]
I am getting an error when trying to add the datasource for the AzureAcitivtyLog

```
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/mpower/env/lib/python3.5/site-packages/azure/mgmt/loganalytics/operations/data_sources_operations.py", line 103, in create_or_update
    raise exp
msrestazure.azure_exceptions.CloudError: 400 Client Error: Bad request, Error converting value "{"linkedResourceId": "/subscriptions/<subscription_id>/providers/microsoft.insights/eventtypes/management"}" to type 'Microsoft.Advisor.DataAccess.Configuration.Models.AzureActivityARMPayload'. Path 'properties'. for url: https://management.azure.com/subscriptions/<subscription_id>/resourcegroups/<resource_group>/providers/Microsoft.OperationalInsights/workspaces/<workspace>/dataSources/AzureActivityLog?api-version=2015-11-01-preview
```
When utilizing this example
```
properties = '{"linkedResourceId": "/subscriptions/<subscription_id>/providers/microsoft.insights/eventtypes/management"}'
client.loganalytics_client.data_sources.create_or_update(
    resource_group,
    workspace,
    'AzureActivityLog',
    DataSource(properties=properties, kind='AzureActivityLog')
)
```

**Comment by lmazuel** [comment]
`properties` must be a dict, and not a string.

**Comment by jmalobicky** [comment]
Yeah totally worked.

**Comment by lmazuel** [comment]
Hi @jmalobicky , 28 days later, are you still happy here? :)

**Comment by jmalobicky** [comment]
@lmazuel Yes, I have had no issues. This is working as expected. I would be good merging at this point.

**Comment by lmazuel** [comment]
@jmalobicky I released the package:
https://pypi.python.org/pypi/azure-mgmt-loganalytics/0.1.0

Thanks for your help! I mentioned you in the ChangeLog :)

**Pull request merged**
