### PR TITLE
[Identity] Add subscription support to Azure CLI cred

### PR DESCRIPTION
**Pull request by pvaneck**
Closes: https://github.com/Azure/azure-sdk-for-python/issues/33129

### CODE REVIEW

**Comment by xiangyan99** [comment]
Are other languages supporting it? (other than go)

**Comment by pvaneck** [comment]
> Are other languages supporting it? (other than go)

All languages will support it at some point, and JS [already added support](https://github.com/Azure/azure-sdk-for-js/pull/31451).

**Comment by xiangyan99** [comment]
> > Are other languages supporting it? (other than go)
> 
> All languages will support it at some point, and JS [already added support](https://github.com/Azure/azure-sdk-for-js/pull/31451).

Do we have a design doc for the feature?

e.g. do we only support it in init? Do we want to support it in get_token()?

**Comment by xiangyan99** [comment]
And do we want to expose it in DAC init?

**Comment by pvaneck** [comment]
Design overview: https://gist.github.com/pvaneck/45964341b0079c6c61743dc89b12eb07

**Review by xiangyan99 — APPROVED** [review]
Please also update the changelog.

**Pull request merged**
