### PR TITLE
add abstract span that wraps the implementation specific spans.

### PR DESCRIPTION
**Pull request by SuyogSoti**

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by SuyogSoti** [comment]
cc: @chlowell @johanste

**Comment by bryevdv** [comment]
My only comment is that I think per the new guidelines this would/should use the ABC decorator. @johanste ?

**Comment by SuyogSoti** [comment]
I can also try to make this a protocol is that better?

**Comment by SuyogSoti** [comment]
ok talked with Johan and ABC is the recommended guideline - fixed it.

**Pull request merged**
