### PR TITLE
PR validation pipelines for Python repo.

### PR DESCRIPTION
**Pull request by mitchdenny**
This PR will add directory specific validation pipelines to this repository. Starting out with just one package files (appinsights). Once that is bedded down I'll submit a PR for the other data plane packages. So far this includes the standard /eng layout for pipelines and templates. Want to get some initial feedback.

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by mitchdenny** [comment]
I've got a pipeline setup on this branch in playground and the build step runs in about 45 seconds (so less than 1/3 of the time of the current build step). I'll need to onboard another package to do a decent test run, I don't think appinsights has many tests? Do you have a recommendation for a data plane package to look at that has good test coverage @scbedd?

**Comment by scbedd** [comment]
@mitchdenny definitely go after `azure-servicebus`. 104 recorded tests. 196 skipped live.

**Comment by scbedd** [comment]
@mitchdenny please note that we support testing for all the python management plane as well. Before we shut off the main CI, we should have a pipeline saved for those.

**Comment by mitchdenny** [comment]
> @mitchdenny please note that we support testing for all the python management plane as well. Before we shut off the main CI, we should have a pipeline saved for those.

This will be a staggered roll out. Get all the pipelines running, make sure they are kicking in when we expect, running what we expect then shutdown the old ones.

**Comment by mitchdenny** [comment]
> @mitchdenny please note that we support testing for all the python management plane as well. Before we shut off the main CI, we should have a pipeline saved for those.

So we should be doing this for say ```azure-mgmt-servicebus``` too then?

**Comment by mitchdenny** [comment]
@scbedd I've kicked off these pipelines to validate the changes (there shouldn't be anything that conflicts with master at the moment). My goal is to get  ```ci.yml``` merged and then stand up a PR validation pipeline on master. Currently ```azure-sdk-for-python - update_pr``` is failing because it looks like it lacks a credential - I'm not sure what this pipeline is for - do you know?

**Comment by mitchdenny** [comment]
It looks like the update_pr build is being triggered because it has a PR validation trigger manually defined on the pipeline definition - accidental?

**Pull request merged**
