### PR TITLE
[Key Vault] Skip test stages for `azure-keyvault-administration` in nightly live tests

### PR DESCRIPTION
**Pull request by mccoyp**
# Description

Recently, we changed from deploying Managed HSMs in nightly live tests to only doing so in weekly tests. `azure-keyvault-administration` jobs are still running in nightly pipelines, though, meaning we deploy KV test resources -- and skip all tests. To save on time and resource quotas, this PR modifies the matrix configuration for live `azure-keyvault-administration` tests:

- Instead of adding an HSM platform to the existing matrix, weekly `azure-keyvault-administration` tests _replace_ the standard matrix with a single HSM platform
- In nightly live tests, `azure-keyvault-administration` replaces the standard matrix with an empty one (since there's nothing to test)

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by mccoyp** [comment]
I cancelled the nightly and weekly pipelines after jobs got picked up to save on resources (and because weekly tests are still flaky), but both show the expected behavior (no platforms staged in nightly tests, and only one platform in public cloud weekly tests) 🙂

**Review by benbp — APPROVED** [review]
I wonder if this could be simplified by wrapping just a `MatrixFilters` statement within the if/else (where the filter is some non-existent key so the output matrix is empty). That way you only declare `MatrixConfigs` once for administration, and you don't need this dummy matrix file either. Looks fine either way.

**Pull request merged**
