### PR TITLE
[text analytics] add perf tests

### LINKED ISSUE #16024: [text analytics] add perf tests

### PR DESCRIPTION
**Pull request by iscai-msft**
fixes #16024

all creds go to @catalinaperalta whose [PR](https://github.com/Azure/azure-sdk-for-python/pull/16969) I copied

### CODE REVIEW

**Review by kristapratico — APPROVED** [review]
🚀

**Comment by catalinaperalta** [comment]
FYI I think you need the empty init file, from the instructions I read in Anna's Perfstress docs.

**Comment by iscai-msft** [comment]
oh really, ok will do, it was working locally without it but can't hurt @catalinaperalta

**Comment by catalinaperalta** [comment]
>oh really, ok will do, it was working locally without it but can't hurt @catalinaperalta

Same, I just put it in because of this line in the docs: 
```
This perfstress_tests directory is a module, and so must contain an __init__.py file. This can be empty.
```

**Pull request merged**
