### PR TITLE
add newline cushion between tags and python snippet in snippet update script

### PR DESCRIPTION
**Pull request by kristapratico**
Resolves https://github.com/Azure/azure-sdk-for-python/issues/29166

A newline between the tag and the code snippet is needed for github.io.

@xiangyan99 this fixes the rendering issue in the github.io page. I'm not sure if we want to merge this during release week since pipelines might fail - what do you think?

### CODE REVIEW

**Comment by xiangyan99** [comment]
Do we also need to update readmes w/ this change?

**Comment by kristapratico** [comment]
> Do we also need to update readmes w/ this change?

Yes, that would probably be the best way to do it. I'll check your original PR and update.

**Review by mccoyp — APPROVED** [review]
Looks good for KV 🙂 Thanks, Krista!

**Review by l0lawrence — APPROVED** [review]
thanks!

**Pull request merged**
