### PR TITLE
Switch to pipeline artifacts for faster publishing.

### PR DESCRIPTION
**Pull request by mitchdenny**
Swapping from FCS to Pipeline Artifacts for publishing artifacts. Pipeline Artifacts is much faster for this kind of thing generally speaking - it should upload this content in a very short period of time (download will generally be faster also).

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by mitchdenny** [comment]
@scbedd can you merge this for me?

**Comment by scbedd** [comment]
> @scbedd can you merge this for me?

Gotchu fam

**Comment by mitchdenny** [comment]
Thank-you sir!

**Comment by mitchdenny** [comment]
Before:
image

After:
image

**Comment by scbedd** [comment]
O-oh. 

Damn.

**Comment by mitchdenny** [comment]
The release pipeline doesn't have such a dramatic improvement (only about 30% faster) but that is because there is no caching. Watch the second publish with the new path _should_ be even faster.

**Comment by mitchdenny** [comment]
Second publish :)

image

Dedup is a beautiful thing!

**Pull request merged**
