### PR TITLE
Update platform matrix to ubuntu 20.04 for storage tests-weekly

### LINKED ISSUE #25170: pypy3.7 failing install - invalid version spec
[example build](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1698079)

Investigate and resolve.

### PR DESCRIPTION
**Pull request by scbedd**
Resolves #25170

@jalauzon-msft I did some digging and ran down what I'm pretty confident is the problem. This is the only difference between the passing nightly livetests, and the failing weekly livetest.

[manual test run](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1703886&view=logs&s=1bcc2fd0-6dea-525b-4e01-7c719fea0eb4)

### CODE REVIEW

**Comment by scbedd** [comment]
image

Confirmed working on tests-weekly. Going to stop that build and merge.

**Review by jalauzon-msft — APPROVED** [review]
Thanks for looking into this Scott!

**Comment by scbedd** [comment]
The CI build failed because it was queued before #25191 merged. A [sample](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1703754&view=results) public storage build was run with that changeset. There is no reason to wait for it.

**Pull request merged**
