### PR TITLE
[formrecognizer] Fix mypy issue

### PR DESCRIPTION
**Pull request by catalinaperalta**

### CODE REVIEW

**Review by kristapratico — APPROVED** [review]
If you want to just merge to main, feel free. I'm not sure we'll get the feature branch in by next Wednesday and I think it would be better to get this in before release week.

**Comment by catalinaperalta** [comment]
> If you want to just merge to main, feel free. I'm not sure we'll get the feature branch in by next Wednesday and I think it would be better to get this in before release week.

Thanks for the heads up. Yes I'll try to get this commit over main instead of your branch. If not I'll send out another quick PR :P

**Comment by catalinaperalta** [comment]
Going with the new branch over main. Closing this.

**Comment by kristapratico** [comment]
> > If you want to just merge to main, feel free. I'm not sure we'll get the feature branch in by next Wednesday and I think it would be better to get this in before release week.
> 
> Thanks for the heads up. Yes I'll try to get this commit over main instead of your branch. If not I'll send out another quick PR :P

I think you can just switch the target branch in the github UI.

**Comment by kristapratico** [comment]
oh nvm you closed it, ignore me!

**Pull request closed without merging**
