### PR TITLE
[DO NOT MERGE] [ADLA] - Catalog - Support list table fragment and table preview

### PR DESCRIPTION
**Pull request by idear1203**
### Swagger PR Links
- [Azure/azure-rest-api-specs#2869: [ADLA] - Cleaning up job.json](https://github.com/Azure/azure-rest-api-specs/pull/2869)
- [Azure/azure-rest-api-specs#2944: [ADLA] - Support catalog list table fragments](https://github.com/Azure/azure-rest-api-specs/pull/2944)
- [Azure/azure-rest-api-specs#3013: [ADLA] - Support table preview](https://github.com/Azure/azure-rest-api-specs/pull/3013)

### Note
- [Azure/azure-rest-api-specs#2869: [ADLA] - Cleaning up job.json](https://github.com/Azure/azure-rest-api-specs/pull/2869)
    - There are no functional changes here just code refactor to make it more readable
- [Azure/azure-rest-api-specs#2944: [ADLA] - Support catalog list table fragments](https://github.com/Azure/azure-rest-api-specs/pull/2944)
    - Catalog_ListTableFragments
- [Azure/azure-rest-api-specs#3013: [ADLA] - Support table preview](https://github.com/Azure/azure-rest-api-specs/pull/3013)
    - Catalog_PreviewTable
    - Catalog_PreviewTablePartition

### CODE REVIEW

**Comment by idear1203** [comment]
@lmazuel, please do not merge this PR. I will add a test for table preview functionality soon.

**Comment by lmazuel** [comment]
@idear1203 If this PR includes breaking changes, I suggest you to use the latest Autorest.Python 3.x adding to your generation `--use=@microsoft.azure/autorest.python@~3.0`.

This is the new standard, but introduces a few breaking changes (see [Network 2.0.0 ChangeLog](https://github.com/Azure/azure-sdk-for-python/blob/master/azure-mgmt-network/HISTORY.rst#200rc1-2018-03-07)).

**Comment by idear1203** [comment]
Thanks, I will take a look soon.

**Comment by idear1203** [comment]
There are some issues on tests. I will reopen this PR when tests are ready

**Pull request closed without merging**
