### PR TITLE
[T1] netapp 2020 11 16

### PR DESCRIPTION
**Pull request by msyyc**
https://github.com/Azure/sdk-release-request/issues/937
--

### CODE REVIEW

**Comment by hildurhodd** [comment]
@msyyc You are skipping a lot of tests. I have created a branch with generated sdk, azure-mgmt-netapp/0.14.0, and updated tests. Here is the branch: https://github.com/hildurhodd/azure-sdk-for-python/tree/netappfiles-tests-for-0-14-0
Unfortunately I can't create a pull request from mine to yours but I could create a PR from mine to Azure/release/v3 if you want.

Azure:release/v3 is still missing tests from previous version. I am waiting on a PR to be approved: https://github.com/Azure/azure-sdk-for-python/pull/14806

**Comment by msyyc** [comment]
@hildurhodd the framwork of test is not very good, I couldn't run live test directly. But I don't have enough time to improve it, so I have to skip some test. Now I have invited you to access my private repo(https://github.com/msyyc/azure-sdk-for-python), you could add test in branch(t1-netapp-2020-11-16). Thank you!

**Comment by hildurhodd** [comment]
> @hildurhodd the framwork of test is not very good, I couldn't run live test directly. But I don't have enough time to improve it, so I have to skip some test. Now I have invited you to access my private repo(https://github.com/msyyc/azure-sdk-for-python), you could add test in branch(t1-netapp-2020-11-16). Thank you!

Can you give hodd@netapp.com access?

**Comment by hildurhodd** [comment]
Tests have been added and broken ones updated. New recordings have been added with correct sdk versions.
All checks are now successful so this PR should be good to go.

**Review by 00Kai0 — APPROVED** [review]

**Pull request merged**
