### PR TITLE
remove Python :: 3.4 classifiers

### PR DESCRIPTION
**Pull request by bryevdv**
Executed via
```
~/work/azure-sdk-for-python/sdk bryanv/classifiers
base ❯ perl -p -i -e 's/^.* "Programming Language :: Python :: 3.4",\n//g' `find ./ -name setup.py`

~/work/azure-sdk-for-python/sdk bryanv/classifiers*
base ❯ perl -p -i -e "s/^.* 'Programming Language :: Python :: 3.4',\n//g" `find ./ -name setup.py`

~/work/azure-sdk-for-python/sdk bryanv/classifiers*
base ❯ grip "Python :: 3\.4"

~/work/azure-sdk-for-python/sdk
```

@lmazuel I'm not sure what the best tags for this would be

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by chlowell** [comment]
FYI, #6080 deletes `azure-security-keyvault`, `azure-security-nspkg`, `azure-keyvault`.

**Comment by lmazuel** [comment]
@bryevdv We don't need the gigantic PR, we just need to update the packaging template here:
https://github.com/Azure/azure-sdk-for-python/blob/b9e3cd7d4e85c2bc7024f5d34151688b8ef9b2d9/tools/azure-sdk-tools/packaging_tools/templates/setup.py#L67

And it will be applied automatically to all new Autorest generated package.

**Comment by bryevdv** [comment]
> And it will be applied automatically to all new Autorest generated package.

Much better, I was not aware the `setup.py`s were templated as well. I made this PR after noticing an explicit change in another PR to remove 3.4 by hand, then noticing that that made things = inconsistent.

**Comment by lmazuel** [comment]
https://github.com/Azure/azure-sdk-for-python/pull/6131

**Pull request closed without merging**
