### PR TITLE
Introduce 'top' filter to Pricesheet API

### PR DESCRIPTION
**Pull request by shbha**

### CODE REVIEW

**Comment by lmazuel** [comment]
Hi @shbha. Thank you for your contribution. Howerver, I can't take it as-is, since this code is auto-generated from a RestAPI meta-description.
@kjeur does pricesheet supports `top` as said in this PR? If yes, could you update the Swagger to integrate it?

**Comment by shbha** [comment]
@lmazuel - Yes, the swagger for Pricesheet API was updated\published\merged prior to this PR, and it does support top. As you'll notice in the new recording, the request and response for pricesheet respects the top setting.

**Comment by lmazuel** [comment]
@shbha @kjeur seems you didn't expose on your github profile your organisations (so you don't have the "Member" tag on your contribution), so I didn't realize this was a contribution from Microsoft and not a random customer :). We have regular contributions from customers that doesn't know we use Swagger, and since you didn't describe the change @shbha , I didn't know there was a Swagger.
This is then a duplicate of https://github.com/Azure/azure-sdk-for-python/pull/1971 (look at the Swagger PR, there was a link to PR 1971).
I take care of this today,
Thanks,

**Comment by lmazuel** [comment]
Merged to feature branch `restapi_auto_consumption/resource-manager`

**Pull request merged**
