### PR TITLE
enable pii logging

### PR DESCRIPTION
**Pull request by xiangyan99**

### CODE REVIEW

**Comment by kashifkhan** [comment]
There should probably be a CHANGELOG update for new behavior when logging is set to DEBUG ?

**Comment by xiangyan99** [comment]
#20474

**Review by kashifkhan — APPROVED** [review]

**Review by mccoyp — COMMENTED** [review]
Are there tests to either validate some aspects of the logging when we expect it, or more importantly, ensure we don't log this info when we don't expect to?

**Comment by xiangyan99** [comment]
> Are there tests to either validate some aspects of the logging when we expect it, or more importantly, ensure we don't log this info when we don't expect to?

Is it by design that if user sets logging level to debug, PII is always logged. I will add tests to make sure it is not logged by default.

**Pull request merged**
