### PR TITLE
[Batch] Update SDK to API version '2019-06-01'

### PR DESCRIPTION
**Pull request by xingwu1**

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by bgklein** [comment]
LGTM.

Whichever admin merge/releases this please include the following PRs in this release as well
https://github.com/Azure/azure-sdk-for-python/pull/5701
https://github.com/Azure/azure-sdk-for-python/pull/5756

**Comment by xingwu1** [comment]
Merged with @bgklein 's 2 PRs.

> LGTM.
> 
> Whichever admin merge/releases this please include the following PRs in this release as well
> #5701
> #5756

**Comment by xingwu1** [comment]
@lmazuel Could you review the change, and merge it?

**Comment by matthchr** [comment]
This looks good to me

**Comment by xingwu1** [comment]
@lmazuel Both me and @bgklein don't have permission to merge the PR. Could you do it for us?

**Pull request merged**
