### PR TITLE
Remove await_prepared_test 

### PR DESCRIPTION
**Pull request by bradleydamato**
Hey @seankane-msft ; took care of this one too

Ran the tox tests:
![image](https://user-images.githubusercontent.com/53579156/95795560-a499f100-0cb8-11eb-9e82-ce3f43015ad6.png

### CODE REVIEW

**Comment by seankane-msft** [comment]
@bradleydamato I'll do my best to get to these by EOD tomorrow (10/14), but if not they will be on the top of my list for next week (I'm oof 10/15-16). If these are for hacktoberfest and there's a deadline just let me know and we can work on this and your other PR to make sure they get in on time.

**Comment by bradleydamato** [comment]
Hey @seankane-msft no rush on my end, take your time and enjoy your time-off :)

**Review by seankane-msft — APPROVED** [review]
LGTM! Thanks for the contribution @bradleydamato !

**Pull request merged**
