### PR TITLE
[AppConfig] Run provider tests in live pipeline

### PR DESCRIPTION
**Pull request by YalinLi0312**
The only pipeline that can run provider live tests is in `tests-weekly` for now, it will be hours to check pipeline results as it's running in three clouds. Configuring a test pipeline for provider to just run live tests in the public cloud can improve efficiency when provider developers want to check live test results.

### CODE REVIEW

**Comment by xiangyan99** [comment]
The stage name Public_Test appears more than once. Stage names must be unique within a pipeline.

**Review by scbedd — APPROVED** [review]
Looks good to me!

**Pull request merged**
