### PR TITLE
Without subnet it is impossible to create a Network Interface

### PR DESCRIPTION
**Pull request by catap**
When try use without this commit, I receive error from azure api server:
```
....
  File "/Library/Python/2.7/site-packages/msrestazure/azure_operation.py", line 629, in result
    raise self._exception
msrestazure.azure_exceptions.CloudError: Subnet reference is required for ipconfiguration /subscriptions/49d0145c-3194-47eb-81d8-0845a97f3377/resourceGroups/jEugene-je/providers/Microsoft.Network/networkInterfaces/jEugene-je/ipConfigurations/default.
```

### CODE REVIEW

**Comment by lmazuel** [comment]
Hi,

Thank you for the bug report! I will not merge the PR, because this part of the code is auto-generated and we need to fix the problem at the source. But we will try to figure this out asap.

@annatisch could you please take a look?
The swagger file is here:
https://github.com/Azure/azure-rest-api-specs/blob/master/arm-network/2015-06-15/swagger/network.json

**Comment by lmazuel** [comment]
@annatisch this is an autorest bug. This commit
https://github.com/catap/azure-sdk-for-python/commit/13060f8e808c08a32630e30debf37ed7ecb4be35

is the generated code with the same file using autorest 02/27 and last one. Could you fix this asap that I can regenerate the file?

Thank you!

**Comment by lmazuel** [comment]
As a workaround you can do (is we assume that you have a dict with your parameters)
```python
conf = NetworkInterfaceIPConfiguration(**myargs)
conf.subnet = myargs['subnet']
```

since `subnet` is a public attribute

**Comment by catap** [comment]
@lmazuel thanks, I did it.

**Comment by lmazuel** [comment]
I just released 2.0.0rc2 which fixes the bug. Please feel free to re-open if you experience any trouble.

Thank you again for your report!

**Pull request closed without merging**
