### PR TITLE
Fix ServiceBus schedule related operation error due to the utc timestamp

### PR DESCRIPTION
**Pull request by yunhaoling**
Update all the datetime consistent to utc time.

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by yunhaoling** [comment]
@annatisch Hello Anna, please review my PR, thanks.

One question:
Should we set the requirements of uamqp in setup.py to "uamqp>=1.2.0,<2.0.0" in both ServiceBus and EventHub Track 2?

**Comment by yunhaoling** [comment]
> The changes look good to me - are we going to release this now?

@annatisch 

Just update the requirement version in uamqp  to 1.2.0 as I found:
1. uamqp requirement need to be consistent with eventhub.
2. uamqp 1.2.0 has fixed bugs.

I think we should release servicebus after we release the uamqp 1.2.0.

**Comment by yunhaoling** [comment]
@annatisch updated history,readme, uamqp requirements, version number, looks good to you?

**Pull request merged**
