### PR TITLE
Replace list() and dict() with literals

### PR DESCRIPTION
**Pull request by atombrella**
# Description

* `from __future__ import print_function, unicode_literals, division` is a thing of the past!
* `dict()` -> `{}` and `list()` -> `[]` are improvements both in terms of Pythonic code and speed:
https://switowski.com/blog/dict-function-vs-literal-syntax/
* Removed the few `u"string"` markers I could find.

It's quite time-consuming to change instances of `dict(a="hello", b="world")` and I don't plan on doing that!

# All SDK Contribution checklist:
- [X] **The pull request does not introduce [breaking changes]**
- [X] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [X] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [X] Title of the pull request is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [X] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by atombrella** [comment]
I don't really understand the test failures, and why this PR cause failing builds.

Note that there are tons of https://docs.python.org/3/library/datetime.html#datetime.datetime.utcnow in the code! They are also highlighted as warnings in the test runs.

**Comment by iscai-msft** [comment]
Thanks for opening this PR @atombrella!

Here is my analysis of the failing steps:
1. The code changes have not been formatted (see failing ci [here](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4340301&view=logs&j=b70e5e73-bbb6-5567-0939-8415943fadb9&t=efe9ac6d-3fdb-50af-24e1-4319f36eecb4)). Follow steps [here](https://github.com/Azure/azure-sdk-for-python/blob/main/doc/eng_sys_checks.md#running-locally) for formatting
2. I think the test failures might not be related to you. @annatisch it seems that cosmos is failing with [service request errors](https://dev.azure.com/azure-sdk/public/_build/results?buildId=4340301&view=logs&j=2dab92d7-429a-5df6-2af2-778bee3d4a2e&t=059e8127-c378-51f4-d737-b7a646d5a5f6&l=13035), are you aware of any cosmos issue? Thanks!

**Comment by iscai-msft** [comment]
@atombrella i think some of the black formatting of files not originally touched by you have made their way into the PR, can you remove those? Thanks!

**Comment by atombrella** [comment]
@iscai-msft I deleted the commit. black then fails :/

I think the approach outlined in https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view is a good solution for the failing black/formatting tests. `black` formats boatloads of lines I didn't touch in my changes.

Note that snippets similar (and identical) to this is also in various places of the code-base.
```python
        # Consider this is real string
        try:
            if isinstance(data, unicode):  # type: ignore
                return data
        except NameError:
            return str(data)
        else:
            return str(data)
```

**Comment by iscai-msft** [comment]
@atombrella are you able to run the black command from within each of the sdks you're touching with your changes, instead of over the entire repo? Thank you so much again for doing this!

**Comment by atombrella** [comment]
I am not a fan of this! `git blame` will be useless after this :(

**Comment by iscai-msft** [comment]
I understand your frustration, it does look like `black` has been behaving weird in our pipelines. @scbedd is actually working on this in a separate pr (linked [here](https://github.com/Azure/azure-sdk-for-python/pull/38212/files)). He should be almost done with this PR, once this is in, do you mind pulling and trying again to see if the black issues are fixed?

Thank you so much again for your contribution, and apologies for it not going super smoothly, but your work is greatly appreciated.

**Comment by iscai-msft** [comment]
talked with @scbedd offline and we'll handle re-running this PR ourselves once his fix is in. Thanks for your patience

**Comment by scbedd** [comment]
Ok. `Analyze` is now clean after my changes to `black`.

The test failures on `azure-cosmos` are known. @iscai-msft please double-check my verification before signoff, but if you only see setup failures invoking `azure-cosmos` as part of `python - pullrequest`, then IMO this PR is ready to go in.

**Comment by iscai-msft** [comment]
yep this looks good. Thanks so much @scbedd and @atombrella for doing this awesome work! I'm going to approve and merge. 

Thanks so much again @atombrella for all of your work and patience

**Review by iscai-msft — APPROVED** [review]

**Comment by iscai-msft** [comment]
ok merged it, thank you so much again for your contribution and your patience @atombrella. Thanks for working with us, it's been a pleasure on our part

**Pull request merged**
