### PR TITLE
[AutoPR] resources/resource-manager

### PR DESCRIPTION
**Pull request by lmazuel**

### CODE REVIEW

**Comment by lmazuel** [comment]
@AutorestCI rebase

**Comment by chidmdxx** [comment]
Don't see the new version in https://github.com/Azure/azure-rest-api-specs/pull/2560 fully added

**Comment by lmazuel** [comment]
@chidmdxx I don't understand your comment?

**Comment by lmazuel** [comment]
@AutorestCI rebase

**Comment by chidmdxx** [comment]
sorry what I meant is that I added a new api version, and expected to see some files that contained 2018-02-01 in their path

**Comment by chidmdxx** [comment]
@lmazuel Hi, what is missing to close this PR and publish the new package?

**Comment by lmazuel** [comment]
@AutorestCI rebase

**Pull request merged**
