### PR TITLE
Update README.rst file

### PR DESCRIPTION
**Pull request by gmsantos**
# Description

Small changes to README.rst file to match the current supported version and also links to the version support policy.

Although, I'm not sure where this file is used, maybe it's just an older file and README.md is the canonical file now.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by mccoyp** [comment]
Hi @gmsantos, thank you for opening a PR! I'll tag some folks who should be able to leave a review and we'll get back to you as soon as possible.

**Review by xiangyan99 — APPROVED** [review]

**Comment by xiangyan99** [comment]
Thanks for your contribution.

**Pull request merged**
