### PR TITLE
Fix Document Intelligence README Issue

### PR DESCRIPTION
**Pull request by dotnet-7**
Fix https://github.com/Azure/azure-sdk-for-python/issues/35404

@rohit-ganguly , @lmazuel , @YalinLi0312 for notification.

### CODE REVIEW

**Comment by rohit-ganguly** [comment]
Hi, I did some digging through the Document Intelligence README and couldn't find anywhere that defines the get_words() function. I would try to ensure the get_words() function is defined somewhere because people are going to copy-and-paste these code blocks.

https://github.com/Azure/azure-sdk-for-python/blob/74509c2efa003f2f5328beb000e923804f9a394c/sdk/documentintelligence/azure-ai-documentintelligence/samples/sample_analyze_read.py#L27

It's defined above in one of the samples I found.

**Comment by jerryshia** [comment]
@rohit-ganguly  Yes, the get_words() function was not defined in the README. The code has been updated according to your suggestions. Please review it.

**Review by rohit-ganguly — APPROVED** [review]

**Comment by v-xuto** [comment]
@rohit-ganguly Could you help merge this PR? Thanks a lot.

**Comment by YalinLi0312** [comment]
This PR is no longer needed. We did some changes in README sample recently, @rohit-ganguly @jerryshia @v-xuto can you check the most recent README.md in main? https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/documentintelligence/azure-ai-documentintelligence/README.md#extract-layout

**Comment by jerryshia** [comment]
The issue #35404  no longer exists.

**Pull request closed without merging**
