### PR TITLE
[Monitor] Refactor tests

### PR DESCRIPTION
**Pull request by pvaneck**
This applies to both query and ingestion tests:

* Better integration with test proxy using fixtures.
* Updated `test-resources.json` file to be a bicep file. Aso cleaned out resources that were deployed but never used (i.e. App Config, Event Hubs)
* Removed dependency on preallocated resources for live tests. Now live tests will only use resources deployed from the `test-resource.bicep` file.
* Integrated tests with assets repo. Added playback tests and recordings into assets repo tag.
* Increased msrest version in setup.py as the mindependency test job was failing because the msrest version used was too old.

Closes: #25213

### CODE REVIEW

**Comment by benbp** [comment]
Love the test resource changes!

**Review by pvaneck — COMMENTED** [review]
Note: Pending update to use the assets repo for recordings before merging. This should substantially reduce the size of this PR.

**Review by mccoyp — APPROVED** [review]
Amazing! Thanks so much for your work on this 🙂

**Pull request merged**
