### PR TITLE
added mimetype based on file extension

### PR DESCRIPTION
**Pull request by hiroyah**

### CODE REVIEW

**Comment by hiroyah** [comment]
Came across this sample code to upload directory to blob, but I wanted to set mime type as well. So ended up changing the code.
Then, I thought it might be good to send pull request, just in case.

**Comment by rakshith91** [comment]
Thanks for the contribution @hiroyah 
Can you add a different sample instead of changing the existing one?
While I agree it's a good idea to add this, we would want to keep the "happy path" in this file.

**Comment by hiroyah** [comment]
> Thanks for the contribution @hiroyah
> Can you add a different sample instead of changing the existing one?
> While I agree it's a good idea to add this, we would want to keep the "happy path" in this file to make it more customer friendly

OK. Added a new file, then reverted the original file.

**Review by rakshith91 — APPROVED** [review]
Thanks (y)

**Comment by xiangyan99** [comment]
@xiafu-msft could you take a look if this is valid?

**Comment by xiangyan99** [comment]
@tasherif-msft Given this is a storage sample, could you also take a look?

**Review by tasherif-msft — APPROVED** [review]

**Pull request merged**
