### PR TITLE
Hotfix for pipeline python version 2.7/3.6 task issues

### PR DESCRIPTION
**Pull request by AikoBB**
# Description

Hotfix for pipeline 2.7/3.6 task issues because of other SDK package teams stopped the support for python 2.7/3.6, excluded 2.7/3.6 tasks run to avoid pipeline failure.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](../CONTRIBUTING.md##building-and-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by petrsvihlik — APPROVED** [review]
we just need to make sure to remove this workaround as part of the https://skype.visualstudio.com/SPOOL/_workitems/edit/2682357

**Comment by xiangyan99** [comment]
Do you want to stop supporting py2.7?

You don't need to filter the jobs (we will do it in a central place when Scott is back).

But you may need to update your readme, setup, etc. 

You can take this as a reference.
https://github.com/Azure/azure-sdk-for-python/pull/22224

**Comment by AikoBB** [comment]
> Do you want to stop supporting py2.7?
> 
> You don't need to filter the jobs (we will do it in a central place when Scott is back).
> 
> But you may need to update your readme, setup, etc.
> 
> You can take this as a reference. #22224

@xiangyan99 we gonna stop supporting 2.7/3.6 but we'll do make changes in other PR. This is a hotfix, our scheduled pipeline was failing because other teams stopped supporting 2.7, will remove this hotfix after Scot's configuration

**Comment by xiangyan99** [comment]
If you have python_requires=">=3.7", in setup.py, our pipeline will be smart enough to skip them. (That's why I said you didn't need it :)).

The change looks good to me.

**Review by petrsvihlik — APPROVED** [review]

**Comment by jaystyles** [comment]
U

**Pull request merged**
