### PR TITLE
[ServiceBus] Support for delivery tag lock tokens

### PR DESCRIPTION
**Pull request by annatisch**

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by andreacassioli** [comment]
Hi, Is there any indication on when this fix will be available in stable release?

**Comment by KieranBrantnerMagee** [comment]
Hey Andreacassioli,

We've begun the process of releasing a new version, I'm admittedly hesitant to make any promises that I don't have guarantees on, but I'm hopeful that you'll see something as this week progresses.  

(At the very least that something may be an update here with a concrete release date, will make sure to keep you in the loop regardless.)

**Comment by andreacassioli** [comment]
Hi @KieranBrantnerMagee , thanks for the reply. 
No need for a promise! I am gonna keep an eye on the sdk releases...

**Comment by KieranBrantnerMagee** [comment]
Hello again; wanted to follow-up on my one week guestimate with an update:  In doing validation over the weekend we found a small issue that [a PR is now out for,](https://github.com/Azure/azure-sdk-for-python/pull/8690) will be rerunning once that gets in and if that goes green we'll be good to go.

Thanks as always for your patience!

**Comment by andreacassioli** [comment]
Hi @KieranBrantnerMagee , thank you very much for the update!

**Comment by andreacassioli** [comment]
Hi @KieranBrantnerMagee I assume this patch is release in 0.50.3. I cannot find explicit mention in the release notes....

**Pull request merged**
