### PR TITLE
[storage-blob] skip blob echo request id test

### PR DESCRIPTION
**Pull request by kristapratico**
Issue tracked [here]( https://github.com/Azure/azure-sdk-for-python/issues/8098)
Waiting for batch endpoints to be fixed.

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by xiafu-msft** [comment]
Ahh would you mind explaining a bit more about why we skip this one? (I didn't quite get even looked at the issue)

**Comment by kristapratico** [comment]
> Ahh would you mind explaining a bit more about why we skip this one? (I didn't quite get even looked at the issue) ^_^

@lmazuel

**Comment by kristapratico** [comment]
The changes in this PR were moved to #8134

**Comment by mayurid** [comment]
@xiafu-msft : this is for the PR https://github.com/Azure/azure-sdk-for-python/pull/8118 which was required due to a service end issue. Since the check was relaxed the appropriate test was commented. 
//cc:@lmazuel

**Pull request closed without merging**
