### PR TITLE
Turn on federated auth by default

### PR DESCRIPTION
**Pull request by xiangyan99**

### CODE REVIEW

**Comment by weshaggard** [comment]
I would also suggest we delete all the places we set this explicitly to true in any tests.yml files where we already set it as that is just noise. https://github.com/search?q=repo%3AAzure%2Fazure-sdk-for-python+UseFederatedAuth&type=code

**Comment by xiangyan99** [comment]
> I would also suggest we delete all the places we set this explicitly to true in any tests.yml files where we already set it as that is just noise. https://github.com/search?q=repo%3AAzure%2Fazure-sdk-for-python+UseFederatedAuth&type=code

After visiting some tests.yml, I prefer to keep those explicit settings for now to track which services have been migrated. Your ideas?

**Comment by weshaggard** [comment]
Can't you count the reverse? i.e. the ones that opt-out like cosmos? If you keep the setting there people will end up copy/pasting it around forever and it really will be a dead property.

**Comment by xiangyan99** [comment]
We agreed that we will clean all in-tests.yml settings when we move to auxiliary tenant.

**Comment by xiangyan99** [comment]
Opened https://github.com/Azure/azure-sdk-for-python/issues/36572 to track the work.

**Review by scbedd — APPROVED** [review]
Seems reasonable to me. They're probably already aware but please let the cosmos folks know that this has been delayed for them.

**Pull request merged**
