### PR TITLE
Replaced rikogeln with flborn in the CODEOWNER section of Mixed Reality

### PR DESCRIPTION
**Pull request by FlorianBorn71**
# Description

Please add an informative description that covers that changes made by the pull request and link all relevant issues.

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [X ] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by jsquire — CHANGES_REQUESTED** [review]
`flborn` does not have the required public organization memberships or permissions to be a code owner.  

Did you mean to use `FlorianBorn71` ?   That account needs the Microsoft organization membership made public but is otherwise correct.

For more information, please see:
- [Azure SDK onboarding](https://eng.ms/docs/products/azure-developer-experience/onboard/requirements) _(Microsoft internal)_
- [Azure SDK onboarding assistance](https://teams.microsoft.com/l/channel/19%3ade3fce22c2994be18cac50502c55f717%40thread.skype/Azure%2520SDK%2520Onboarding?groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47) _(Microsoft internal)_

**Comment by FlorianBorn71** [comment]
> `flborn` does not have the required public organization memberships or permissions to be a code owner.
> 
> Did you mean to use `FlorianBorn71` ? That account needs the Microsoft organization membership made public but is otherwise correct.
> 

Good find. flborn is my MS alias, but here it should be FlorianBorn71.

**Comment by FlorianBorn71** [comment]
@jsquire, fixed ;-)

**Comment by jsquire** [comment]
> @jsquire, fixed ;-)

I'll get this merged in.   Please join the Microsoft org on GitHub and make that membership public.

**Review by jsquire — APPROVED** [review]

**Comment by jsquire** [comment]
Entry failing linter is not part of this change set.

**Pull request merged**
