### PR TITLE
Update pylint-checker-guidelines to 0.0.7

### PR DESCRIPTION
**Pull request by praveenkuttappan**
Pylint-checker-guidelines was updated to 0.0.5 and this is breaking for anomalydetector. Reverting this version to last known working version.

### CODE REVIEW

**Review by l0lawrence — APPROVED** [review]
thank you

**Comment by praveenkuttappan** [comment]
@LibbaLawrence This PR pipeline is failing with error `Could not find a version that satisfies the requirement pylint-guidelines-checker==0.0.6` 

Isn't this version published yet to internal feed?

**Comment by l0lawrence** [comment]
> @LibbaLawrence This PR pipeline is failing with error `Could not find a version that satisfies the requirement pylint-guidelines-checker==0.0.6`
> 
> Isn't this version published yet to internal feed?

It should be released now; I hadn't manually run the pipeline.

**Comment by praveenkuttappan** [comment]
We can update this PR to 0.0.7 once new version to fix KV issue is released.

**Comment by praveenkuttappan** [comment]
I have queued a new KV pipeline run against this PR. @scbedd I hate to ask this on a release week. But we need to merge this to resolve KV pipeline issue to release KV package tomorrow.

**Comment by praveenkuttappan** [comment]
> I have queued a new KV pipeline run against this PR. @scbedd I hate to ask this on a release week. But we need to merge this to resolve KV pipeline issue to release KV package tomorrow.

Alternate option is to skip this step and manually verify review diff before releasing it.

**Pull request merged**
