### PR TITLE
Add support for the OSImage /details endpoint

### PR DESCRIPTION
**Pull request by bear454**
The OSImage representation return by the default API endpoint does not include any publishing data, such as replication regions and progress.

### CODE REVIEW

**Comment by bear454** [comment]
@lmazuel - can you review this, please?

**Comment by lmazuel** [comment]
Looks good to me, sorry about the delay.
Thank you!

**Comment by bear454** [comment]
@lmazuel : this code still hasn't been released... will the legacy package be upgraded along with the 2.0 release?

**Comment by lmazuel** [comment]
Yes you are right I will try to a release asap.
Thank you for your report.

**Comment by lmazuel** [comment]
Hi @bear454 , I just released [0.20.3](https://pypi.python.org/pypi/azure-servicemanagement-legacy/0.20.3)

It will be a direct dependency in the next azure full meta-package, but you can use it right now.

Thank you for your feedback, tell me you have any other questions!

**Pull request merged**
