### PR TITLE
Added Blob name encoding

### PR DESCRIPTION
**Pull request by tasherif-msft**

### CODE REVIEW

**Comment by tasherif-msft** [comment]
@scbedd any idea why this failure is happening?

**Comment by scbedd** [comment]
@tasherif-msft it looks a random failure during the `artifact upload` stage early exited the `build` stage, the rest failed because the necessary `packages` artifact isn't actually present.

[Exact Error Location](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1172409&view=logs&j=7e6a3fb7-dbfe-5169-4db8-92b72295ba6c&t=c9435986-9273-5047-cff5-b7edac6243b9)

I'd give it a retry tbh. You should be fine.

**Comment by tasherif-msft** [comment]
@scbedd it seems even restarting the pipeline is not working :S

**Comment by scbedd** [comment]
@tasherif-msft it's a NEW issue now! 

Please check the Engineering System teams channel, `github` disabled a certain checkout style. I [patched main](https://github.com/Azure/azure-sdk-for-net/commit/af9d76c205246c7f629d0139c3061d8aae438010) but it looks like `feature/storage-stg80` is your target branch, so it wouldn't have _gotten_ that fix.

My recommendation? Update `feature/storage-stg80` from `main`. If not that, then cherry pick the commit I linked above.

**Pull request closed without merging**
