### PR TITLE
feedRangeChangeBasedOnAPIReview

### PR DESCRIPTION
**Pull request by xinlian12**
A follow up PR based on the API review. 

- For get_feed_ranges, changed to return Iterable[Dict[str, Any]]
- for query_items_change_feed, accept feed_range with type Dict[str, Any]

### CODE REVIEW

**Review by tvaron3 — APPROVED** [review]
LGTM

**Review by simorenoh — APPROVED** [review]
LGTM! 👍

**Comment by simorenoh** [comment]
Pylint is complaining about these two lines, should be g2g after that:
image

**Pull request merged**
