### PR TITLE
Add explicit requirement for azure-core in mgmt-compute

### PR DESCRIPTION
**Pull request by psalaberria002**
https://github.com/Azure/azure-sdk-for-python/pull/34770 added a direct dependency for azure.core, and it actually requires this to be newer than 1.28. 
 Related to https://github.com/Azure/azure-sdk-for-python/issues/34091

# Description

Please add an informative description that covers that changes made by the pull request and link all relevant issues.

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [ ] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by jim-cooley — APPROVED** [review]

**Review by jim-cooley — COMMENTED** [review]
though i can't approve, this indeed fixes the issue with azure-mgmt-compute requirement of azure-core.  specifically, azure-mgmt-compute requires the property 'SensitiveHeaderCleanupPolicy' on 'azure.core.pipeline.policies', which is only present in versions of azure-core >= 1.28.1

**Comment by annatisch** [comment]
Hi @msyyc - could you confirm whether this setup.py is auto-generated and therefore the codegen needs updating for this dependency?

**Comment by msyyc** [comment]
- Python Mgmt SDK depends on azure-mgmt-core instead of azure-core directly
- Python Mgmt SDK is auto generated and it doesn't use `azure.core.pipeline.policies.SensitiveHeaderCleanupPolicy` by default

Above all, if your application want to use `SensitiveHeaderCleanupPolicy`, it is better to add it by yourself instead of changing SDK dependency. After all, not all SDK users need `SensitiveHeaderCleanupPolicy`

**Comment by jim-cooley** [comment]
actually, i don't want to use SensitiveHeaderCleanupPolicy, but if you write the following code:
        self.credential = DefaultAzureCredential()
        self.resource_client = ResourceManagementClient(self.credential, self.subscription_id)
        self.compute_management_client = ComputeManagementClient(self.credential, self.subscription_id)

 It will fail with "azure.core.pipeline.policies" does not have property 'SensitiveHeaderCleanupPolicy'.  that is when using the latest mgmt-compute with an azure-core prior to 1.28.1.  perhaps the reference is indirect via azure-mgmt-core, however the SDK itself uses this property so this fails at runtime.

**Comment by aszodiba** [comment]
I'm having totally the same issue as it is described by @jim-cooley. 
I'll try to simply access synapse notebook contents by using azure-synapse-artifacts.
Using the recommended ArtifactsClient by simply adding credentials and the endpoint I get the same error. Hence it should be reopened.
image

**Pull request closed without merging**
