### PR TITLE
retry on 429

### PR DESCRIPTION
**Pull request by xiangyan99**

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by bryevdv** [comment]
429 is "Too Many Requests" is the solution to make another request immediately? A 429 response may come with a `Retry-After` header indicating how long should be waited before a retry is attempted:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429

**Comment by bryevdv** [comment]
LGTM modulo the unrelated failing CI job

**Comment by xiangyan99** [comment]
> 429 is "Too Many Requests" is the solution to make another request immediately? A 429 response may come with a `Retry-After` header indicating how long should be waited before a retry is attempted:
> 
> https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429

Yes. We have logic in retry policy to honor 'Retry-After' from the header

**Pull request merged**
