### PR TITLE
Clean up azure-mgmt-agfood and azure-mgmt-azureadb2c which hit EOL 3/31/2023

### PR DESCRIPTION
**Pull request by JimSuplizio**
The original [PR](https://github.com/Azure/azure-sdk-for-python/pull/30599), because we had to release one last time, ended up with merge issues. It was easier to just recreate the PR.

[azure-mgmt-agfood](https://github.com/Azure/azure-sdk/blob/main/_data/releases/latest/python-packages.csv?plain=1#L85) and [azure-mgmt-azureadb2c](https://github.com/Azure/azure-sdk/blob/main/_data/releases/latest/python-packages.csv?plain=1#L99) both hit EOL on 3/31/2023. This means these are no longer supported and there's no need for them to be part of the repository anymore.

I've already deleted both sets of public and private pipelines. This PR is to remove the source code from the repository.

//CC @scbedd and @mario-guerra so you're both aware.

### CODE REVIEW

**Review by scbedd — APPROVED** [review]

**Comment by scbedd** [comment]
[azure-mgmt-agfood](https://pypi.org/project/azure-mgmt-agfood/)
[azure-mgmt-azureadb2c](https://pypi.org/project/azure-mgmt-azureadb2c/)

both reflecting inactive classifier and deprecation notice. Merge it!

**Comment by JimSuplizio** [comment]
I'm going to override check enforcer since there's nothing that'll run that'll test these changes

**Pull request merged**
