### PR TITLE
[AppConfig] Enable to run sphinx in pipeline

### PR DESCRIPTION
**Pull request by YalinLi0312**
Resolves https://github.com/Azure/azure-sdk-for-python/issues/33541

### CODE REVIEW

**Review by l0lawrence — COMMENTED** [review]
lgtm but pinging @kristapratico just to make sure will warnings cause sphinx to fail on the flip over or if the CI is green we are good?

**Review by xiangyan99 — APPROVED** [review]

**Comment by kristapratico** [comment]
> lgtm but pinging @kristapratico just to make sure will warnings cause sphinx to fail on the flip over or if the CI is green we are good?

Warnings will cause build failures. I don't see any warnings for azure-appconfiguration, though?

https://dev.azure.com/azure-sdk/public/_build/results?buildId=3669682&view=logs&j=4259cd7e-6a4b-5ca5-581a-0ae020cd9d20&t=4d670c9c-5acd-5cc3-aede-d35282ac764a&l=3464

**Comment by YalinLi0312** [comment]
> > lgtm but pinging @kristapratico just to make sure will warnings cause sphinx to fail on the flip over or if the CI is green we are good?
> 
> Warnings will cause build failures. I don't see any warnings for azure-appconfiguration, though?
> 
> https://dev.azure.com/azure-sdk/public/_build/results?buildId=3669682&view=logs&j=4259cd7e-6a4b-5ca5-581a-0ae020cd9d20&t=4d670c9c-5acd-5cc3-aede-d35282ac764a&l=3464

Hi @kristapratico - I think @LibbaLawrence is talking about this warning: https://dev.azure.com/azure-sdk/public/_build/results?buildId=3669682&view=logs&j=4259cd7e-6a4b-5ca5-581a-0ae020cd9d20&t=4d670c9c-5acd-5cc3-aede-d35282ac764a&l=3820

**Comment by kristapratico** [comment]
> > > lgtm but pinging @kristapratico just to make sure will warnings cause sphinx to fail on the flip over or if the CI is green we are good?
> > 
> > 
> > Warnings will cause build failures. I don't see any warnings for azure-appconfiguration, though?
> > https://dev.azure.com/azure-sdk/public/_build/results?buildId=3669682&view=logs&j=4259cd7e-6a4b-5ca5-581a-0ae020cd9d20&t=4d670c9c-5acd-5cc3-aede-d35282ac764a&l=3464
> 
> Hi @kristapratico - I think @LibbaLawrence is talking about this warning: https://dev.azure.com/azure-sdk/public/_build/results?buildId=3669682&view=logs&j=4259cd7e-6a4b-5ca5-581a-0ae020cd9d20&t=4d670c9c-5acd-5cc3-aede-d35282ac764a&l=3820

We're only turning on strict_sphinx for azure-appconfiguration: https://github.com/Azure/azure-sdk-for-python/pull/35079/files#diff-f33ba15723f99d9b8eb887bf241f9acb8b6746e128598edf492c903c3129b180

azure-mgmt-appconfiguration is not running strict-sphinx, that would need to be enabled in its own pyproject.toml.

**Pull request merged**
