### PR TITLE
[typing] Add DefaultAzureCredential to allowed types for credentials in KeyVaultClient

### PR DESCRIPTION
**Pull request by soer7022**
# Description

The current typing for KeyVaultClient does not match the steps described in current documentation: [here](https://docs.microsoft.com/en-us/azure/key-vault/secrets/quick-create-python?tabs=azure-cli#create-the-sample-code)

I have added the `DefaultAzureCredential` from `azure.identity` based on the current recommended steps from the documentation.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by mccoyp** [comment]
Hi @soer7022, thank you for opening a PR and contributing to the SDK!

In this instance though, I believe the current typing is correct. Key Vault clients (and other clients in the SDK) don't necessarily require `azure-identity` credentials. They accept any credential that supports the [TokenCredential protocol](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/core/azure-core/CLIENT_LIBRARY_DEVELOPER.md#tokencredential-protocol), which does include the DefaultAzureCredential, but also includes other `azure-identity` credentials and even custom credentials ([some examples](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/samples/custom_credentials.py)). So, TokenCredential is used as the credential type here and elsewhere 🙂

Do you think the documentation should be more clear about that? And/or is there a type checker that raised an error when providing a DefaultAzureCredential to a Key Vault client? If so, that might be something we'd want to find a fix for.

**Comment by soer7022** [comment]
Thank you for the detailed reply 😄 

The main reason that I made this pull request is due to PyCharm flagging it as a incorrect type:

Screenshot 2022-07-11 at 07 35 14

Is my fix the right fix? Or should we look into making something more general?

**Comment by mccoyp** [comment]
@soer7022 Thank you for providing context about the issue! That's the first time I've seen an IDE raise a concern with the typing, and suggests that there's something we can do to make the protocol implementation more clear to Python (and users).

I can't reproduce the PyCharm warning on my end unfortunately -- I'm using a Python 3.10.0 interpreter on PyCharm Community Edition 2021.1.3. Could I know what interpreter and PyCharm version you're using?

If you don't mind, I'd like to continue this discussion on https://github.com/Azure/azure-sdk-for-python/issues/25175, an issue I opened to track this. It would be great if you could continue to help us to fix this! If not, that's no problem -- I appreciate that you brought this to our attention 🙂

I'm going to close this PR though, since the solution should come from the credential definition and/or the `TokenCredential` protocol definition.

**Comment by soer7022** [comment]
Thank you! I will add further details and comments on the issue

**Pull request closed without merging**
