### PR TITLE
Batch - Update to latest REST API

### PR DESCRIPTION
**Pull request by bgklein**

### CODE REVIEW

**Comment by bgklein** [comment]
@xingwu1 for review

**Comment by bgklein** [comment]
@lmazuel @annatisch any idea why the CI is failing? Seems to be complaining about setup.py which is unchanged

**Comment by lmazuel** [comment]
@bgklein 
```
The project's long_description has invalid markup which will not be rendered on PyPI. The following syntax errors were detected:
line 64: Error: Unexpected indentation.
```

**Comment by lmazuel** [comment]
@xingwu1 @bgklein @matthchr You might want to apply the same "models" update than azure-batch, since it's breaking release. At your convenience.

**Comment by bgklein** [comment]
Good thought! I have ran the script so now both should be aligned. Good to merge whenever you have time

**Comment by bgklein** [comment]
Going to update one of the method comments real quick

**Comment by bgklein** [comment]
@lmazuel

**Comment by bgklein** [comment]
@annatisch do you have merge/publish permissions? Waiting on this to be published to update CLI components.  Thanks.

**Comment by bgklein** [comment]
@lmazuel could we get this merged?

**Comment by lmazuel** [comment]
Sorry @bgklein holiday + training, got far far away from a keyboard for a few days :/
Merge and release now, thanks for your patience

**Pull request merged**
