### PR TITLE
fixed message attachment defect

### PR DESCRIPTION
**Pull request by howieleung**
# Description
Our samples failed at

    attachment = MessageAttachment(file_id=file.id, tools=CodeInterpreterTool().definitions)

And

    attachment = MessageAttachment(file_id=file.id, tools=FileSearchTool().definitions)

It is because tools keyword expects List["MessageAttachmentToolDefinition"] where MessageAttachmentToolDefinitionis Union of FIleSearchToolDefinition and CodeInterpreterToolDefinition.

To fix it, I did 2 things:
1.  change CodeInterpreterTool().definitions and FileSearchTool().definitions to return List[CodeInterpreterToolDefinition] and List[FIleSearchToolDefinition] instead of List[ToolDefinition].   But to do this, I need to change for all tools to return their specific types of tool definitions.
2. List doesn't support covariant types.   With that said, with tool: List[Union[FIleSearchToolDefinition, CodeInterpreterToolDefinition]], you can't assign it List[CodeInterpreterToolDefinition] or List[FIleSearchToolDefinition] .   So I overload constructor of MessageAttachment.

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [ ] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by jhakulin** [comment]
This is to main branch?

**Comment by jhakulin** [comment]
Is it functional failure in

attachment = MessageAttachment(file_id=file.id, tools=CodeInterpreterTool().definitions)

or static analyser failure?

**Comment by howieleung** [comment]
> Is it functional failure in
> 
> attachment = MessageAttachment(file_id=file.id, tools=CodeInterpreterTool().definitions)
> 
> or static analyser failure?

It faile

> Is it functional failure in
> 
> attachment = MessageAttachment(file_id=file.id, tools=CodeInterpreterTool().definitions)
> 
> or static analyser failure?

It is a pylance error that cannot be resolved by casting.
image

**Comment by howieleung** [comment]
> This is to main branch?

Yes.   In sync channel, I mentioned that I will wait for the decision to merge to main or beta 3.0.1

**Review by jhakulin — APPROVED** [review]

**Pull request merged**
