### PR TITLE
Move template project to new repo structure

### PR DESCRIPTION
**Pull request by weshaggard**
cc @Azure/azure-sdk-eng 

Contributes to https://github.com/Azure/azure-sdk-for-python/issues/4319

@scbedd could you please have a look at the script updates?

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by weshaggard** [comment]
@scbedd @lmazuel do either of you guys know if the "Python Build Drop" CI leg is still valid or should we remove it from the required set of CI checks now?

**Comment by weshaggard** [comment]
Looks like "Python Build Drop" is an optional leg that only gets triggered for some types of PR's. Given that I'm going to remove it from the required CI legs. @lmazuel please let me know if you disagree with that and we can figure out a different approach.

**Pull request merged**
