### PR TITLE
Enable long path for Windows test

### PR DESCRIPTION
**Pull request by praveenkuttappan**
Cognitive services is failing to test with dev build version due to path name for few files exceeding 260 chars. This fix is to enable long path name on windows host.

Additional fix is to record list of packages installed as part of every test to aid in debugging when test fails suddenly due to new dependent external package.

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by mitchdenny** [comment]
To date we've resisted requiring long path support on Windows and instead done the work necessary to make sure our code bases when cloned and built will work with a regular Windows path length configuration. This seems like a departure from that?

**Comment by scbedd** [comment]
@mitchdenny You are correct. @praveenkuttappan let's talk about options here.

**Comment by scbedd** [comment]
@mitchdenny Thanks for the call-out here. I had a convo with the owner of the package that was hitting these issues, and it looks like we're reverting those changes regardless. This change is unnecessary as a result.

**Comment by weshaggard** [comment]
Good this particular issue got fixed a different way. Just to reiterate with @mitchdenny said though we shouldn't enable long path like this in our CI legs. We should instead fix the paths that are too long.

**Pull request closed without merging**
