### PR TITLE
Adding SQL Mgmt

### PR DESCRIPTION
**Pull request by lmazuel**

### CODE REVIEW

**Comment by thenewwazoo** [comment]
I'm not having any success in generating docs for the mgmt.sql stuff. I can generate ref/azure.mgmt.sql.rst but the resultant html files end up empty. (`python ./generate_doc.py; make`). Am I missing a step?

**Comment by lmazuel** [comment]
Hi @thenewwazoo 
This is a work in progress, I didn't try yet to generate the documentation of SQL. However, you find the good way to add a new client into the documentation, this should work.
I plan to merge this PR this week, and should be able to publish the package on PyPI with documentation on readthedocs.

**Comment by thenewwazoo** [comment]
No worries - I'm working on adopting this branch and discovered that doc generation didn't seem to be succeeding. If I find any other issues, is this the best place to report them?

**Comment by lmazuel** [comment]
@thenewwazoo Any SQL feedbacks are welcome! Here if the PR is still opened, on issue if released.
Thanks!

**Comment by lmazuel** [comment]
@thenewwazoo Built the readthedocs doc with no problem:
image

**Pull request merged**
