### PR TITLE
[Tables] Adding azurite support

### PR DESCRIPTION
**Pull request by seankane-msft**
#17417

### CODE REVIEW

**Comment by seankane-msft** [comment]
@v-xuto can you elaborate on how to best test these changes? Is there a way to spin up azurite in the azure devops? Are there any limitations to azurite or does it have the exact same functionality as the Tables service>

**Comment by seankane-msft** [comment]
@v-xuto I tested locally and I get an error on the sample code you provided:
```
Error: *Internal Azurite Error*: content-type value application/json;odata=nometadata is not supported by Azurite.
```

**Comment by v-xuto** [comment]
@seankane-msft - I tested it locally based on the code you modified, and the result was successful. I use this repo: https://github.com/Azure/Azurite, switch to the branch table, start azurite. Below are the values of `account_url` and `access_key` that I used. The values of these variables are provided in the [readme](https://github.com/Azure/Azurite/tree/table#default-storage-account). 
```
account_url = 'https://127.0.0.1:10002/devstoreaccount1'
access_key = 'Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=='
```

**Review by annatisch — APPROVED** [review]
Looks good - changelog update?

**Pull request merged**
