### PR TITLE
Revert "delete eventgrid"

### PR DESCRIPTION
**Pull request by msyyc**
related content that needs to be reverted:
Reverts Azure/azure-sdk-for-python#21509
Reverts Azure/azure-sdk-for-python#21510

### CODE REVIEW

**Review by BigCat20196 — APPROVED** [review]

**Comment by rakshith91** [comment]
@msyyc @BigCat20196 going forwards, please use 'BuildTargettingString' on the pipeline to skip packages - it's a little scary to get the packages deleted :)

https://github.com/Azure/azure-sdk-for-python/blob/main/doc/eng_sys_checks.md#targeting-a-specific-package-at-build-time

**Comment by msyyc** [comment]
@rakshith91 Sorry for the operation and we promise that it will never happen again.

**Pull request merged**
