### PR TITLE
Device Update for IoT Hub GA release updates

### PR DESCRIPTION
**Pull request by dpokluda**
# Description

Please add an informative description that covers that changes made by the pull request and link all relevant issues.

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by BigCat20196** [comment]
Hi @dpokluda, I updated conf test in your PR to add sanitizers to testproxy to replace secret values. Please re run live test and upload records to eliminate secret leakage. thanks!

secrets like this: https://github.com/Azure/azure-sdk-for-python/pull/25709/files#diff-b8929615194bc164797f7d3aa3e7c94a508f911ff9a952b7768141021695761dR4

https://github.com/Azure/azure-sdk-for-python/pull/25709/files#diff-b8929615194bc164797f7d3aa3e7c94a508f911ff9a952b7768141021695761dR197

**Comment by dpokluda** [comment]
I updated the PR with fresh new recorded sessions.

**Comment by BigCat20196** [comment]
> I updated the PR with fresh new recorded sessions.

The leakage problem still exists. 
https://github.com/Azure/azure-sdk-for-python/pull/25709/files#diff-b8929615194bc164797f7d3aa3e7c94a508f911ff9a952b7768141021695761dR197

**Comment by dpokluda** [comment]
I'm not an expert. What should I do to fix/resolve it?
________________________________

**Comment by BigCat20196** [comment]
> I'm not an expert. What should I do to fix/resolve it?

Hi @dpokluda, you could add sanitizers as [here](https://github.com/Azure/azure-sdk-for-python/pull/25709/files#diff-1f857e3abd5d112406a58c29d3d56b294ea1b4b7cc7542599bd2eedd10fe651dR41-R48). Maybe your local environment variable name is not like `DEVICEUPDATE_SUBSCRIPTION_ID`, so it does not take effect. You could also replace them.

**Comment by dpokluda** [comment]
Sorry, you are right. I think it should be fixed now.

**Review by johanste — APPROVED** [review]

**Comment by dpokluda** [comment]
Please, let me know if there is any other issue I should fix? Thanks.

**Pull request merged**
