### PR TITLE
update docs

### PR DESCRIPTION
**Pull request by xiangyan99**

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by scbedd** [comment]
@xiangyan99 So this is a real failure! However, it's _only a failure_ because we haven't released the newest version of `azure-core` yet. 

The `depends` test is what's failing. Your tests are actually passing. What is this `depends` test?

> install _just_ our package + it's `install_requires` and test to see if you can import * from the namespace. **NO** dev requirements for this,

This is to cover the couple instances where we _missed_ dev dependencies because people don't realize that the `dev_requirements` is concealing a necessary dependency.

Since we haven't uploaded the newest version of azure-core, this is actually failing because when we install. Given that this is a branch on the repo itself, let me push an override for this check. We should remember to delete the exception after we publish these packages.

**Comment by scbedd** [comment]
Also, I re-merged master. Checks were going insane because the PR was saying it had 110 files changed.  This should be fixed now.

**Pull request merged**
