### PR TITLE
Move cosmos errors.py -> exceptions.py

### LINKED ISSUE #7728: [Cosmos] Rename 'errors' module to 'exceptions'
This will make it consistent with Core and other track 2 SDKs.
We should add an alias and deprecation warning for `errors` to make the change non-breaking.

### PR DESCRIPTION
**Pull request by bryevdv**
issues: closes #7728

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by bryevdv** [comment]
@annatisch There are failing CRUD tests:

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=171687&view=logs&j=e4797745-1ad6-5989-d345-8ffe02e82111

Any ideas offhand? With this PR I might expect errors (broken imports etc) but not failures.

**Comment by annatisch** [comment]
Agreed - this shouldn't have changed.
@srinathnarayanan - can you please take a look?

**Comment by bryevdv** [comment]
I should also mention I ran all the tests locally against a real live instance before pushing the PR and things worked (or else I would not have pushed the PR!)

**Comment by annatisch** [comment]
Thanks @bryevdv - we wont block this PR on the live tests then.

**Comment by bryevdv** [comment]
Emulator test issues to be resolved in a separate PR.

**Pull request merged**
