### PR TITLE
Make __init__.py compatible with pkgutil-style namespace

### LINKED ISSUE #13187: azure-eventhub/azure/eventhub/extensions/__init__.py is incompatible with packaging namespaces
- **Package Name**: 
azure-eventhub

- **Package Version**: 
5.1.0

- **Operating System**:
Linux

- **Python Version**: 
3.8.2

**Describe the bug**
Existence of emptiness of the file https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/eventhub/azure-eventhub/azure/eventhub/extensions/__init__.py is incompatible with packaging namespaces. It causes problem using this package in Bazel, see https://github.com/dillon-giacoppo/rules_python_external/issues/56

**To Reproduce**
1. Go into temporary directory `cd /tmp`
2. Install azure_eventhub under dir1 `pip install --target=$(pwd)/dir1 azure_eventhub`
3. Install azure-eventhub-checkpointstoreblob under dir2 `pip install --target=$(pwd)/dir2 azure-eventhub-checkpointstoreblob`
4. Create virtual environment `virtualenv venv`
5. Activate virtual environment `source venv/bin/activate`
6. Create main.py 
```
cat > main.py
import sys
sys.path.extend(['/tmp/dir1', '/tmp/dir2'])
from azure.eventhub.extensions.checkpointstoreblob import BlobCheckpointStore
```
7. Execute main.py `python ./main.py`
8. Result is an error:
```
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from azure.eventhub.extensions.checkpointstoreblob import BlobCheckpointStore
ModuleNotFoundError: No module named 'azure.eventhub.extensions.checkpointstoreblob'
```

**Expected behavior**
main.py should execute without errors.

**Screenshots**
N/A

**Additional context**
The problem emerges because Bazel installs dependencies in separate directories. Current layout, incompatible with packaging namespaces makes it impossible to use in applications build by Bazel, see https://github.com/dillon-giacoppo/rules_python_external/issues/56

### PR DESCRIPTION
**Pull request by pjachowi**
Fixes #13187

### CODE REVIEW

**Comment by KieranBrantnerMagee** [comment]
Prior build had expired, (Sorry this sat a bit!) looks like we might have had a small lint/mypy issue, but that should be easy enough to triage;  rekicked build to see what's up and we can go from there.

**Review by lmazuel — DISMISSED** [review]
After a long discussion about namespace packages in the team, we agree on the fix :)

**Review by yunhaoling — APPROVED** [review]
@pjachowi , thanks for the PR, merging it now!

**Pull request merged**
