### PR TITLE
[ml] Fix optional types

### PR DESCRIPTION
**Pull request by diondrapeck**
# Description

Please add an informative description that covers that changes made by the pull request and link all relevant issues.

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [ ] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by nemanjarajic — APPROVED** [review]

**Comment by mccoyp** [comment]
@diondrapeck test failures in CI should be fixed by https://github.com/Azure/azure-sdk-for-python/pull/31244

**Comment by mccoyp** [comment]
> @diondrapeck test failures in CI should be fixed by #31244

#31244 has been merged, so a rebase with `main` should fix CI failures. As was mentioned in the linked PR, tests should still fail in nightly `latestdependency` checks despite CI being green, since the `marshmallow` dependency causing the failure can only be pinned from `dev_requirements.txt`.

I recommend disabling body matching by using [`set_bodiless_matcher()`](https://github.com/Azure/azure-sdk-for-python/blob/e70aa6d831402b78f6ff702380fe012fcfdb0353/tools/azure-sdk-tools/devtools_testutils/sanitizers.py#L64) in the relevant tests' bodies. The ML team should also create a tracking issue to remove the `marshmallow` upper bound from `dev_requirements.txt` -- and once Python 3.7 support is dropped by the SDK, body matching can be restored for these tests.

**Comment by annatisch** [comment]
@mccoyp - when will we be able to unpin `marshmellow`? We can keep it to unblock CI for this release if we need to re-record, but we should be testing against latest `marshmellow` because that's generally what customers will be using. Especially given that the majority of customers probably won't be using 3.7.

**Comment by mccoyp** [comment]
> @mccoyp - when will we be able to unpin `marshmellow`? We can keep it to unblock CI for this release if we need to re-record, but we should be testing against latest `marshmellow` because that's generally what customers will be using. Especially given that the majority of customers probably won't be using 3.7.

@annatisch @diondrapeck That's a good point -- we should probably remove the pin after ML tests are adjusted to disable body matching for the affected tests (that could be done in the same PR). `mindependency` would still cover tests for when `marshmallow` supported 3.7+ officially, and `latestdependency` would test what customers are likely using.

**Pull request closed without merging**
