### PR TITLE
fix failures in samples

### PR DESCRIPTION
**Pull request by xiangyan99**

### CODE REVIEW

**Comment by xiangyan99** [comment]
@YalinLi0312 seems like env var "AZURE_APPCONFIG_CONNECTION_STRING" was not set.

Do you know where we set the envs?

**Comment by YalinLi0312** [comment]
> @YalinLi0312 seems like env var "AZURE_APPCONFIG_CONNECTION_STRING" was not set.
> 
> Do you know where we set the envs?

It should be `APPCONFIGURATION_CONNECTION_STRING` https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/appconfiguration/test-resources.json#L194

**Review by YalinLi0312 — APPROVED** [review]

**Pull request merged**
