### PR TITLE
Support for replication and publishing

### PR DESCRIPTION
**Pull request by schaefi**
Added a ComputeManagementService class and methods to allow replication and publishing of VM images

### CODE REVIEW

**Comment by huguesv** [comment]
Thanks schaefi!

The code looks like it should work, and I trust that you've used it successfully (I can't really test this myself, but we'll take it despite the fact we can't test it).

Though I have a minor objection to naming this ComputeManagementService...

This is mainly because all of the existing compute operations are currently in ServiceManagementService.  Unlike the node.js sdk, we never ended up splitting into separate Compute, Network, Storage management service classes.  If we did, or intended to do so in the future, then ComputeManagementService would indeed be the correct class to include these operations.

So I would prefer to include the 3 new operations in the existing ServiceManagementService class.

If we have a ComputeManagementService class, users may think that this is where all the VM stuff is (especially if they are familiar with node.js or the newer ARM apis), where in fact it would just be these 3 image publishing operations that most users can't use since most are not image publishers.

**Comment by schaefi** [comment]
Thanks for looking into this

yes we actively use these patches in azurectl from here: https://github.com/SUSE/azurectl
This is our main tool to upload, register, publish and replicate the images we provide in Azure. The goal is to be not forced into powershell ;-) The design and scope of azurectl is for the complete Azure service not only limited to our use case. A long story short, we rely on that functionality and you can be assured we care if this does not work

At the moment we carry these patches in our version of the python-azure-sdk rpm package

**Comment by schaefi** [comment]
I'm basically ok with merging the new methods into the existing module. However  ServiceManagementService is already pretty big and the python coding style already complains about the size. Well you are steering this ship but don't you think it would be a good idea to have a separate name space for publishing/replication ?

I have no strong opinion about the name but glueing everything into service management creates a beast :)

Let me know what you think

Thanks

**Comment by huguesv** [comment]
Yes, it would be a good idea to have more subcategories so that the class isn't so large :)

However, given that this is a legacy API (we are now pushing users and putting our efforts towards the new ARM APIs), I have stopped worrying about these old design decisions and accepted to live with them.  Avoiding breaking changes for users that don't want to switch to ARM is a higher priority.

So far we've only split by Azure service.  Scheduler, ServiceBus, SqlDatabase, WebSite were added as their own classes because they are separate services from what was in ServiceManagement (storage+compute).

VM publishing support is part of compute which already has a class.  It sure is large, but it would feel more out of place to separate it out versus integrating it in the existing class.

Note that the method names will have to change as they get integrated into the existing class, because `replicate` needs to be qualified ie. `replicate_vm_image` might be a good name.

That's my thinking.  I'm trying to keep things as consistent as they can be.

**Comment by schaefi** [comment]
ok I'm going to rework the code taking into account what you have said

**Comment by schaefi** [comment]
Are you ok with it now ? Thanks

**Pull request merged**
