### PR TITLE
[storage] Fix for Files upload return type

### PR DESCRIPTION
**Pull request by annatisch**

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by annatisch** [comment]
FYI @xiangyan99 - thanks for the report!

**Comment by annatisch** [comment]
ping @rakshith91 @zezha-msft :)
CI UI update in the PR seems to be stuck - but according to the devops portal it passed.

**Comment by annatisch** [comment]
ping @zezha-msft @rakshith91  :)
Just a quick look over? Pretty please? I'd rather not merge without at least one signoff....

**Pull request merged**
