### PR TITLE
feat: create disk with ConfidentialVM_NonPersistedTPM securityType

### PR DESCRIPTION
**Pull request by fnerdman**
# Description

Adds option to create managed disks with ConfidentialVM_NonPersistedTPM securityType. These are required to boot ConfidentialVMs with `--os-disk-security-encryption-type` set to `NonPersistedTPM`.

This is more of an issue rather than a PR. The patch fixes deployment on my side, but I won't add changelog and test cases. So this could be used as a precursor to the final PR.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by annatisch** [comment]
@msyyc @ChenxiJiang333 - is there a swagger update needed here?
Or perhaps it's already been updated and we need a code regen?

**Comment by msyyc** [comment]
@fnerdman It is already there https://github.com/Azure/azure-sdk-for-python/blob/275dc102d852e9f3a620163e476318ae475d0bce/sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2024_03_02/models/_compute_management_client_enums.py#L129-L131 and could you please try latest version of azure-mgmt-compute?

**Comment by annatisch** [comment]
Sounds like this has already been resolved - @fnerdman please let us know if you have any further difficulties with this.

**Comment by Hyodar** [comment]
Stumbled across https://github.com/Azure/azure-cli/issues/29207 and adding the member to the `v2023_04_02`'s enums file similarly to this PR solves it. Running `azure-mgmt-compute@33.0.0`. Maybe it's an issue in the CLI side?

**Comment by fnerdman** [comment]
@Hyodar I meet you in person for the first time and few hours later stumble upon this very valuable comment of yours - what a coincidence. TY!

**Comment by Hyodar** [comment]
@fnerdman Haha, my pleasure! It was geat meeting in person :)

**Comment by msyyc** [comment]
> @msyyc @annatisch The underlying issue is still persistent and not resolved. az-cli still uses v2023_04_02 which does not have this option listed.

Since we can make sure SDK has the target enum, it is not SDK issue. Maybe it is because CLI doesn't upgrade SDK to latest version and you can seek help from CLI team.

**Pull request closed without merging**
