### PR TITLE
Fix Get-AllPackageInfoFromRepo for Linux Machine runs

### PR DESCRIPTION
**Pull request by chidozieononiwu**
For some reason `eng\scripts\get_package_properties.py` result includes a `u` for the version when run on Linux [Example](https://dev.azure.com/azure-sdk/playground/_build/results?buildId=772101&view=logs&j=a4f1cc8a-0ccb-5e90-36f4-f06f41d0ce59&t=648c9d12-90a9-5fb6-d4d2-15f97230c638&l=12)
This fixes this case so we have the same result as from windows machines.

### CODE REVIEW

**Comment by benbp** [comment]
I think it would be better to figure out why the python function is returning this unicode prefix as the string result and fix it there, rather than patching in a trim() at this level.

**Comment by weshaggard** [comment]
I agree with @benbp lets see if we can understand where that is coming from.

**Comment by chidozieononiwu** [comment]
> I agree with @benbp lets see if we can understand where that is coming from.

It came because I was printing the entire object rather than its individual members.

**Review by weshaggard — APPROVED** [review]

**Pull request merged**
