### PR TITLE
Fixes warning about session reuse.

### PR DESCRIPTION
**Pull request by zooba**

### CODE REVIEW

**Comment by lmazuel** [comment]
@matthchr a little of context here. Since msrest 0.4.28, there is an improvement on session handling:
https://github.com/Azure/msrest-for-python#2018-04-18-version-0428

If your `signed_session` has an optional `session` parameter, `msrest` injects its permanent session to be patched, instead of relying on you to create a new one. In practical term, I can re-use the same session instead of creating a new one for each call (which is better).

Should be safe, but please do not hesitate to test it.

**Comment by zooba** [comment]
FWIW, I did test it before sending the PR :)

**Comment by matthchr** [comment]
This looks good to me.
@xingwu1, it sounds like @lmazuel is suggesting that we release a patch version of the SDK with this fix. Any objections to that?

**Comment by zooba** [comment]
It'll certainly make my demo next week easier if I'm using a public release :)

Though there's also the semi-related https://github.com/Azure/msrest-for-python/issues/126 that I'd like fixed too. Not sure whether that will require any coordination with the `azure-batch` release.

**Comment by lmazuel** [comment]
@zooba not coordination needed, and PR done for msrest already:
https://github.com/Azure/msrest-for-python/pull/127

**Comment by xingwu1** [comment]
@lmazuel The fix LGTM. However, it is possible to publish the new binary without change the version?

**Comment by lmazuel** [comment]
@xingwu1 No, that's against PyPI policy. And anyway, this is a change in code, and then requires a bug fix version update.

**Pull request merged**
