### PR TITLE
Add Python SDK for Subscription RP.

### PR DESCRIPTION
**Pull request by wilcobmsft**
Initial SDK with support for creating/listing subscription definitions.

### CODE REVIEW

**Comment by lmazuel** [comment]
Hi @wilcobmsft !
Great PR thinks! Could you confirm it's the extraction of the subscription client that was packaged with "azure-mgmt-resource" before?
This will have massive impact on CLI, and I need to rev a major version of "azure-mgmt-resource" at the same time + moving the subscription test, etc.

**Comment by wilcobmsft** [comment]
@lmazuel Not quite. We introduced a Subscription RP, which contains a new "subscription definition" resource which is subtly different from the top-level /subscription object in ARM. This PR is about exposing a "Subscription*Definition*Client". As such, there should be no need to rev azure-mgmt-resource. Let me know if you have further questions.

**Comment by lmazuel** [comment]
@wilcobmsft hum ok, I was mislead by the title of this PR https://github.com/Azure/azure-rest-api-specs/pull/2062 "Moving Microsoft.Subscription into its own SDK"
I need to think if the naming is then ok, since it's not subscription but subscriptionDefinition. Might be confusing for people.

I was thinking to externalize SubscriptionClient into it's own package "azure-mgmt-subscription". Since these two clients have the same constraint (they don't take a SUBSCRIPTION_ID as a client parameter).
What do you think if we do that? Having subscription + definitions into one external package?

**Comment by wilcobmsft** [comment]
@lmazuel Moving SubscriptionClient into azure-mgmt-subscription sounds reasonable. Seems like something that could be done separately from this PR, at any point in time.

**Comment by lmazuel** [comment]
What is your deadline/schedule/"plan for CLI" for this? We can talk by email if you prefer on this.

**Comment by wilcobmsft** [comment]
@lmazuel We're starting a private preview on Friday, so we're hoping to have CLI available sometime this month.

**Comment by lmazuel** [comment]
Released part of another PR

**Pull request closed without merging**
