### PR TITLE
Updated exception hierarchy

### PR DESCRIPTION
**Pull request by johanste**
Simplified exception hierarchy.

Basically, three cases:

- Failed to send request
- Sent request, but failed to understand response
- Understood response and I have the status code, and the status code is something I don't like, or I failed to deserialize the body (decode error)

Additional changes are needed to make sure that we are correctly constructing the exception messages (e.g. I know that decode error needs to get the request/response passed in). But opening this PR anyways to get feedback on the simplified exception hierarchy.

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by sima-zhu** [comment]
I like the idea of the simplified the exception.
I have no issue understanding ServiceRequestException. (This one is ac)

For ServiceResponseException and HttpResponseException are really vague to me. 
Based on your description, can we do something like ServerErrorException (=ServiceResponseException) and ClientErrorException (=HttpResponseException). Refer to Java [API](https://docs.oracle.com/javaee/7/api/javax/ws/rs/package-tree.html)

Since we make the exception name without mention HTTP, can we rename the base to AzureHttpException, so we know the hierarchy under the base will be related to http. For other protocol, we can have other base. I don't think different protocols needs to originate to the same base, as client will not use more than one protocol for one call. Or we can move the exception under http package. And have respective exception folder under each protocol package.

**Comment by johanste** [comment]
One additional data point; we have generally not prefixed HTTP specific things with HTTP in azure-core. The base assumption is that it is HTTP. And that other protocols would have to use a prefix if they needed to distinguish themselves.

**Comment by annatisch** [comment]
Thanks @sima-zhu!

Just to clarify - a ServerErrorException has a status code (5xx) and therefore would be an HttpRequestError. Whereas a ServerResponseError is a connection error that occurs after the request reached the service (e.g. a read timeout error).

I can't speak for Java, but for Python I generally disagree that we would not want to share a single parent exception type between HTTP and non-HTTP services. Without a common base class, a user is forced to be aware what protocol is being used for any given operation in order to catch an error.

**Comment by johanste** [comment]
@annatisch, what would be the set of common exception types between, say, AMQP and HTTP/REST based services be? And how would you document them? The protocol *does* leak out today as we have protocol specific properties in the exceptions.

**Comment by annatisch** [comment]
@johanste - good point... 
The errors currently here are very http-centric, and I think that's fine. But having a common AzureError at the top that we can reuse for AMQP-specific types is also useful.
The parent AzureError has plenty of common attributes that could be shared between the next tier of protocol specific types:
```
self.inner_exception = kwargs.get('error')
        self.response = kwargs.get('response')
        self.exc_type, self.exc_value, self.exc_traceback = sys.exc_info()
        self.exc_type = self.exc_type.__name__ if self.exc_type else type(self.inner_exception)
        self.exc_msg = "{}, {}: {}".format(message, self.exc_type, self.exc_value)  # type: ignore
        self.message = str(message)
```
So a developer, depending on their use case, could catch the common AzureError type and still get:
- the message
- an inner exception if one was thrown
- an error response object from the service if one is available
- stack trace information.

**Pull request merged**
