### PR TITLE
Fix regression of PipelineRequest in retry

### PR DESCRIPTION
**Pull request by xiangyan99**

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by bryevdv** [comment]
LGTM to me. For my own edification, what other sorts of responses can come through?

**Comment by kristapratico** [comment]
Also LGTM, good catch. 

@bryevdv This is due to the increment method accepting either the pipeline response or pipeline request under the same response param.

In the send method...
`retry_active = self.increment(retry_settings, response=response)`
and
`retry_active = self.increment(retry_settings, response=request, error=err)`

**Comment by xiangyan99** [comment]
> LGTM to me. For my own edification, what other sorts of responses can come through (or is this just a guard against `None`?)

In retry policy, we also have 

retry_active = self.increment(retry_settings, response=request, error=err)

Which passes an request into the method

**Pull request merged**
