### PR TITLE
Fix #513 - Add renew lock feature

### LINKED ISSUE #513: Explain in docs how to wait for new messages in service bus queue
I'd like to know how I can react to new messages appearing in a service bus queue using the python sdk. As far as I know, I can write `msg = bus_service.receive_queue_message('taskqueue')`, but does that block/poll/something or does it always return immediately? This should be clarified in the docs.

Ideally, I'd like to be able to pass a timeout and wait for that time span to see if a new message appears when there aren't any available immediately. Supporting that feature asynchronously would be even better! Something like:

```python
while True:
    msg = await bus_service.receive_queue_message('taskqueue', wait=500)  # blocks/defers execution for 500 seconds
    if msg:
        process(msg)
```

### PR DESCRIPTION
**Pull request by lmazuel**
Fix #513

### CODE REVIEW

**Comment by oak-tree** [comment]
Hey @lmazuel 
Question: 
We are using this feature of renew_lock. But this does not update the `broker_properties['LockedUntilUtc']`. So we can we know when is the lock is going to be expired?

Thanks!

**Comment by lmazuel** [comment]
Hi @oak-tree 
Unfortunately, if you look at the RestAPI, this properties is not returned when we renew :(
https://docs.microsoft.com/en-us/rest/api/servicebus/renew-lock-for-a-message

So I'm unsure how I'm supposed to get the updated value :/

**Comment by lmazuel** [comment]
@oak-tree I got an answer from the SB team. New lock has to be computed manually. When you use renew, you should now wait the "entity’s default lock duration" (quote from SB answer).
I can probably provide a wrapper or something to do that. I'm not a huge fan of updating LockedUntilUtc, since it's an actual value from the initial message. But I can probably provide a "when_expire" or something method that returns LockedUntilUtc or the computed time. Please open an explicit issue asking for this if you feel this is interesting.

**Comment by oak-tree** [comment]
@lmazuel Thanks for replying! How can I get the `entity's default lock duration`? If I understand correctly the `api call` is restarting the `lock clock`?

and yes, this can be help at the future. I'll open an issue for that

**Comment by lmazuel** [comment]
I'm not sure yet how to get the entity's default lock duration :/

**Comment by oak-tree** [comment]
@lmazuel getting the `default lock duration` can be done by 
`get_subscription(topicname,subscriptionname).lock_duration`

**Pull request merged**
