### PR TITLE
[Core] Add `@runtime_checkable` to TokenCredential protocol definitions

### PR DESCRIPTION
**Pull request by mccoyp**
# Description

See https://github.com/Azure/azure-sdk-for-python/issues/25175. With this PR, doing an `isinstance` check with an `azure-identity` credential and a `TokenCredential` protocol returns True -- that check errors today since these protocols aren't runtime checkable.

`isinstance` and `issubclass` checks aren't available without `@runtime_checkable`, but [explicitly declaring the `TokenCredential` implementation](https://peps.python.org/pep-0544/#explicitly-declaring-implementation) (as shown below) could possibly satisfy static type checkers.
```python
# from https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/azure/identity/_internal/get_token_mixin.py
...
from azure.core.credentials import TokenCredential
...
class GetTokenMixin(ABC, TokenCredential):
```
```python
# from https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/identity/azure-identity/azure/identity/aio/_internal/get_token_mixin.py
...
from azure.core.credentials_async import AsyncTokenCredential
...
class GetTokenMixin(abc.ABC, AsyncTokenCredential):
```

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by xiangyan99 — CHANGES_REQUESTED** [review]
Let's split them into two separate PRs: core-only and non-core.

**Review by xiangyan99 — APPROVED** [review]
Do you want to add it into changelog?

**Comment by mccoyp** [comment]
@xiangyan99 good point, it probably would be worth adding. I am just now noticing, though, that this isn't supported in Python 3.7. This'll need some reworking, unfortunately 🤔

**Review by lmazuel — APPROVED** [review]

**Review by lmazuel — COMMENTED** [review]
Change my approve to comment, as we need 3.6 support. Maybe Krista has an idea.

**Comment by xiangyan99** [comment]
> Change my approve to comment, as we need 3.6 support. Maybe Krista has an idea.

I guess what you wanted to say is we wanted 3.7 support?

**Comment by lmazuel** [comment]
@mccoyp we're dropping 

> > Change my approve to comment, as we need 3.6 support. Maybe Krista has an idea.
> 
> I guess what you wanted to say is we wanted 3.7 support?

yeah :p

**Comment by mccoyp** [comment]
Yeah, this won't work because 3.7 doesn't support it 😔 And it doesn't solve the motivating issue (see [this comment](https://github.com/Azure/azure-sdk-for-python/issues/25175#issuecomment-1182894409)), so we'll need a different approach completely.

I don't think this change (rather, a 3.7-compatible version) is a bad idea, because being able to do an `isinstance` check of a protocol implementation sounds desirable. But I can also close this PR for now -- @lmazuel what do you think?

**Comment by lmazuel** [comment]
@mccoyp , ok let's try to reproduce already, it should be possible. Once we understand that, we'll talk about solution.

**Review by lmazuel — APPROVED** [review]

**Comment by mccoyp** [comment]
Identity CI failure is unrelated, and a fix is proposed here: https://github.com/Azure/azure-sdk-for-python/pull/25787

Overriding check enforcer to merge since everything else is a-okay 🙂

**Pull request merged**
