### PR TITLE
[Automation] Add GitHub Action workflow to test data sdk samples with the latest released version of package `azure-appconfiguration `.

### PR DESCRIPTION
**Pull request by zedy-wj**
**Description:**
We are promoting the automated testing process for data sdk services samples. Currently, we need to manually test the samples related to the monthly released packages. We hope to optimize this process through `GitHub Action workflow` to reduce repeated operations and a lot of time costs.

**Related Task:**
Azure Data SDK Monthly Release Manual Test ➡️ Automation (Doing)

**Related package:**
This PR uses the `azure-appconfiguration` package as an example to show how we can automate testing samples in a workflow.

**Design:**
1. `scripts/run-samples.sh`: This file is used to run samples and record the number of failures, and finally manage the exit status of the pipeline. It can be used by all `yml` files (here refers to the running samples we are developing), so we put it in the `scripts` folder.

2. `.github/workflows/<packages>-samples.yml`: For this PR, it is `appconfig-samples.yml`. We plan to expand the scope to more packages in the future. As long as there are samples under the package and it is still under maintenance, we will add corresponding `yml` to folder `.github/workflows` to automatically run samples under the package.

### CODE REVIEW

**Comment by ArthurMa1978** [comment]
@weshaggard, could you please review this? The team is planning to enable test automation for samples.

**Comment by weshaggard** [comment]
@ArthurMa1978 @zedy-wj is there any reason this is a github action? In general we have been sticking int Azure Devops, especially for anything that requires secrets and run on a PR.

**Comment by ArthurMa1978** [comment]
> @ArthurMa1978 @zedy-wj is there any reason this is a github action? In general we have been sticking int Azure Devops, especially for anything that requires secrets and run on a PR.
> 
> Also we have generally ran sample validation in the DevOps release pipeline directly. I don't recall if we do that in python but we do in other languages.

We have been manually testing all samples for years, and now we plan to move to automation. I got a message that some of our engineering systems are transitioning to GitHub Actions, so the team has built this as a GitHub Action. Please correct me if I’m wrong, and we can consider moving to ADO.

This process involves running live tests using the sample code to ensure the samples are runnable. It goes beyond just validating the syntax correctness, unlike the existing sample validation.

**Comment by v-xuto** [comment]
Close this PR. Because we will move to Azure DevOps.

**Pull request closed without merging**
