### PR TITLE
[formrecognizer] set up live canary/prod pipelines

### PR DESCRIPTION
**Pull request by kristapratico**
After talking to Daniel, the region will just be a variable set in the devops pipeline.

### CODE REVIEW

**Comment by kristapratico** [comment]
@danieljurek

**Comment by scbedd** [comment]
@kristapratico this looks great! The only piece that I THINK needs to change is that we need to refer to a different subscriptionId. So probably the the canary one needs to use a different subscription variable. Waiting for @danieljurek to confirm on that.

**Comment by kristapratico** [comment]
@scbedd Awhile back I submitted to whitelist both playground and test resources subs for canary access for form recognizer. Is this what you mean?

**Comment by scbedd** [comment]
@kristapratico Aha. Yeah. If that subscription is g2g on canary because of that, 👍 

then LGTM!

**Pull request merged**
