### PR TITLE
Update SDK Tools Consumption

### PR DESCRIPTION
**Pull request by chidozieononiwu**
Update method of consuming SDK tools to use resources and templates.

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by scbedd** [comment]
I believe this is the order of ops for the builds:

client -> archtype sdk-nightly -> test-nightly
archtype-sdk-tests -> build-test
archtype-sdk-client -> build-test

So basically what I'm saying is that `resources` definition is necessary at `archtype-sdk-client` and `sdk-tests` ymls.

**Comment by chidozieononiwu** [comment]
The Issue with the resources is you can't add them at a template level. Since `archtype-sdk-tests` and `archtype-sdk-client` are both templates I had to go all the way back to the yml that call them. The CI fails due to error in pylint step. Queuing `python - cognitiveservices - ci` again.

**Comment by scbedd** [comment]
@chidozieononiwu the eventhub failure is known and they are working on it. I don't believe it's related to your changes.

**Pull request merged**
