### PR TITLE
Repo restructure 1 - AppInsights, ResourceGraph, LogAnalytics, IotHubProvisioning, EventHub

### PR DESCRIPTION
**Pull request by scbedd**
Details:

`git mv azure-mgmt-eventgrid/ sdk/eventgrid/azure-mgmt-eventgrid`
`git mv azure-mgmt-eventhub/ sdk/eventhub/azure-mgmt-eventhub`
`git mv azure-mgmt-iothubprovisioningservices/ sdk/iothub/azure-mgmt-iothubprovisioningservices`
`git mv azure-loganalytics/ sdk/operationalinsights/azure-loganalytics`
`git mv azure-mgmt-resourcegraph/ sdk/resourcegraph/azure-mgmt-resourcegraph`
`git mv azure-applicationinsights/ sdk/applicationinsights/azure-applicationinsights`

Updated docsettings, dev_requirements relative reference to azure-sdk-tools.

Plan is to move `azure-sdk-tools` at the _very end_. This means we will be to update the relative dev_requirements locations in one shot.

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by scbedd** [comment]
@Azure/azure-sdk-eng

**Comment by weshaggard** [comment]
>git mv azure-loganalytics/ sdk/loganalytics/azure-loganalytics

The specs repo (https://github.com/Azure/azure-rest-api-specs/blob/f4b675a240503e6547239e1ce2c4eed90c61984c/specification/operationalinsights/data-plane/readme.md) and the JS repo (https://github.com/Azure/azure-sdk-for-js/blob/763eb48fa5dede2e8bd68d4ee2700482aeb7fae4/sdk/operationalinsights/loganalytics/package.json) have operationalinsights as the service name so lets use that here.

**Comment by weshaggard** [comment]
In general lets try to be consistent with the specs repo as much as possible.

**Comment by scbedd** [comment]
> In general lets try to be consistent with the specs repo as much as possible.

Totally agree. Salty I missed it.

**Pull request merged**
