### PR TITLE
[Tables] Migrate to new test proxy

### PR DESCRIPTION
**Pull request by YalinLi0312**
For issue: https://github.com/Azure/azure-sdk-for-python/issues/20114

### CODE REVIEW

**Comment by scbedd** [comment]
@YalinLi0312 tomorrow I will add the necessary changes to spin up the test-proxy!

**Comment by mccoyp** [comment]
Running a new pipeline that will (or should) have test proxy logs here: https://dev.azure.com/azure-sdk/public/_build/results?buildId=1221035&view=results

**Review by mccoyp — APPROVED** [review]

**Pull request merged**
