### PR TITLE
Support AZURE_RESOURCEGROUP_NAME

### PR DESCRIPTION
**Pull request by lmazuel**

### CODE REVIEW

**Comment by danieljurek** [comment]
Resource Group Scoping Tests: 
* KV - https://dev.azure.com/azure-sdk/internal/_build/results?buildId=214310&view=results
* Storage - https://dev.azure.com/azure-sdk/internal/_build/results?buildId=215120&view=results

**Comment by lmazuel** [comment]
Merging, since CI pass, and I don't think the live issues we see are related to the content of this PR (if that's the case I'll be happy to debug it ;))

**Pull request merged**
