### PR TITLE
Nspkg to sdk folder

### PR DESCRIPTION
**Pull request by lmazuel**

### CODE REVIEW

**Comment by lmazuel** [comment]
@scbedd I think you postpone the full problem actually, every packages can be in two spots, and every of them should be installable from the "sdk" folder. Being the installation could be:
pip install -e mypackage
or
pip install -e sdk/myservice/mypackage

The approach I would do would then not consider "azure-common" or anything as specific packages, but have a global strategy.
What I have done here:
https://github.com/Azure/azure-sdk-for-python/blob/27bed2b6296f95e219cef89f46f1238ce3c6cf48/azure-sdk-tools/packaging_tools/drop_tools.py#L55-L58
is using a regexp to keep a tuple (base_path, package_name). This tuple could be:
("." , mypackage)
or
("./sdk/myservice/, my package)

and then the installation code is simply:
pip install -e base_path/mypackage

**Comment by badeball** [comment]
Hi, @lmazuel

I just tried to build the sdk (using `./setup.py`), but it fails with `ValueError: list.remove(x): x not in list` on https://github.com/Azure/azure-sdk-for-python/blob/f24fb53e547645809cf1f36c9688ae464cd232ec/setup.py#L32, presumably due to 25a80a9. Can you confirm that this is indeed an / the issue?

**Comment by lmazuel** [comment]
Hi @badeball 
That's a little more subtle, declared here:
https://github.com/Azure/azure-sdk-for-python/issues/5291

Thanks

**Comment by scbedd** [comment]
@badeball PR #5449 this should fix the problem.

**Comment by badeball** [comment]
Ah, I tried to look over most recent issues, but apparently didn't see that one. Thanks for looking into this!

**Pull request merged**
