### PR TITLE
Add aliases for redis list operations for backwards compatibility

### PR DESCRIPTION
**Pull request by TimLovellSmith**
That will compensate for aligning Redis operations in the open API specs with the standard operation name conventions. 

To unblock https://github.com/Azure/azure-rest-api-specs/pull/14023

(Looks like it was pretty well validated by CI.)

### CODE REVIEW

**Review by iscai-msft — APPROVED** [review]

**Review by lmazuel — APPROVED** [review]

**Comment by msyyc** [comment]
I have approved the breaking change of https://github.com/Azure/azure-rest-api-specs/pull/14023#pullrequestreview-652995840. So we needn't the patch anymore.

**Comment by TimLovellSmith** [comment]
@msycc So we don't need the Python SDK to keep backcompat across the versions in this particular case?

**Comment by msyyc** [comment]
@iscai-msft @lmazuel I think both are ok. 
(1)But now that our CHANGELOG has indicated that there is breaking change. So it is better to let it happen. Otherwise customers will be confused and doubt the precision of our CHANGELOG.
(2)The patch may increase our work load of maintenance in the future. We should avoid manual change for mgmt SDK code ASAP.

**Comment by TimLovellSmith** [comment]
@msycc Can we manually edit the CHANGELOG also in this PR? Or its too late because a release is already generated?

**Comment by msyyc** [comment]
@TimLovellSmith CHANGELOG is generated by tools compared with last published package. It is better not to edit it manually since it may mislead customers.

**Pull request closed without merging**
