### PR TITLE
33604: Update docstring for sphinx for azure-maps-search

### PR DESCRIPTION
**Pull request by Lakicar95**
# Description

Fix Sphinx errors related to formatting, styling and adopting anonymous links in docstrings. After introducing these changes, we are able to set strict_sphinx to true in pyproject.tom - which enforces strict checking during the Sphinx documentation build process.

Fixes: https://github.com/Azure/azure-sdk-for-python/issues/33604

### [Testing Guidelines]
`../azure-maps-search>pip install "tox<5"

../azure-maps-search>tox run -e strict-sphinx -c ../../../eng/tox/tox.ini --root .`

### CODE REVIEW

**Comment by kristapratico** [comment]
@Lakicar95 is this PR ready to review?

**Comment by Lakicar95** [comment]
> @Lakicar95 is this PR ready to review?

@kristapratico I have some changes within _generated dir, and regarding generating code from autorest, I couldn't overcome this issue:

When I try this command:

`(venv) PS C:\Users\LazarPejic\PycharmProjects\azure-sdk-for-python\sdk\maps\azure-maps-search\swagger> autorest .\README.md --input-file=https://github.com/Azure/azure-rest-api-specs/blob/main/specification/maps/data-plane/Search/preview/1.0/search.json  `

I'm getting this error:

```
fatal   | Error: AzureKey security scheme should be of in 'header' but was 'query'
fatal   | Process() cancelled due to failure
error   |   Error: Plugin modelerfour reported failure.
error   | Autorest completed with an error. If you think the error message is unclear, or is a bug, please declare an issues at https://github.com/Azure/autorest/issues with the error message you are seeing.
(venv) PS C:\Users\LazarPejic\PycharmProjects\azure-sdk-for-python\sdk\maps\azure-maps-search\swagger>
```

Can you maybe help me to understand the steps to generate code from autorest in order to be able to verify whats needed and to resolve other issues as well..?

**Comment by Lakicar95** [comment]
@kristapratico If there are errors in _generated folder, is it ok to just fix those changes in this repo, or do we have to modify autorest part to make sure our changes will not be overwritten?

**Comment by kristapratico** [comment]
@Lakicar95 the autorest error is describing a problem with the spec the code is being generated from. The maps service team will need to make adjustments to correct it before the next time they need to regenerate (including some of the docs changes you're making here). I don't think we should block on this PR because it's important that we enable strict_sphinx so any future changes will comply. I'm going to go ahead and approve / merge this PR. Thanks for all your contributions!

**Review by kristapratico — APPROVED** [review]

**Comment by Lakicar95** [comment]
@kristapratico Thanks, so just one question, we can and should make changes to files within _generated directory (even though those changes might be overridden in the future by the autorest tool)?

**Comment by kristapratico** [comment]
@Lakicar95 no, I would not say this is a common case. We really shouldn't make any changes to generated files because they will be overridden upon the next generation. Instead we should make a change to the API spec so the correct code is generated, or, if the bug arises from autorest itself, fix it there. In this case, I'm not certain what the correct fix to the API spec is without input from the maps service team. Upon their next generation they will need to fix both the autorest error and the way they were specifying links. By merging this PR and enabling strict_sphinx, we will at least block on any future PRs until these are fixed. Since this library hasn't seen a new release in awhile, nor did your PR touch any actual code, I favored leniency in merging the change. Hope that helps!

**Pull request merged**
