### PR TITLE
Storage Mgmt 2016-05-01

### PR DESCRIPTION
**Pull request by lmazuel**
New API Version

### CODE REVIEW

**Comment by derekbekoe** [comment]
FYI @tjprescott @johanste

**Comment by lmazuel** [comment]
@derekbekoe @tjprescott @johanste blocked until https://github.com/Azure/autorest/issues/1647 solved

**Comment by lmazuel** [comment]
Re-add Client suffix and re-record tests to check everything else is compatible

**Comment by tjprescott** [comment]
Are the breaking changes just the case changes for the enums and the name changes for the classes?

**Comment by lmazuel** [comment]
@tjprescott It seems, since renaming the Client was enough to get everything ok (current broken state on Travis is because I didn't re-record Compute tests using Storage). But I don't think I will release a new Client manually rewritten, I will wait for the Autorest fix.

**Comment by lmazuel** [comment]
Replaced by https://github.com/Azure/azure-sdk-for-python/pull/961

**Pull request closed without merging**
