### PR TITLE
Use common OIDC token env vars for live tests.

### PR DESCRIPTION
**Pull request by benbp**
Support oidc az cli login in post deploy scripts for multi-cloud. Requires https://github.com/Azure/azure-sdk-tools/pull/9099

### CODE REVIEW

**Comment by benbp** [comment]
@pvaneck FYI I noticed that the `ProvisionLiveResources` parameter does not seem to be propagating correctly during weekly tests

**Comment by benbp** [comment]
Tests seem to be failing on the AKS quota issues we are seeing for the new TME tenant. I will hold off for the moment.

**Review by weshaggard — APPROVED** [review]

**Comment by benbp** [comment]
Closing as https://github.com/Azure/azure-sdk-for-python/pull/37815 fixes

**Pull request closed without merging**
