### PR TITLE
[HDInsight] Adding support for HDInsight

### PR DESCRIPTION
**Pull request by wawon-msft**
This is the initial commit from HDInsight.

This PR contains the following changes:
- Generation from the latest Swagger spec (with API version 2015-03-01-preview) into /azure-mgmt-hdinsight
- Addition of a CRUD test (and the recording) into /azure-mgmt-hdinsight/test (let me know if more tests are preferred).
- Update to /.github/CODEOWNERS with myself.

Feel free to let me know if any additional changes are required.

### CODE REVIEW

**Comment by wawon-msft** [comment]
Hi @lmazuel, thanks for the review and the initiative to try this out with the new API version. There are still some details I would like to hammer out on our end before we make this API version public. However, when this API version becomes available, the tests will be compatible with either API version.
I was hoping these two processes can progress in parallel (especially because the actual changes are minimal), but if you'd prefer to wait until the API version is released, I can abandon this PR and make changes to the auto PR when ready.

**Comment by lmazuel** [comment]
Hi @wawon-msft 
Make sense, we can do that and release this PR.
The CI fails because of the packaging, but I have my own system to build packaging. I will push it to your PR.
Thanks!

**Comment by lmazuel** [comment]
@wawon-msft Also, you generated with and old version of Autorest (autorest has a cache, and sometimes it creates trouble....). I re-generated with latest version.

**Comment by lmazuel** [comment]
@wawon-msft I approve the PR, since I pushed into your branch, please confirm you're ok with the content before I release. Thanks!

**Comment by wawon-msft** [comment]
@lmazuel The changes look great, thanks!
Will https://docs.microsoft.com/en-us/python/api/overview/azure/ be updated after this change, or should I follow up afterwards on adding HDInsight details to that page?

**Comment by lmazuel** [comment]
@wawon-msft I send you an email for the doc.
Thanks!

**Pull request merged**
