### PR TITLE
Live test is failing due to missing python 3.8 yml

### PR DESCRIPTION
**Pull request by praveenkuttappan**
Updated to use Python 3.8 image instead of compiled python

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by annatisch** [comment]
Looks like the MaxOS tests have either hung or the VM has stopped reporting.
Are the VM drop-outs still happening?
@YijunXieMS - is this possibly related to the tests themselves?

**Comment by YijunXieMS** [comment]
@annatisch The next test method is test_receive_owner_level_async before it hung. I don't see anything special with this test method.

**Comment by praveenkuttappan** [comment]
@scbedd : This PR has changes to add python 3.8 in archtype-sdk-tests.yml also. 
https://github.com/Azure/azure-sdk-for-python/pull/8739/files#diff-2c092bb34841b77838298f0d852da820R27

**Pull request merged**
