### PR TITLE
add reprs to common user-facing classes

### PR DESCRIPTION
**Pull request by bryevdv**
Went with non-evalable scheme:

* `CosmosClient` may have long/complicated args, including credentials
* Other classes are not intended to be instantiated directly by users

Yields e.g. 
```
In [10]: c
Out[10]: <CosmosClient [https://brvandev-cosmos.documents.azure.com:443/]>

In [11]: c.get_database_client("foo")
Out[11]: <DatabaseProxy [dbs/foo]>

In [12]: c.get_database_client("foo").get_container_client("bar")
Out[12]: <ContainerProxy [dbs/foo/colls/bar]>

In [13]: PartitionKey("stuff")
Out[13]: <PartitionKey [stuff]>
```

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by bryevdv** [comment]
Linter is failing with 

> azure/cosmos/cosmos_client.py:197: [C4729(client-method-name-no-double-underscore), CosmosClient.__repr__] Client method name should not use a double underscore prefix. See details: https://azure.github.io/azure-sdk/python_introduction.html#public-vs-private

@johanste is it really the intention  of the guidance to prevent all under methods on clients?

**Comment by johanste** [comment]
@bryevdv, correct. The rule is intended for name mangling only.

**Comment by bryevdv** [comment]
> @bryevdv, correct. The rule is intended for name mangling only.

@johanste OK I'll just put in a pylint disable comment for now. Who is the best person to ping about updating the custom linter rules?

**Pull request merged**
