### PR TITLE
Repo Restructure - ServiceBus

### PR DESCRIPTION
**Pull request by scbedd**
Properly using `git mv` this time.

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by lmazuel** [comment]
@scbedd You need to change azure-eventhub as well

**Comment by scbedd** [comment]
> @scbedd You need to change azure-eventhub as well

Yep. Installation failure due to the interdependence. *facepalm

**Pull request closed without merging**
