### PR TITLE
revert the filter on python < 3.8 in service-bus dev_requirements.txt

### PR DESCRIPTION
**Pull request by scbedd**
`typed-ast` has released an update. This should work now.

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by scbedd** [comment]
@annatisch I am re-enabling the pylint install on the dev requirements for python 3.8. The break in `typed-ast` has been resolved.

**Comment by scbedd** [comment]
TIL Pressing `close and comment` will leave the comment and close the PR.

**Pull request merged**
