### PR TITLE
Storage File Datalake test (test_list_paths_with_max_per_page) improvement

### PR DESCRIPTION
**Pull request by v-xuto**
Fixes https://github.com/Azure/azure-sdk-for-python/issues/16231

@lmazuel , @kyle-patterson , @kasobol-msft , @annatisch，@tasherif-msft  for notification.

### CODE REVIEW

**Comment by v-xuto** [comment]
@lmazuel , @kyle-patterson , @kasobol-msft , @annatisch, @tasherif-msft  Could you please help review this PR?

**Review by jalauzon-msft — APPROVED** [review]
Thanks @v-xuto for improving this test! This change looks good to me. Sorry your issue went unanswered for so long but thanks again for your contribution!

**Comment by v-xuto** [comment]
@jalauzon-msft Please help merge this PR. Thanks a lot.

**Comment by vincenttran-msft** [comment]
> @jalauzon-msft Please help merge this PR. Thanks a lot.

I can merge this for you. Sorry again for the late reply! I am new on the team and wanted to let Jacob take a first pass instead of blindly approving and merging!

**Pull request merged**
