### PR TITLE
Update graphrbac.rst

### PR DESCRIPTION
**Pull request by 4c74356b41**
more fr-fr goodness ^^

### CODE REVIEW

**Comment by lmazuel** [comment]
Thanks @4c74356b41  :)

**Comment by 4c74356b41** [comment]
hey, btw, can I ask you something, how do we replace these 2 packages? We need kinda need them, and I believe they won't be working any time soon, as they are not supported now? thanks!
azure-graphrbac 0.30.0rc6
azure-mgmt-authorization 0.30.0rc6

**Comment by lmazuel** [comment]
Hi @4c74356b41 
What do you mean? These package are available on PyPI for use:
https://pypi.python.org/pypi/azure-mgmt-authorization
https://pypi.python.org/pypi/azure-graphrbac
and are already used in the new Azure CLI in Python:
https://github.com/Azure/azure-cli

So, I don't follow you?

**Comment by 4c74356b41** [comment]
The following packages are also available as preview only, not ready for production, and will NOT be installed with the 2.0.0rc6 "azure" meta-package. We removed then from the 2.0.0rc6 to prepare our customers to the 2.0.0 stable release that will only contains the stable packages listed before.

azure-graphrbac 0.30.0rc6
azure-mgmt-authorization 0.30.0rc6
azure-mgmt-cdn 0.30.0rc6
azure-mgmt-cognitiveservices 0.30.0rc6
azure-mgmt-commerce 0.30.0rc6
azure-mgmt-dns 0.30.0rc6
azure-mgmt-iothub 0.1.0
azure-mgmt-notificationhubs 0.30.0
azure-mgmt-powerbiembedded 0.30.0rc6
azure-mgmt-trafficmanager 0.30.0rc6
azure-mgmt-web 0.30.0rc6

from https://github.com/Azure/azure-sdk-for-python

**Comment by lmazuel** [comment]
@4c74356b41 
We are currently removing the "rc" tag because we think that the code generator is stable enough now. For instance you can see azure-mgmt-resource is now 0.30.2. I can release 0.30.0 to replace 0.30.0rc6 if you wish, to show we are serious about the generator status.
However, the decision to consider the RestAPI as stable has to come from the service team in Azure. These services have not acknowledged the RestAPI as stable yet, so we can't step from 0.30.0 to 1.0.0. This is not a Python issue, for instance you can see [it's the same for the C#](https://www.nuget.org/packages/Microsoft.Azure.Management.Authorization/2.4.2-preview)
As soon as the service team assume their RestAPI as stable, we will change the version to 1.0.0.

**Comment by 4c74356b41** [comment]
Well, I'm not asking about that, I mean, how can we use those packages if they are removed? Are they maintained or not? Can we just install them separately?

**Comment by lmazuel** [comment]
`azure` is meta-package, we removed them as a dependency in this meta-package, not the packages:
- https://pypi.python.org/pypi/azure-mgmt-authorization/0.30.0rc6
- https://pypi.python.org/pypi/azure-graphrbac/0.30.0rc6

You can install them manually:
`pip install --pre azure-graphrbac azure-mgmt-authorization`

More info:
http://azure-sdk-for-python.readthedocs.io/en/latest/installation.html#installation-with-pip

**Comment by 4c74356b41** [comment]
ok, that kinda makes sense, so how do I track compatibility between those?

**Comment by lmazuel** [comment]
For RC package, I was upgrading the RC number, with or without breaking changes. I was waiting for new update to publish 0.30.0 now we decided to remove the RC tag.
Once RC is gone, since they are 0.x package, I upgrade the minor number on breaking change and the patch number on small fixes.
If it helps you, I have no problem to release 0.30.0 with the same content as 0.30.0rc6 to confirm what I said and help you track compatibility.

**Comment by 4c74356b41** [comment]
ok, let me try to comprehend that. i'm bad at thinking. can I get back to you later and ask questions about this if i have them? thanks!

**Comment by 4c74356b41** [comment]
also, i'm not sure, this python cli thing, is it considered stable\proudction ready? i'm working on a project where we use python to manage azure resources and some operations are a bit of a pain, maybe we could switch to that, but i can't seem to find any information on that cli online, do you have docs or something? thanks!

**Comment by johanste** [comment]
The announce blog is here: https://azure.microsoft.com/en-us/blog/announcing-azure-cli-2-preview/ Github repo: http://github.com/azure/azure-cli

We are more than happy to answer any questions that you may have over there. And we very much appreciate feedback.

**Comment by 4c74356b41** [comment]
so, xplat cli is generally dead? its just a matter of time right, so the cli2 = new cli that is the way to go?

**Pull request merged**
