### PR TITLE
testcase.py now uses AzureTestCase

### PR DESCRIPTION
**Pull request by bradleydamato**
Hi @seankane-msft ; it looks like a change only need to be made in `testcase.py` as `asynctestcase.py` imports `TableTestCase` from the former. 

I've run the tox tests and here are the results:
image

### CODE REVIEW

**Comment by seankane-msft** [comment]
Thanks @bradleydamato! I will double check this by pulling down your branch and running these against our live resources just to double check. I'll let you know what the results are

**Review by seankane-msft — APPROVED** [review]
LGTM! Thanks for the help @bradleydamato

**Comment by bradleydamato** [comment]
Hey @seankane-msft thanks for the approval! Just an FYI that I am not able to merge to master, but also no rush on my end!  CC@annatisch

**Comment by seankane-msft** [comment]
Sorry about that @bradleydamato, merging it now! Thanks for the contribution!

**Pull request merged**
