### PR TITLE
converge management documentation generation to the same methodology …

### PR DESCRIPTION
**Pull request by scbedd**
…in preparation for deleting generate_doc.py

Hey @changlong-liu this is out of the blue, but @sima-zhu tagged me on another PR that prompted me to start this process.

When you get a few minutes, can you please take a look at this PR? It has some changes of substance for what you see on github.io, but nothing gamebreaking. 

You don't need to worry about getting a direct comparison, I've gotten that done for you already!

For acceptance, please compare the results of a `sphinx` run of `azure-mgmt-storage`. 

Grab these two artifacts:
- [Before](https://docsupport.blob.core.windows.net/repackaged/mgmt-storage-before.zip)
- [After](https://docsupport.blob.core.windows.net/repackaged/mgmt-storage-after.zip)

And compare them.

Really the main difference is how the ToC is generated. 

image
image

### CODE REVIEW

**Comment by sima-zhu** [comment]
Thanks for taking the step! We can completely remove the `generate_doc.py` once the PR got merged in, right?

**Comment by scbedd** [comment]
@sima-zhu yep. That's right.

**Review by sima-zhu — APPROVED** [review]
LGTM

**Comment by changlong-liu** [comment]
Add @jsntcy @msyyc  for review.

Hi @scbedd , thanks for the detail information! The generated doc looks almost the same from before to after.
The mgmt SDK has been transferred to Yu's team, so I'm no longer the mgmt owner :)

**Comment by jsntcy** [comment]
@nickzhums, could you check the difference for the document?
@scbedd, LGTM. Do we need take any actions from mgmt side after you merge this PR?

**Comment by scbedd** [comment]
@jsntcy Nope other than that

> yeah we accept that our github.io will look different after this

👍

**Comment by scbedd** [comment]
@nickzhums once you sign off on this, I'll merge it. Waiting to merge till you do 👍

**Review by nickzhums — APPROVED** [review]

**Comment by nickzhums** [comment]
> @nickzhums once you sign off on this, I'll merge it. Waiting to merge till you do 👍

approved, thanks!

**Comment by scbedd** [comment]
@nickzhums 

Thank you! Not going to merge this _today_ as it does touch code that gets used in release. Next week sometime.

Thanks!

**Pull request merged**
