### PR TITLE
Fix InteractiveBrowserCredential caching

### LINKED ISSUE #8339: InteractiveBrowserCredential doesn't cache tokens
The following opens a login page twice, even when the first login is successful:
```py
from azure.identity import InteractiveBrowserCredential

credential = InteractiveBrowserCredential()

for _ in range(2):
    credential.get_token('https://vault.azure.net/.default')
```

### LINKED ISSUE #8340: InteractiveBrowserCredential fails on Python 2.7
Some class isn't new-style:
```sh
Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from azure.identity import InteractiveBrowserCredential
>>> InteractiveBrowserCredential().get_token('')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "azure\identity\_internal\exception_wrapper.py", line 23, in wrapper
    raise_from(auth_error, ex)
  File "C:\27\lib\site-packages\six.py", line 737, in raise_from
    raise value
azure.core.exceptions.ClientAuthenticationError: Authentication failed: super() argument 1 must be type, not classobj
```

### PR DESCRIPTION
**Pull request by chlowell**
With these changes, `InteractiveBrowserCredential` delegates refresh token handling to MSAL, and so should only open a browser to login once (fixes #8339). This script provides a quick validation:
```py
from azure.identity import InteractiveBrowserCredential

cred = InteractiveBrowserCredential()
tokens = {cred.get_token('https://management.azure.com/.default').token for _ in range(2)}
assert len(tokens) == 1
```
It should open a browser exactly once, and not raise `AssertionError`.

These changes also fix #8340, which was caused by calling `super` on `HTTPServer` (an old-style class).

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by chlowell** [comment]
python - identity - tests is the live test pipeline. I ran it against this branch before opening this PR. It failed as expected (because of #8314) but DevOps apparently associated that run with the commit, so this PR had failing (non-CI) tests the moment I opened it 🤷‍♂ 

Upshot: if not for this unexpected DevOps behavior, this would be a green PR.

**Pull request merged**
