### PR TITLE
[textanalytics] appease python 2 encoding for samples

### PR DESCRIPTION
**Pull request by kristapratico**
yes really

### CODE REVIEW

**Review by mssfang — APPROVED** [review]

**Review by deyaaeldeen — APPROVED** [review]

**Review by maririos — APPROVED** [review]
😆

**Review by deyaaeldeen — COMMENTED** [review]
But you did not add extractive summarization to the mix yet 😄

**Comment by kristapratico** [comment]
> But you did not add extractive summarization to the mix yet 😄

do you mean in the bullet points? it's there: https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/textanalytics/azure-ai-textanalytics/README.md

**Comment by deyaaeldeen** [comment]
@kristapratico I see, I was looking at the version in this PR and did not recognize it was behind `main` already:
Capture

**Pull request merged**
