### PR TITLE
clean up resources / fix changelog (#12432)

### PR DESCRIPTION
**Pull request by changlong-liu**

### CODE REVIEW

**Comment by weshaggard** [comment]
FYI @chidozieononiwu

**Comment by weshaggard** [comment]
Can you please cherry-pick all the changes from https://github.com/Azure/azure-sdk-for-python/pull/12432.

**Comment by weshaggard** [comment]
>These changes will resolve the said error.

Yes they will resolve it but I'd like to also get the resource reference changes from https://github.com/Azure/azure-sdk-for-python/pull/12432 included and ported into this branch as well.

**Comment by changlong-liu** [comment]
Hi @weshaggard , this PR is actually a cherry pick from #12432 .
But they are a little different because:
1.  the deleted contents in archetype-sdk-client.yml and cosmos-sdk-client.yml are not existed in release/v3 branch.   They are added into master after release/v3's lastest rebase.
2. a minor difference in CHANGELOG.md of containerregistry: looks like this is not related to this PR's topic :)

**Comment by weshaggard** [comment]
@changlong-liu OK thanks for the update I now understand why they aren't part of this PR, and I'm OK with this change as is.

@chidozieononiwu can you please take a workitem to go and remove the resource references from all the other yml files in the `release/v3` branch? I want to be sure that we don't accidently break anything else in this branch because of those.

@scbedd @praveenkuttappan any ideas why the pylint is failing in CI currently?

**Comment by changlong-liu** [comment]
Hi @praveenkuttappan @weshaggard ,  I cherry-picked lint fix for azure-core in last commit.

And the current formrecognizer issue should has no relation with mgmt release, shall I merge this PR now?

**Comment by praveenkuttappan** [comment]
@kristapratico Can you please help us on this mypy failure for form recognizer? It's on release/v3 branch.

**Comment by kristapratico** [comment]
> @kristapratico Can you please help us on this mypy failure for form recognizer? It's on release/v3 branch.

https://github.com/Azure/azure-sdk-for-python/pull/12514

**Comment by mikenass51** [comment]
I recieved this note.

**Comment by changlong-liu** [comment]
Thank you, @praveenkuttappan @kristapratico @mikenass51 . 
It's all green now.

**Pull request merged**
