### PR TITLE
[Core] type AzureNamedKey

### PR DESCRIPTION
**Pull request by swathipil**
Using AzureNamedKeyCredential in the SB SDK results in a partially untyped error when running verifytypes, since it uses the untyped AzureNamedKey namedtuple underneath. Typing AzureNamedKey gets rid of this error.

### CODE REVIEW

**Review by kristapratico — APPROVED** [review]

**Review by xiangyan99 — APPROVED** [review]

**Comment by swathipil** [comment]
Tables/ContainerRegistry pypy are failing for other reasons. All other tests are passing.

/check-enforcer override

**Pull request merged**
