### PR TITLE
Clean up the legacy mapping used by old doc generation.

### PR DESCRIPTION
**Pull request by sima-zhu**
Pre-requisite: https://github.com/Azure/azure-sdk-for-python/pull/16369

### CODE REVIEW

**Comment by weshaggard** [comment]
https://github.com/Azure/azure-sdk-for-python/blob/fc38db1cea8e6b7f22b29f3218c7bcf0f24668ca/doc/sphinx/generate_doc.py#L7 looks like this is reference there.

**Comment by sima-zhu** [comment]
It looks like the file is being used to generate package documentation. @scbedd I will close the PR if it is needed by api doc.

**Comment by scbedd** [comment]
[This PR](https://github.com/Azure/azure-sdk-for-python/pull/16369) needs to go in before yours does, but removes the dependency on the package_service_mapping.json.

**Comment by scbedd** [comment]
Hey @sima-zhu my other PR blocking this one merged. I queued [this build](https://dev.azure.com/azure-sdk/public/_build/results?buildId=738719&view=results) for you to verify that everything is a-ok.

**Comment by sima-zhu** [comment]
The [build](https://dev.azure.com/azure-sdk/internal/_build/results?buildId=738734&view=logs&j=10327055-d4d6-50a6-a312-3d2cd4bd9cb9&t=f5631f7d-b32d-5870-f8fc-4da93924d5ce) has passed.

**Review by scbedd — APPROVED** [review]
That should be the last piece using that guy. You're fine now.

**Pull request merged**
