### PR TITLE
ACR 2017-10-01

### PR DESCRIPTION
**Pull request by lmazuel**
@djyou Ready for tests and review on your side

### CODE REVIEW

**Comment by lmazuel** [comment]
@djyou This error means that you leaked an AzureOperationPoller unfinished from one of your tests. Be sure to explictly call `wait` or `result` on all the AzureOperationPoller before the end of the tests.

Note that we have a task to add in the test framework the detection of that and a more detailled exception, but still not done yet.

**Comment by derekbekoe** [comment]
@djyou @lmazuel I will restart CI for the PR after https://github.com/Azure/azure-cli/pull/4523 has been merged.

**Comment by derekbekoe** [comment]
Restarted.

**Comment by djyou** [comment]
@derekbekoe Do you know why one of the CI couldn't start properly?

**Pull request merged**
