### PR TITLE
[textanalytics] Add azure-ai-nspkg to artifacts in ci.yml

### PR DESCRIPTION
**Pull request by kristapratico**

### CODE REVIEW

**Comment by scbedd** [comment]
Given that the package isn't set to be `universal`, I have a feeling that the set of artifacts will have a `py2` and `py3` whl generated separately.

**Comment by kristapratico** [comment]
@scbedd thanks for pointing that out. I think I added the correct setup.cfg file to fix this, can you verify?

**Comment by scbedd** [comment]
@kristapratico Absolutely, will wait for next set of checks

**Comment by kristapratico** [comment]
Well, it says 5 artifacts but only shows 4 published: [link](https://dev.azure.com/azure-sdk/public/_build/results?buildId=227991&view=results)

Looks like the nspkg is no longer being generated with separate py2 and py3 whls.

**Comment by scbedd** [comment]
Aligns with what we published for `azure-keyvault-nspkg`!

LGTM!

image

**Comment by kristapratico** [comment]
Thanks Scott. That makes a lot of sense :)

**Pull request merged**
