### PR TITLE
change list interface

### PR DESCRIPTION
**Pull request by xiangyan99**

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by bryevdv** [comment]
`update_pr` is failing on at least a few PRs at once right now, reporting that `git` is not installed @scbedd are you aware of this?

**Comment by scbedd** [comment]
@bryevdv hey appreciate the extra heads up. We new there were update_pr issues, but this is a new one. We're on it.

**Comment by bryevdv** [comment]
@xiangyan99 Does this PR supersede #9066?

**Comment by xiangyan99** [comment]
> supersede

Yes

**Comment by xiangyan99** [comment]
> @xiangyan99 Does this PR supersede #9066?

Yes

**Pull request closed without merging**
