### PR TITLE
[eventhub] Fix typo

### PR DESCRIPTION
**Pull request by jeesang7**
# Description
Fix typo in keyword `lease` in  _get_block_list_

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by kristapratico** [comment]
@jeesang7 thanks so much for your contribution! This appears to be more than just a typo -- it's actually a bug fix since it looks like the user-provided keyword argument is ignored. @jalauzon-msft @kashifkhan - would you mind taking a look at this?

**Comment by jalauzon-msft** [comment]
Thanks @jeesang7! This is definitely a bug in Storage so thanks for finding this and making the fix.

The change looks good from the Storage side but I'm not entirely sure if we can change the `eventhub` Storage code directly. The Storage code in `eventhub` appears to be a fork of the Storage code which I assume is periodically updated from the Storage packages. I'm not sure the cadence of this update and if manual changes are allowed. @kashifkhan or @l0lawrence any idea on this?

**Comment by l0lawrence** [comment]
We can manually update this for eventhub

**Review by jalauzon-msft — APPROVED** [review]
Thanks again @jeesang7!

**Pull request merged**
