### PR TITLE
Rename AutoLockRenew to AutoLockRenewer

### PR DESCRIPTION
**Pull request by rakshith91**

### CODE REVIEW

**Review by yunhaoling — COMMENTED** [review]
we also need to update the term mentioned in migration guide: 
https://github.com/Azure/azure-sdk-for-python/blob/master/sdk/servicebus/azure-servicebus/migration_guide.md

**Review by KieranBrantnerMagee — APPROVED** [review]
LGTM, obviously pending Adam's OK of his comment as well.

**Review by yunhaoling — APPROVED** [review]
LGTM

**Pull request merged**
