### PR TITLE
Clean up azure-mgmt-agfood and azure-mgmt-azureadb2c which hit EOL 3/31/2023

### PR DESCRIPTION
**Pull request by JimSuplizio**
[azure-mgmt-agfood](https://github.com/Azure/azure-sdk/blob/main/_data/releases/latest/python-packages.csv?plain=1#L85) and [azure-mgmt-azureadb2c](https://github.com/Azure/azure-sdk/blob/main/_data/releases/latest/python-packages.csv?plain=1#L99) both hit EOL on 3/31/2023. This means these are no longer supported and there's no need for them to be part of the repository anymore.

I've already deleted both sets of public and private pipelines. This PR is to remove the source code from the repository.

//CC @scbedd and @mario-guerra so you're both aware.

### CODE REVIEW

**Review by danieljurek — COMMENTED** [review]
LGTM. I see no CODEOWNERS for these packages. We should check w/ Laurent. 

@lmazuel - This PR removes source code for packages that have reached EOL and are not supported. Removal is the right thing to do from our perspective. cc @scbedd 

Jim found these while doing some clean up work on docs.

**Comment by lmazuel** [comment]
For clarity for customers, I would do a final release to PyPI with a deprecation message, and a link to the new library (if any)
- https://pypi.org/project/azure-mgmt-agfood/
- https://pypi.org/project/azure-mgmt-azureadb2c/

As PyPI do not allow text update, it has to go with a release. @scbedd has a system to bypass most of the CI in this scenario, since we don't care about compliance for something we are killing.

**Comment by JimSuplizio** [comment]
> For clarity for customers, I would do a final release to PyPI with a deprecation message, and a link to the new library (if any)
> 
> * https://pypi.org/project/azure-mgmt-agfood/
> * https://pypi.org/project/azure-mgmt-azureadb2c/
> 
> As PyPI do not allow text update, it has to go with a release. @scbedd has a system to bypass most of the CI in this scenario, since we don't care about compliance for something we are killing.

@lmazuel With both of these being pre-release versions, never GA'd, does this need to be done? As far as I'm aware, releasing a new version of these libraries would restart the EOL clock. We'd hit this with a couple of Java libraries last year. I'm not sure when these were flagged deprecated but it seems like they should have been released at that time, instead of two months after the EOL date.

**Comment by scbedd** [comment]
@JimSuplizio I will do a separate PR. Add `Inactive` classifier, bump the beta version, add a changelog entry, and update the readme with deprecated notification above the content. After that merges and releases, you'll have a merge conflict, but then will be unblocked to merge to `main`.

**Comment by scbedd** [comment]
> @JimSuplizio I will do a separate PR. Add `Inactive` classifier, bump the beta version, add a changelog entry, and update the readme with deprecated notification above the content. After that merges and releases, you'll have a merge conflict, but then will be unblocked to merge to `main`.

I just noticed that both of the pipelines are already deleted, so I will use the partner release pipelines to cut new versions of these.

**Comment by JimSuplizio** [comment]
@scbedd, do you just want me to kill this PR and you can recreate it, or not, when you're done?

**Comment by JimSuplizio** [comment]
Rather than deal with merge conflicts for something I'm obliterating. I'm going to kill this PR and make another one as it'll require far less effort.

**Pull request closed without merging**
