### PR TITLE
we renamed the file but did not update the baseline file. Fix it.

### PR DESCRIPTION
**Pull request by xiangyan99**
# Description

Please add an informative description that covers that changes made by the pull request and link all relevant issues.

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [ ] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by mccoyp** [comment]
CI run for this PR: https://dev.azure.com/azure-sdk/public/_build/results?buildId=1524529&view=results

**Comment by mccoyp** [comment]
Looks like the warning is still being raised despite the name update in the baseline file. @sima-zhu, do you know why that is?

@xiangyan99 if the package owners are okay with us making a change on their behalf, could we move the [fake secret](https://github.com/Azure/azure-sdk-for-python/blob/de2b0fed1ea4bac5066610ee94ab36b3649b320b/sdk/hdinsight/azure-mgmt-hdinsight/test/disable_test_mgmt_hdinsight.py#L59) that's raising the error into our [fake credential store](https://github.com/Azure/azure-sdk-for-python/blob/main/tools/azure-sdk-tools/devtools_testutils/fake_credentials.py) instead, and import it in the test file? We could then remove the baseline suppression entirely, which is the eventual goal anyway. We could probably name the secret value `MGMT_HDINSIGHT_FAKE_KEY`

**Comment by xiangyan99** [comment]
> Looks like the warning is still being raised despite the name update in the baseline file. @sima-zhu, do you know why that is?
> 
> @xiangyan99 if the package owners are okay with us making a change on their behalf, could we move the [fake secret](https://github.com/Azure/azure-sdk-for-python/blob/de2b0fed1ea4bac5066610ee94ab36b3649b320b/sdk/hdinsight/azure-mgmt-hdinsight/test/disable_test_mgmt_hdinsight.py#L59) that's raising the error into our [fake credential store](https://github.com/Azure/azure-sdk-for-python/blob/main/tools/azure-sdk-tools/devtools_testutils/fake_credentials.py) instead, and import it in the test file? We could then remove the baseline suppression entirely, which is the eventual goal anyway. We could probably name the secret value `MGMT_HDINSIGHT_FAKE_KEY`

I am ok to move it into our fake cred store. But we still want to know why it failed? @sima-zhu

**Comment by sima-zhu** [comment]
> > Looks like the warning is still being raised despite the name update in the baseline file. @sima-zhu, do you know why that is?
> > @xiangyan99 if the package owners are okay with us making a change on their behalf, could we move the [fake secret](https://github.com/Azure/azure-sdk-for-python/blob/de2b0fed1ea4bac5066610ee94ab36b3649b320b/sdk/hdinsight/azure-mgmt-hdinsight/test/disable_test_mgmt_hdinsight.py#L59) that's raising the error into our [fake credential store](https://github.com/Azure/azure-sdk-for-python/blob/main/tools/azure-sdk-tools/devtools_testutils/fake_credentials.py) instead, and import it in the test file? We could then remove the baseline suppression entirely, which is the eventual goal anyway. We could probably name the secret value `MGMT_HDINSIGHT_FAKE_KEY`
> 
> I am ok to move it into our fake cred store. But we still want to know why it failed? @sima-zhu

Right, the baseline file is using hash somehow. Rename directly does not fix the error.

**Comment by sima-zhu** [comment]
Python has guideline of fixing this. It is better to fix as @mccoyp suggested.

**Comment by xiangyan99** [comment]
@mccoyp could you help to move those fake secrets into our [fake credential store](https://github.com/Azure/azure-sdk-for-python/blob/main/tools/azure-sdk-tools/devtools_testutils/fake_credentials.py)?

**Comment by xiangyan99** [comment]
Close this one as we will use #24274 instead.

**Pull request closed without merging**
