### PR TITLE
add health report pipeline

### PR DESCRIPTION
**Pull request by kristapratico**
Adding the health report generation to the aggregate-reports pipeline.

Test run: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=4104693&view=logs&j=09cf8b18-32ff-5ace-942c-480825d4e4bd&t=2587bd3b-68d6-5949-3508-73f37cab414a

This will update the health report for the repo: https://aka.ms/azsdk/python/health

### CODE REVIEW

**Comment by weshaggard** [comment]
Any reason this wouldn't go into the "python - aggregate-reports" pipeline? This seems to be exactly along the lines of other things in there.

**Comment by kristapratico** [comment]
> Any reason this wouldn't go into the "python - aggregate-reports" pipeline? This seems to be exactly along the lines of other things in there.

Wasn't aware of this pipeline or its purpose, I'll take a look.

**Comment by kristapratico** [comment]
> Any reason this wouldn't go into the "python - aggregate-reports" pipeline? This seems to be exactly along the lines of other things in there.

Okay, added the steps to aggregate-reports instead 👍

**Review by weshaggard — APPROVED** [review]

**Comment by kristapratico** [comment]
/check-enforcer override

core failure is unrelated

**Pull request merged**
