### PR TITLE
[AutoRelease] t2-resourcegraph-2021-03-31-51385

### PR DESCRIPTION
**Pull request by msyyc**
https://github.com/Azure/sdk-release-request/issues/1415
--

### CODE REVIEW

**Comment by fenwickt** [comment]
Hi,

I believe basic query and facet query tests are failing because in the new api version we've changed the default output format to be an object array (basically json), while tests are still expecting the table format. 

For a quick fix, please add *options* param to both test_resources_basic_query and test_resources_facet_query:
query = QueryRequest(
            query='project id, tags, properties | limit 2',
            subscriptions=[self.settings.SUBSCRIPTION_ID],
            options=QueryRequestOptions(
                result_format=ResultFormat.table
            ), ...<any other params>)

I will revisit these tests later and update them accordingly to the changes.

**Comment by fenwickt** [comment]
@msyyc let me know whether the tests are a blocker for releasing the library and if I can help with anything.

**Review by 00Kai0 — APPROVED** [review]

**Pull request merged**
