### PR TITLE
[AutoPR] compute/resource_manager

### PR DESCRIPTION
**Pull request by lmazuel**

### CODE REVIEW

**Comment by lmazuel** [comment]
@AutorestCI rebase

**Comment by samedder** [comment]
@lmazuel what do you need my review on, this all looks like compute?

**Comment by lmazuel** [comment]
@AutorestCI rebase

**Comment by lmazuel** [comment]
@AutorestCI rebase

**Comment by lmazuel** [comment]
@AutorestCI rebuild https://github.com/Azure/azure-rest-api-specs/blob/master/specification/compute/resource-manager/readme.md

**Pull request merged**
