### PR TITLE
fix cspell issues for azure-communication identity

### PR DESCRIPTION
**Pull request by AikoBB**
# Description
Fixed cspell issues for azure-communication identity
Resolves https://github.com/Azure/azure-sdk-for-python/issues/22636

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by petrsvihlik — APPROVED** [review]

**Review by petrsvihlik — CHANGES_REQUESTED** [review]
how come the PR doesn't contain these?

```
./sdk/communication/azure-communication-identity/azure/communication/identity/_shared/user_credential_async.py:53:43 - Unknown word (inprogress)
./sdk/communication/azure-communication-identity/azure/communication/identity/_shared/user_credential_async.py:77:26 - Unknown word (inprogress)
./sdk/communication/azure-communication-identity/azure/communication/identity/_shared/user_credential.py:55:37 - Unknown word (inprogress)
./sdk/communication/azure-communication-identity/azure/communication/identity/_shared/user_credential.py:77:20 - Unknown word (inprogress)
./sdk/communication/azure-communication-identity/azure/communication/identity/_shared/policy.py:11:46 - Unknown word (IOHTTP)
./sdk/communication/azure-communication-identity/azure/communication/identity/_shared/policy.py:14:33 - Unknown word (IOHTTP)
```

**Comment by AikoBB** [comment]
> how come the PR doesn't contain these?
> 
> ```
> ./sdk/communication/azure-communication-identity/azure/communication/identity/_shared/user_credential_async.py:53:43 - Unknown word (inprogress)
> ./sdk/communication/azure-communication-identity/azure/communication/identity/_shared/user_credential_async.py:77:26 - Unknown word (inprogress)
> ./sdk/communication/azure-communication-identity/azure/communication/identity/_shared/user_credential.py:55:37 - Unknown word (inprogress)
> ./sdk/communication/azure-communication-identity/azure/communication/identity/_shared/user_credential.py:77:20 - Unknown word (inprogress)
> ./sdk/communication/azure-communication-identity/azure/communication/identity/_shared/policy.py:11:46 - Unknown word (IOHTTP)
> ./sdk/communication/azure-communication-identity/azure/communication/identity/_shared/policy.py:14:33 - Unknown word (IOHTTP)
> ```

These words were added by other teams

**Review by danieljurek — APPROVED** [review]
cspell does not have a great way to determine word boundaries for collections of letters inside of things that are, to a human, obviously encoded values. 

For future consideration: If you plan on changing these values frequently it might be easier to store the values in a separate file(s) and add those files to the list of files to ignore. Otherwise this method works well enough and will help you spot spelling errors in the rest of the tests.py file.

**Review by petrsvihlik — APPROVED** [review]

**Pull request merged**
