### PR TITLE
[translation] fix samples with renamed params

### PR DESCRIPTION
**Pull request by kristapratico**
Resolves https://github.com/Azure/azure-sdk-for-python/issues/20059

Missed updating these in the renaming PR.

### CODE REVIEW

**Review by iscai-msft — APPROVED** [review]
:shipit:

**Review by maririos — APPROVED** [review]
curious, how did you notice the difference?
is there a way the CI could check if the samples are not updated with the latest code changes?

**Comment by kristapratico** [comment]
> curious, how did you notice the difference?
> is there a way the CI could check if the samples are not updated with the latest code changes?

Our vendor team opened an issue when testing samples. We do run all translation samples through CI _except_ these ones which will depend on user input to set the filters.

**Comment by maririos** [comment]
>Our vendor team opened an issue when testing samples

Wow!!! Love to see that we have that extra validation :)\

Thanks for the context!

**Pull request merged**
