### PR TITLE
Python 3.6

### PR DESCRIPTION
**Pull request by lmazuel**

### CODE REVIEW

**Comment by brettcannon** [comment]
This PR is missing the updates to the trove classifiers to list Python 3.6 as supported.

**Comment by lmazuel** [comment]
For the new part, I already updated my cookiecutter template: https://github.com/Azure/cookiecutter-azuresdk-pypackage/commit/f0bd87847d52bfedfd3d6eb9a11aef9ea31281f8

**Comment by lmazuel** [comment]
@brettcannon I added the classifiers. Thoughts?

**Comment by brettcannon** [comment]
@lmazuel LGTM

**Pull request merged**
