### PR TITLE
Unified Pipelines for most of repo

### PR DESCRIPTION
**Pull request by mitchdenny**
This PR enables unified pipelines for everything that isn't shipped as part of the client SDK preview, as well as adding a few artifacts to those that did ship. This can wait to be merged after the preview ships but it is a fairly big set of changes since we have so many pipelines for Python.

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by mitchdenny** [comment]
> Tell me you didn't have to manually create the `name`, `safename` combinations Mitch. There are a lot of these O.o

For the big list of artifacts like cog services I had a PowerShell one liner ;) Automation is up there on the list after this experience. I actually want to eliminate safeName entirely.

**Pull request merged**
