### PR TITLE
Make private Cosmos modules private [WIP]

### PR DESCRIPTION
**Pull request by bryevdv**
As part of this I am also making previously private class names public, when inside a private module, i.e.

> consistent_hash_ring._ConsistentHashRing -> _consistent_hash_ring.ConsistentHashRing 

There aren't a lot of changes for each, but each one is scattered over a few locations so the going is a bit tedious. I wanted to post this WIP PR to make sure everyone is in agreement with this before proceeding further (I would propose to do this for every module entry on the review spreadsheet marked "hide")

cc @johanste @christopheranderson

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by bryevdv** [comment]
Also FYI a few of them hav code that does not appear to be used anywhere, e.g. `range` and `range_partition_resolver` are not imported anywhere AFAICT:

> ~/work/azure-sdk-for-python/sdk/cosmos/azure-cosmos bryanv/cosmos_docs_modules
base ❯ grip range_partition_resolver
>
> ~/work/azure-sdk-for-python/sdk/cosmos/azure-cosmos bryanv/cosmos_docs_modules

**Comment by bryevdv** [comment]
@christopheranderson @johanste I wanted to give an update. With the current changes, the docs page looks like this:

Screen Shot 2019-07-18 at 5 54 07 PM

Some of those modules are not renamed because they are used in Sample code. I think we should avoid moving those remaining modules that are used for transitive imports because if they are renamed the "[source]" links go to private modules, which as a user I would find strange:

Screen Shot 2019-07-19 at 9 02 00 AM

As a compromise, I would suggest adding a top level docstring in `__init__.py` (this should be done anyway, really) But in it we can quickly at the top to the most important concepts. A mockup of that looks like:

Screen Shot 2019-07-19 at 9 07 58 AM

Doing that also avoids having to try to make any special cases for building these docs. Let me know what you think, I can certainly move the other modules to be private that is really desired.

**Comment by johanste** [comment]
Does the sample code import types directly from the submodules or from azure.cosmos? If the former, we should probably update the sample code.

**Comment by bryevdv** [comment]
@johanste 

`azure.cosmos.base` is imported in one sample but never actually use (no linting for samples?) So it can be made private. 

Otherwise `auth` and `http_constants` are used in these ways (which are not in `azure.cosmos`:
```
base ❯ grip "auth\." samples
samples/NonPartitionedCollectionOperations/Program.py:
  129 :         authorization = auth.GetAuthorizationHeader(

~/work/azure-sdk-for-python/sdk/cosmos/azure-cosmos bryanv/cosmos_docs_modules*
base ❯ grip http_constants samples
samples/MultiMasterOperations/ConflictWorker.py:
    6 : from azure.cosmos.http_constants import StatusCodes
samples/MultiMasterOperations/Worker.py:
    4 : from azure.cosmos.http_constants import StatusCodes
```

**Comment by bryevdv** [comment]
I've made `base.py` private as well. @christopheranderson Any thought on how the docs look at this stage? i.e. whether to keep small list of submodules above and add a module docstring with refs to the most important things?

**Comment by bryevdv** [comment]
per discussion with Mayuri, merging this now ahead of Friday and can continue to iterate on docs formatting in the future

**Pull request merged**
