### PR TITLE
small edits to lease client docs

### PR DESCRIPTION
**Pull request by bryevdv**

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by annatisch** [comment]
Thanks for the update!
Though there's a trailing whitespace on line 88 ;)

**Comment by bryevdv** [comment]
@scbedd any idea why this is failing? It just says pylint but does not give details. AFAICT there is no trailing whitespace. I added a "d" to "released" to kick CI. Previously all the jobs were green but the check-enforcer job never finished after ~3hrs.

**Comment by xiafu-msft** [comment]
@annatisch I think we want to merge this to feature/storage-preview4 instead of master?

**Comment by xiafu-msft** [comment]
@bryevdv It's failing because of the doc(not related to your change) wasn't formatted properly I guess. I saw it also failed in feature/storage-preview4. There was a commit just merged into the feature/storage-preview4 so I think the CI will be green now.

**Comment by bryevdv** [comment]
Thanks @xiafu-msft I have changed the base to `feature/storage-preview4`

**Comment by scbedd** [comment]
@bryevdv I think the pylint failure was probably due to the fact that it throws the `trailing whitespace` error for doc strings if the line isn't completely **blank**. @kristapratico actually showed me this when I was trying to get my checkin done on Wednesday.

If that errors is gone though 👍

**Pull request merged**
