### PR TITLE
Adding 2020-09-01-hybrid profile

### PR DESCRIPTION
**Pull request by abbhar**

### CODE REVIEW

**Review by bganapa — DISMISSED** [review]

**Review by bganapa — APPROVED** [review]

**Comment by changlong-liu** [comment]
Hi @msyyc @jsntcy , it's is a PR for AzureStack.
Would you help to merge this?

**Review by changlong-liu — APPROVED** [review]

**Comment by bganapa** [comment]
@jsntcy Thanks for the merge. Could you please let me know when are we planning to do the next release of azure-common package? I do not have an urgency, just wanted to know the timeline

**Pull request merged**
