### PR TITLE
updated pythonsdk for new swagger api-version for botservice

### PR DESCRIPTION
**Pull request by swagatmishra2007**
1) regenerated the python sdk with the latest swagger
2) added tests for newly added resource and other changes

### CODE REVIEW

**Comment by swagatmishra2007** [comment]
@lmazuel  i generated the python sdk using - autorest --version=latest readme.md --python --azure-arm=true --payload-flattening-threshold=2 --license-header=MICROSOFT_MIT_NO_VERSION --namespace=azure.mgmt.botservice --package-name=azure-mgmt-botservice --package-version=0.2.0

However, version.py still has it hardcorded as "0.0.1" . Should i update it manually? shouldnt autorest have updated it?

**Comment by lmazuel** [comment]
Hi @swagatmishra2007 could you update your autorest and reset it:
- npm install -g autorest
- autorest --reset

And then regenerate. You're using an old version of Autorest.
Thanks!

**Comment by swagatmishra2007** [comment]
i renegerated the sdk, but the version.py problem doesnt seem to be solved. 
Here's my autorest info - 
AutoRest code generation utility [version: 2.0.4283; node: v8.2.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest


Showing All Installed Extensions

 Type       Extension Name                           Version      Location
 core       @microsoft.azure/autorest-core           2.0.4283     C:\Users\swagatm\.autorest\@microsoft.azure_autorest-core@2.0.4283
 extension  @microsoft.azure/autorest.modeler        2.3.44       C:\Users\swagatm\.autorest\@microsoft.azure_autorest.modeler@2.3.44
 extension  @microsoft.azure/autorest.python         2.1.40       C:\Users\swagatm\.autorest\@microsoft.azure_autorest.python@2.1.40

**Comment by lmazuel** [comment]
Hum, still not using the latest autorest. @fearthecowboy I thought with my recent PR now Autorest uses the 3.x of Python.

@swagatmishra2007 actually, if you update this file with the new version 0.2.0:
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/botservice/resource-manager/readme.python.md

You should get an automatic Python generation for free, and you don't have to generate it manually.

If you still want to generate manually, please add `--use=@microsoft.azure/autorest.python@~3.0.56`. This should not be needed, but at least after that you have the right version of Autorest for sure. And then we''ll change version.py later

**Comment by swagatmishra2007** [comment]
No, it's this one - https://github.com/Azure/azure-rest-api-specs/pull/3478 
(further to your point above, i am going to update the readme.python.md file next time, so that i dont have regenerate the sdk manually)

**Comment by lmazuel** [comment]
Should I wait or do you want a release of this particular PR, and later another one for 3577?

**Comment by swagatmishra2007** [comment]
we need a release of this particular PR, since we are going to use this version for  publishing our CLI module. The 3577 PR is actually a new azure resource and wont go live for quite sometime.
So please merge when ready :)

**Pull request merged**
