### PR TITLE
[WIP] Add some initial support for network security groups

### PR DESCRIPTION
**Pull request by andre-geldenhuis**
Hi

I've added a start on support for network security groups.  I really need them for a project I'm working on so I started writing some code rather than creating an issue.

This pull request allows creating, deleting and listing network security groups.  This isn't really useful yet as at the very least you also need to be able to add the security group to a subnet and add some rules to it.

If this isn't up to the project standards, please let me know and I'll do what I can to fix it.
Cheers :)
Andre

### CODE REVIEW

**Comment by huguesv** [comment]
Your changes look fine, we'll be happy to take them if you can add some tests.

FYI:
We're working on support for compute, network, storage and resource manager (ARM) REST APIs:
https://msdn.microsoft.com/en-us/library/azure/dn948464.aspx

We should be able to release a preview of them soon.  We have some reorg of the repository/packages that we need to do first.

The existing ServiceManagement will become legacy when support for ARM is available.

**Comment by andre-geldenhuis** [comment]
Will do.  thanks for the heads up on ARM :)

**Comment by lmazuel** [comment]
Hello @andre-geldenhuis 

We changed a lot of things with the release 1.0 with the integration of the ARM preview version. As @huguesv said, the ASM library is now "legacy" code and has been slightly changed to fit in the new package template. You can find the changes in our ChangeLog.txt at the root of the repository in the "release 1.0.0" section.

Are you able to correct your pull-request to fit into the "legacy" code architecture? 

If you can do that, I will try to test/merge asap. Even if it's legacy code, I think that your commit will be very easy to fit into the new architecture, so no reason to loose your job :-).
If you didn't have time or think that the ARM version is enough for you, please let me know and I will close the PR.

Thank you!

**Comment by lmazuel** [comment]
Closing this PR, because this cannot be merged into our current code. Moreover, the ASM system is legacy and the ARM version will cover this feature.
Please feel free to re-open if you need this feature in the ASM legacy code, with a branch up to date with the current master.

**Comment by andre-geldenhuis** [comment]
Yup makes sense.  This was only a preliminary bit of code in anycase.

**Pull request closed without merging**
