### PR TITLE
Migrate Event Hub SDK to central Repo

### PR DESCRIPTION
**Pull request by yunhaoling**
Docs have been updated. Next step is to integrate with CI.

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by annatisch** [comment]
FYI @lmazuel - It would be great it you could take a look at the fundamentals - setup.py etc etc.
In terms of a thorough code review, up to you - but we're planning a track 2 SDK release in the near future so much of the API may change.

**Comment by annatisch** [comment]
@lmazuel - it looks like I don't have permissions to merge this into master.
This PR is the EventHubs SDK as it is currently published (i.e. we are not planning a new release immediately - when we wish to do a subsequent release we will PR those updates separately).

This PR preserves the entire commit history of the EventHubs SDK - though I appreciate that it will probably be squashed on merge.
Could you please take a look?

**Pull request merged**
