### PR TITLE
update readme

### PR DESCRIPTION
**Pull request by xiangyan99**

### CODE REVIEW

**Review by kristapratico — APPROVED** [review]

**Comment by kristapratico** [comment]
Should we also add the link to the sample at the top like this?

image

**Review by xiangyan99 — COMMENTED** [review]
I like the idea. But this means we need to update our README template. We may want to loop in more people for discussion.

**Comment by kristapratico** [comment]
It looks okay to add according this template: https://github.com/Azure/azure-sdk/blob/master/docs/policies/README-TEMPLATE.md

But not sure if I'm looking at the right one. I got it from here: https://review.docs.microsoft.com/en-us/help/contribute-ref/contribute-ref-how-to-document-sdk?branch=master#readme

**Comment by xiangyan99** [comment]
It is included in #14769

**Pull request closed without merging**
