### PR TITLE
Add resetuserpassword in user_operations

### PR DESCRIPTION
**Pull request by sfonteneau**

### CODE REVIEW

**Comment by lmazuel** [comment]
Hi @sfonteneau 

Thank you for your contribution! However, I can't accept it directly, because this code is auto-generated from a Swagger specification.
I created an issue in the MS Swagger repo about this, to add the Swagger definition of this endpoint:
https://github.com/Azure/azure-rest-api-specs/issues/358

I keep this bug open until we have an answer on the Swagger issue.

Thank you again!

**Comment by sfonteneau** [comment]
Thank you! Meanwhile, adding "reset user password" works.

**Comment by sfonteneau** [comment]
I just see that the issue is closed

How do I do?
What are the best-practice?

**Comment by lmazuel** [comment]
Yes, the Swagger file has been validated. This means that the next Python release 2.0.0RC5 will include the fix inside.
I plan to release it mid next-week.

**Comment by sfonteneau** [comment]
Great ! Thank you very much for your response !

**Comment by lmazuel** [comment]
Hi @sfonteneau 

I just released the 0.30.0RC5 library with an updated GraphRbac. There is some little breaking changes, because we moved from Rest API Version "1.6-preview" to "1.6" (which is a good sign). All breaking changes are just renaming ([this is an example of renaming in my tests](https://github.com/Azure/azure-sdk-for-python/commit/b03cae526d9ac46d1b477840f15d3729aa0d939f#diff-296e794143f66af83d1bf2db6eb7a935))

The GraphRbac team told me that the thing you want to do must be made through the "update_user" method. I close this PR now, but feel free to open an issue if you have difficulties to plug the "update_user" for password reset.

Thank you again for your feedback!

**Comment by sfonteneau** [comment]
everything works perfectly well with update_user . Thank you

**Pull request closed without merging**
