### PR TITLE
Drop 3.6 python version support  for the communication services

### PR DESCRIPTION
**Pull request by AikoBB**
# Description

- Dropped 3.6 python version support for the communication services
- Synched up the shared folder across all communication modalities

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by lucasrsant — APPROVED** [review]
Approved for PhoneNumbers. Thanks for taking care of this.

**Review by yogeshmo — APPROVED** [review]
Looks good to me, thanks for handling this!

**Review by petrsvihlik — APPROVED** [review]
looks ok 👍

note: when syncing the _shared folders, it would be nice for the reviewers to know which file was considered as a source of truth and copied to other modalities

**Review by maximrytych-ms — APPROVED** [review]

**Review by shirleyqin-msft — APPROVED** [review]

**Review by LuChen-Microsoft — APPROVED** [review]

**Review by ajpeacock0 — APPROVED** [review]

**Review by besh2014 — APPROVED** [review]
All good for SMS

**Comment by elavarasidc** [comment]
@shirleyqin-msft has verified the changes from ACS Rooms. Changes looks good for Rooms.

**Pull request merged**
