### PR TITLE
[Key Vault] Update docstrings for `next-pylint`

### PR DESCRIPTION
**Pull request by mccoyp**
# Description

This updates documentation throughout all KV libraries to conform to the standards of the `next-pylint` check.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by mccoyp** [comment]
Updated weekly pipeline shows that `pylint-next` check is still green: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2853585&view=logs&j=1401073d-e1dc-5a16-1dec-e5eaef9eaad4&t=bc894be0-00bb-5d6a-39fa-13a603e483e5

**Review by YalinLi0312 — APPROVED** [review]

**Pull request merged**
