### PR TITLE
Replace compile-time `validateFormatting` parameter

### PR DESCRIPTION
**Pull request by scbedd**
Resolves https://github.com/Azure/azure-sdk-for-python/issues/35153

1. Removes `validateFormatting` parameter
2. `black` is opt-out by default,  but individual packages can opt in with `black = true` in their `pyproject.toml`
3. Update all `ci.yml` to remove validateFormatting and individually re-enabled `black` on those packages that were running it prior to this PR.

This change is necessary because of the fact that `python - pullrequest` doesn't have access to the parameter that you have set for your `ci.yml`. We need to emplace it some place else that's universal.

I'm taking a look now because @LibbaLawrence ran into exactly this issue with `azure-eventhub` running on `python - pullrequest`.

This PR moves these settings from the `validateFormatting` template parameter to a per-package `pyproject.toml`.
 
TODO:

- [x] Invert old `validate_formatting.py` into being called from `tox` instead of `validate_formatting` calling `tox.
- [x] update that tox `black` calling script with `is_check_enabled`.
- [x] Verify that it still invokes, and doesn't break any dev scenarios (confirm with @kdestin)

### CODE REVIEW

**Review by l0lawrence — APPROVED** [review]
Is this going to cause CI failures if an sdk currently has black=True but ValidateFormatting False?

**Comment by scbedd** [comment]
> Is this going to cause CI failures if an sdk currently has black=True but ValidateFormatting False?

I'm finding the # of packages that fit in that gap (that aren't mgmt). We don't run `black` check against `mgmt` packages. If it's only a few, I'll set `pyproject.toml` `black=False`.

If not...we'll see 😆

**Comment by scbedd** [comment]
We have one of two avenues:

- We set `black` check to `off` by default.
    - I go in and adjust 5 services to update pyproject.toml updates with `black=true` in them.

OR

- We set `black` to `on` by default
- We omit mgmt packages from checks
- We individually set `black=false` on anyone failing (or doesn't currently have `validateFormatting: true` on their `ci.yml`.

**Comment by l0lawrence** [comment]
> We have one of two avenues:
> 
>     * We set `black` check to `off` by default.
>       
>       * I go in and adjust 5 services to update pyproject.toml updates with `black=true` in them.
> 
> 
> OR
> 
>     * We set `black` to `on` by default
>       
>       * We omit mgmt packages from checks
>       * We individually set `black=false` on anyone failing (or doesn't currently have `validateFormatting: true` on their `ci.yml`)

I think right now black is an opt-in so I would vote for #1 to remain consistent

**Review by weshaggard — APPROVED** [review]

**Comment by scbedd** [comment]
> I think right now black is an opt-in so I would vote for 1 to remain consistent

Agreed, I'll make that change in this PR after making the other adjustments for opt in.

**Review by pvaneck — APPROVED** [review]

**Comment by scbedd** [comment]
/check-enforcer override

Single failure to download an environment seed.

**Pull request merged**
