### PR TITLE
Fix ci.yml for applicationinsights

### PR DESCRIPTION
**Pull request by mitchdenny**
I had two errors that I'm hoping to fix in this PR. The first is an extra ```ci.yml``` file that is no longer required (and was broken anyway) and the ```azure-applicationinsights``` module missing from the targetting string. The build is failing because of lack of code coverage results. This might fix it, although its probably just masking an issue of not handling no code coverage results gracefully (in mgmt scenarios I suspect).

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by mitchdenny** [comment]
OK, this fixes the ```python - applicationinsights - ci``` pipeline. By making sure that the client library builds as well as the management library we get some code coverage emitted. It doesn't fix the situation where code coverage missing causes the pipelines to fail, but we wouldn't have noticed if I had the ```ci.yml``` file for this setup correctly ;)

**Comment by mitchdenny** [comment]
Slipped another change in to this PR. I noticed that multiple CG jobs were getting injected during the build and we already had it explicitly in the Analyze step so I've disabled it via a global (still runs in the job we explicitly include it in). We don't see it in the PRs, but we do with manually triggered CI.

**Comment by mitchdenny** [comment]
@scbedd could you merge this for me?

**Pull request merged**
