### PR TITLE
[ACR] Drop Python 3.6

### PR DESCRIPTION
**Pull request by YalinLi0312**

### CODE REVIEW

**Review by xiangyan99 — APPROVED** [review]

**Comment by YalinLi0312** [comment]
Hi @msyyc, can you help to take a look the min dependency conflicts in CI? It looks is a conflict in mgmt acr sdk.

**Comment by msyyc** [comment]
CI failure caused by `azure-mgmt-containerregistry` is fixed. Current failure is caused by unconsistency of mindep between `setup.py` and `share_requirements.txt`. Please refer to https://github.com/Azure/azure-sdk-for-python/pull/25756/files 
image

**Comment by YalinLi0312** [comment]
> CI failure caused by `azure-mgmt-containerregistry` is fixed. Current failure is caused by unconsistency of mindep between `setup.py` and `share_requirements.txt`. Please refer to https://github.com/Azure/azure-sdk-for-python/pull/25756/files image

Thanks for your quick response! @msyyc

**Pull request merged**
