### PR TITLE
[Blobs] Update special chars recording

### PR DESCRIPTION
**Pull request by rakshith91**
Latest version of urllib3 (1.25.5) encodes ~ as %7E. Recording needs to be updated 

EDIT: 
It seems like more than just updating a recording. Skipping the test and will fix in https://github.com/Azure/azure-sdk-for-python/issues/7407

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by scbedd** [comment]
Hey @rakshith91 can you take a look on the failures on this guy? This test has been failing the nightly build for the weekend now.

**Pull request merged**
