### PR TITLE
update usage for the adu deploy

### PR DESCRIPTION
**Pull request by danewalton**

### CODE REVIEW

**Comment by danewalton** [comment]
still relevant

**Comment by lmazuel** [comment]
Hi @danewalton sorry for the late answer.
Shouldn't the Python be updated as well?
https://github.com/Azure/azure-sdk-for-python/blob/ee31ef85d0d88116c71a294c2291444295b6515b/sdk/deviceupdate/azure-iot-deviceupdate/samples/DeployUpdate/sample_deploy_update.py#L41-L46

Did you executed this code to confirm it was working? Can you share the rationale for this.

Thanks!

**Comment by danewalton** [comment]
Yes let me go ahead and modify the sample as well.

We create a similar payload in our E2E tests with ADU here: https://github.com/Azure/azure-iot-middleware-freertos/blob/a5fdb049838668f2fbe100990d393a9f98202a4a/tests/e2e/adu/service/create_and_import_manifest.ps1#L171-L182

And it doesn't use the `update` wrapper object.

**Review by lmazuel — APPROVED** [review]
Sounds fair

**Pull request merged**
