### PR TITLE
InkRecognizer to use GA azure-core

### PR DESCRIPTION
**Pull request by lmazuel**

### CODE REVIEW

**Comment by xinyzhou** [comment]
The second commit from AutorestCI did some weird things, e.g. changing package name (sdk/cognitiveservices/azure-cognitiveservices-inkrecognizer/setup.py Line 16), changing filename to refer (sdk/cognitiveservices/azure-cognitiveservices-inkrecognizer/setup.py Line 24), create separate and incorrect readme (sdk/cognitiveservices/azure-cognitiveservices-inkrecognizer/Readme.rst), etc.

**Comment by lmazuel** [comment]
@xinyzhou yes you're right, the DevOps system pushed an incorrect auto-commit, I fixed it with a "push force" and disabled auto-commit system for this package. We should be good now :)

**Comment by xinyzhou** [comment]
@lmazuel Cool, thanks!

**Comment by lmazuel** [comment]
Merging, but no release planned at this time

**Pull request merged**
