### PR TITLE
Fix Content Safety Readme Issue

### PR DESCRIPTION
**Pull request by dotnet-7**
Fixes https://github.com/Azure/azure-sdk-for-python/issues/34059

@rohit-ganguly , @lmazuel , @JieZhou000 for notification.

### CODE REVIEW

**Review by v-xuto — APPROVED** [review]

**Comment by v-xuto** [comment]
@rohit-ganguly , @lmazuel , @JieZhou000 Could you help review this PR?

**Review by rohit-ganguly — APPROVED** [review]
Thanks for fixing this typo!

**Comment by v-xuto** [comment]
@rohit-ganguly Could you help merge this PR? Thanks a lot.

**Review by rohit-ganguly — APPROVED** [review]

**Comment by v-xuto** [comment]
@rohit-ganguly Could you help merge this PR? Thanks a lot.

**Pull request closed without merging**
