### PR TITLE
[bct] Fix module key error

### LINKED ISSUE #37307: [breaking change detector] fail to generate changelog for data-plane SDK `azure-ai-vision-face`
When  try to generate changelog for `azure-ai-vision-face` https://github.com/azure-sdk/azure-sdk-for-python/pull/8633, the following error happens:
```
(venv-dev) PS C:\dev\azure-sdk-for-python\sdk\face\azure-ai-vision-face> tox run -c ../../../eng/tox/tox.ini --root . -e breaking -- --changelong --latest-pypi-version
```
image

### PR DESCRIPTION
**Pull request by catalinaperalta**
Fixes #37307

### CODE REVIEW

**Comment by catalinaperalta** [comment]
@msyyc this is the fix for the issue you opened, feel free to merge if it looks good to you :)

**Comment by msyyc** [comment]
> @msyyc this is the fix for the issue you opened, feel free to merge if it looks good to you :)

Test the PR locally and it works as expected. Thanks for the quick response!

**Review by msyyc — APPROVED** [review]

**Pull request merged**
