### PR TITLE
Fix bug in multi-threaded error handling

### PR DESCRIPTION
**Pull request by bgklein**
@xingwu1 can you re-record the tests if necessary (added one call to confirm works). My dev_setup is failing due to cffi failing to build.

Edit: Will likely need to fiddle with sizes of the tasks as it looks like that test was silently failing due to bug

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by bgklein** [comment]
@xingwu1 or @matthchr Could one of you review? I managed to get the tests working locally for recordings

**Comment by bgklein** [comment]
@lmazuel good to merge/release

**Comment by bgklein** [comment]
Ping @lmazuel .

**Comment by lmazuel** [comment]
@bgklein sorry missed your ping the first time, sounds good to me :)

**Pull request merged**
