### PR TITLE
Add Log Analytics data plane SDK

### PR DESCRIPTION
**Pull request by alexeldeib**
Hi all! I'm introducing a new client to query Log Analytics (the operational insights resource provider in Azure). Tested out the SDK manually and it looks great, had a couple questions though!

- I saw the testing using stubbed management clients, is there an equivalent for data plane clients? or can I implement some testing using that framework and custom endpoints? I looked to KeyVault often as an example of a service slightly parallel our own -- custom endpoint, auth resource, etc, but they don't have tests? (after thinking about this some more, I misread the original code I think -- looks like I just need to new up a client).

- Due to swagger limitations we have one field of our response type that's modeled as a string (it's the type of the row value in the tables) but on the wire can actually be pretty much any primitive type: string, int, null, float/double, some datetime formats. In C# we are somewhat forced to deal with the strings but we have type information returned by the API to type them appropriately. I haven't tested this bit too closely, but will the python client respect the wire format, or actually use the attribute mappings to cast things to string?

[rest-api-specs spec](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/operationalinsights/data-plane/Microsoft.OperationalInsights/stable/v1/OperationalInsights.json)

### CODE REVIEW

**Comment by lmazuel** [comment]
Hi @alexeldeib !
Sorry for the late answer, I was in PyCon improving my Python last week :)

Most important here is that Python has no history to follow, so the mgmt package was release using the correct `loganalytics` branding.
https://pypi.org/project/azure-mgmt-loganalytics/#description

This has to be the same here, but overriding package name and title, like I did here:
https://github.com/Azure/azure-rest-api-specs/tree/master/specification/operationalinsights/resource-manager#python

Also, it seems to be not ARM, so the correct dependency will be "msrest" and not "msrestazure":
https://github.com/Azure/azure-sdk-for-python/blob/master/azure-servicefabric/setup.py#L80

To answer your questions now:
- The test framework is not tight to ARM, ARM is just a default. Documentation: https://github.com/Azure/azure-sdk-for-python/wiki/Contributing-to-the-tests
- Python is awesome, usually we can do anything we want :). I just don't have enough information to answer, could you show me some JSON example with the corresponding Swagger line?

Thanks!

**Comment by lmazuel** [comment]
Note, the `workspace_id` fix as to be done in the Swagger, change this line value to "method":
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/operationalinsights/data-plane/Microsoft.OperationalInsights/stable/v1/OperationalInsights.json#L131

**Comment by alexeldeib** [comment]
PyCon sounds exciting! Hope it was fun 👍 

I missed the management packages -- I'll change the naming to match. I'll also fix the dependency in setup.py. 

On the point about workspace ID, coincidentally I have a PR out with [that change](https://github.com/Azure/azure-rest-api-specs/pull/3084/files#diff-5068384c2d0c7a349dffd27ac8f5ae2cL131) 😄 I also updated the readme there for generation which (of course) produced [another PR](https://github.com/Azure/azure-sdk-for-python/pull/2568).

To the last bit about the string parameter: [this is the field](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/operationalinsights/data-plane/Microsoft.OperationalInsights/stable/v1/OperationalInsights.json#L238) in the swagger. I saw models all have code like this: 

```python
_attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'columns': {'key': 'columns', 'type': '[Column]'},
        'rows': {'key': 'rows', 'type': '[[str]]'},
    }
```

I had a chance to test this out and I see see that the python client does respect the string types in the swagger, converting the JSON type, e.g.: 

```
[
  u'OpsManager', 
  u'2018-04-08T12:27:10.86Z',
  u'00000000-0000-0000-0000-000000000001',
  u'40.83.215.18', 
  u'Direct Agent', 
  u'Windows', 
  u'', 
  u'10', 
  u'0', 
  u'8.0.11081.0', 
  u'Direct', 
  'False', 
  '-121.83',
  '37.32',
  u'United States', 
  u'microsoft.compute', 
  u'virtualmachines', 
  u'Azure', 
  u'"security", "serviceMap", "securityCenterFree"',
  u'Heartbeat'
]
```

For context, here's the JSON returned from the HTTP call (note the boolean and raw number values returned, converted to strings): 

<pre>
[
    "OpsManager",
    "2018-04-22T08:40:09.77Z",
    "00000000-0000-0000-0000-000000000001",
    "40.83.215.18",
    "Direct Agent",
    "Windows",
    "",
    "10",
    "0",
    "8.0.11081.0",
    "Direct",
    <b>false</b>,
    <b>-121.83,              # HERE </b>
    <b>37.32</b>,
    "United States",
    "microsoft.compute",
    "Azure",
    "\"security\", \"serviceMap\", \"securityCenterFree\"",
    "Heartbeat"
]
</pre>

Answering my own question -- the client will respect whatever is in the swagger. My follow up, then: we have the [information for column types](https://github.com/Azure/azure-sdk-for-python/pull/2557/files#diff-d7af4bc32d13ab67d2652cc2204d2c6bR28). Could I do some custom modeling to convert/cast the underlying values so they look right from the service perspective? For example, a value returned as a number in JSON will come back as a string but I would convert it back using the column.type field to determine type.  

We are returning rows from DB query, but due to restriction in swagger/autorest we can't model the value as multiple primitive types (yet!). So we ended up with string. I'm trying to work around that at the SDK level to provide a better experience. Curious what you think.

**Comment by lmazuel** [comment]
@alexeldeib Yes, we can do custom serialization/deserialization. But in this case, it seems I just have to not try to hard and expose what was on the JSON right? Could you confirm this is all basic types? For instance, there is not date in ISO8601 string your expect to be exposed as `datetime` object?

If this is just exposing bool/str/int/float, I can probably add an internal option in my runtime to say "Don't try serialize/deserialize". Example:
```python
_attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'columns': {'key': 'columns', 'type': '[Column]'},
        'rows': {'key': 'rows', 'type': '[[str]]', 'transform': False},
    }
```

Thoughts?

**Comment by alexeldeib** [comment]
Your proposal is the ideal. We really want to expose what the API brings back, because it "knows better" than the swagger. There are some ISO8601 format strings, but we are modeling these as strings in swagger anyway (due to format limitations), so this shouldn't present a problem python-side. 

BTW -- I'm waiting to move forward here until the swagger-side cleanup from the [above PR](https://github.com/Azure/azure-rest-api-specs/pull/3084) is complete. It includes the workspace_id => method parameter change, as well as some more general housekeeping.

**Comment by lmazuel** [comment]
@alexeldeib Swagger (at least Autorest, maybe there is subtle difference between Autorest and Swagger here) supports ISO8601, and we have automatic transformer for that.

You should need to use format "date-time" and on the SDK side you receive a date object ( `datetime` for Python). Example:
https://github.com/Azure/azure-rest-api-specs/blob/0bef2b99ad6d52781e3c308bc6b420f6eef59ef7/specification/apimanagement/resource-manager/Microsoft.ApiManagement/stable/2016-10-10/apimnetworkstatus.json#L105

**Comment by alexeldeib** [comment]
Side bar -- for the results, we're actually modeled just as string in swagger. This was the swagger/autorest limitation -- giving this a variety of type possibilities. So we landed on just making all the row results string in swagger. The comments about timestamps apply to parameters, but not results. 

So, what we found with C# was actually that date time worked fine, but that we didn't have good support for ISO8601 intervals, which we use (e.g. query timespan). Do you happen to know if that would work well in Python? A cursory search tells me the standard datetime objects can do durations but not intervals. I haven't played around this with the SDK, which would answer my question...but I figured you would know best 😄 

If it ends up that the intervals/durations work well, I'll add a transform in the swagger to include format: duration/format: interval (or the appropriate keywords, per your guidance) to the swaggers for client generation. I think for ISO8601 interval in particular we didn't find a good "format" keyword to feed autorest to get the desired result.

**Comment by alexeldeib** [comment]
@lmazuel The corresponding updates were merged in the specification repo, I regenerated and added a basic test case for usage. Functionally, from my end this is good to go. Let me know if you still see anything that wasn't covered.

One thing I noticed with the autorest configuration -- there is some weird behavior here. 
- If I try to override the title, namespace, and package name for python, the namespace and package name work. The title does not override. This looks like what you did with the resource-manager package, but it didn't work for me?
image
image

-  If I leave the global section empty, and only populate the per-language sections for Python, I get a client named "Azure Log Analytics"
image
image

- If I change the global title, Python uses it and generates "LogAnalyticsDataPlaneClient" as desired
image

Not sure what autorest is doing here, but it doesn't seem to respect the "title" override. For the time being, I manually generated the SDK with the global title "LogAnalyticsDataPlane" rather than "OperationalInsightsDataPlane". This is the [diff of the readme](https://github.com/azure/azure-rest-api-specs/compare/master...alexeldeib:pythonReadme) I used against master. This probably means the AutoPR's will be messed up, but I assume the autorest overrides won't work in other languages either. That may take some deeper investigation to resolve.

**Comment by lmazuel** [comment]
You're 100% right @alexeldeib we discovered that with @fearthecowboy recently. There is no way to make the override to work inside the Python section, it has to be moved into the global section.
Plan B would be to override the bot configuration for auto-PR, but this means manual generation won't have it. 
I will try to work with @fearthecowboy to find the correct Readme asap.
Thanks a lot for your work here!

**Comment by alexeldeib** [comment]
`override-client-name: <name>` seems to do the job. The title override seems to work but description still doesn't. I removed the description from the readme which forces Autorest to pull it out of the swagger itself -- that's accurate, at least 😄 

Here's the [readme diff](https://github.com/azure/azure-rest-api-specs/compare/master...alexeldeib:pythonReadme). 

The generated code is identical except for the description [[diff]](https://github.com/alexeldeib/azure-sdk-for-python/compare/loganalytics...alexeldeib:pythonReadmeFix) 
image

So I see three options:
- Keep the global description as "Operational Insights" and the python description as "Log Analytics". When autorest overrides for description work, you'll get an auto PR that fixes the single-line diff. 
- Remove global and Python level descriptions, allowing Autorest to pull from the swagger. Only downside here is the text now says "API", but circumvents the problem entirely. 
- Wait until this is fixed in autorest to merge at all.

Personally, I'd prefer to avoid option 3 -- it doesn't make sense to block on that single line description. I've gone with the second option for right now. If you think that's okay, I'll merge the corresponding readme diff into the spec repo. Or if you prefer the first option, I can make the change here and merge the corresponding readme change as well.

**Comment by lmazuel** [comment]
I like your diff, just want @fearthecowboy feedback on using `override-client-name` since I didn't this existed... Just want to be sure it's supported correctly (Autorest has some legacy and I want to avoid legacy stuff if possible)

**Comment by alexeldeib** [comment]
Sounds good, no problem to wait. I didn't know about this either 😄 I found it when I went to generate NodeJS library, someone did the same for Log Analytics/Operational Insights already: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/operationalinsights/resource-manager/readme.nodejs.md

**Comment by alexeldeib** [comment]
@fearthecowboy any comment on this?

**Comment by fearthecowboy** [comment]
I have no idea where `override-client-name` came from -- that looks like a last minute hack put in before we split out the generators. 

it does look like it's in the different generators, so you should be ok.

**Comment by alexeldeib** [comment]
Is there a preferred way to do the same transform otherwise? Definitely happy to avoid using a hack, if there is another approach.

**Comment by alexeldeib** [comment]
@lmazuel any thoughts on this? I looked at this in the generators and i'm fine with using it.

**Comment by lmazuel** [comment]
@alexeldeib I'm a little confused about the relation between this PR and https://github.com/Azure/azure-sdk-for-python/pull/2767? Should not one of them being closed?

**Comment by alexeldeib** [comment]
No, these are distinct. I'll follow up offline with some additional detail.

**Comment by alexeldeib** [comment]
@lmazuel Let me know if you see any other issues. Both this and https://github.com/Azure/azure-sdk-for-python/pull/2767 work smoothly now 👍

**Comment by alexeldeib** [comment]
Bump? 😊 @lmazuel

**Comment by alexeldeib** [comment]
Looks good to me! Thanks @lmazuel

**Comment by lmazuel** [comment]
Great! Let's release this guy :)

**Pull request merged**
