### PR TITLE
32565 Fix response validation error for reverse search address

### PR DESCRIPTION
**Pull request by Lakicar95**
# Description

For some coordinates, the server returns an array of strings, while for others, it returns an empty array for the route_numbers field. According to the documentation, the field should contain an array of strings, not an array of integers:

`"routeNumbers": {
          "description": "The codes used to unambiguously identify the street",
          "type": "array",
          "items": {
            "type": "string",
            "readOnly": true
          },
          "readOnly": true
        },`

This has been tested for multiple coordinates, including all those listed in the issue.

Resolves: https://github.com/Azure/azure-sdk-for-python/issues/32565

Note: _models_py3.py is no longer generated using autorest, but it's still used, therefore, all changes should be applied manually.

### CODE REVIEW

**Comment by kristapratico** [comment]
As discussed in https://github.com/Azure/azure-sdk-for-python/pull/34987, this change needs to be updated in the spec since we'll lose this fix upon next generation.

**Comment by Lakicar95** [comment]
> As discussed in #34987, this change needs to be updated in the spec since we'll lose this fix upon next generation.

@kristapratico I will put everything in this comment:
 Spec is already updated: https://github.com/Azure/azure-rest-api-specs/pull/17151
 Upon trying to regenerate new code described in this draft pr: https://github.com/Azure/azure-sdk-for-python/pull/35029 I managed to resolve the issue, but there is a lot of work to be done before fixing tests/everything..

**Review by kristapratico — APPROVED** [review]
Discussed offline. We'll merge this for now since the fix is already present in the spec and the team is working on migrating to typespec which will change the codegen anyway.

**Pull request merged**
