### PR TITLE
Fix quoting issue when deleting multiple blobs

### PR DESCRIPTION
**Pull request by malthe**
The blob name needs to be quoted.

See #10336 which has some discussion on why the blob name is quoted. This particular pull request doesn't try to address that issue, but just applies the same quoting as what's already present in the case of deleting a single blob.

### CODE REVIEW

**Comment by malthe** [comment]
I don't understand these test failures.

**Comment by xiafu-msft** [comment]
HI @malthe 
The fix has been merged into master, so can we please close this pr?

**Comment by malthe** [comment]
@xiafu-msft no because d9ce290a91abba6c65d557a2f539edde75e85bf9 hasn't been merged to master. In this PR I just cherry-picked the commit which you're referring to and then added another one which sort of builds on it.

**Comment by rakshith91** [comment]
@malthe `Can't overwrite existing cassette` means you will have to run the tests in live and need to update recordings.
also, you have a missing import in the async files

**Comment by malthe** [comment]
@rakshith91 sorry, how do I run the tests live?

I added the missing import to the async file – thanks for the keen eye!

**Comment by xiafu-msft** [comment]
Hi @malthe 

The quote fix has been released a couple of weeks ago, this pr is not necessary

**Comment by malthe** [comment]
Hi @xiafu-msft – as I mentioned in an earlier comment, there is still an open issue which is solved by this PR. Please examine for yourself the contents of 0a3c4e81e3adfe72a2edd757b5925d359a3e548d and compare with the master branch.

**Comment by xiafu-msft** [comment]
> Hi @xiafu-msft – as I mentioned in an earlier comment, there is still an open issue which is solved by this PR. Please examine for yourself the contents of [0a3c4e8](https://github.com/Azure/azure-sdk-for-python/commit/0a3c4e81e3adfe72a2edd757b5925d359a3e548d) and compare with the master branch.

Thanks for looking into the details! I responded inline

**Comment by malthe** [comment]
@xiafu-msft please see my [inline comment](https://github.com/Azure/azure-sdk-for-python/commit/0a3c4e81e3adfe72a2edd757b5925d359a3e548d#r39467273).

**Comment by xiafu-msft** [comment]
Hi @malthe 

https://github.com/Azure/azure-sdk-for-python/pull/11802 will fix this problem! It should be released before the end of this week!

Thanks again for catching this

**Comment by malthe** [comment]
Closing this PR since the issue will be fixed elsewhere.

**Pull request closed without merging**
