### PR TITLE
Get successful MyPy pass for azure-core

### LINKED ISSUE #5022: [azure-core]Need successful MyPy pass
In moving code between msrest and azure-core, most of the type-hinting statements have been broken or left in an incomplete state. These need to be fixed and completed.

### PR DESCRIPTION
**Pull request by rakshith91**
Resolves #5022

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by bryevdv** [comment]
@rakshith91 I am actually extremely new to MyPy, had been waiting to learn about it until later this year  when other projects I run move to Python 3.5+. So you can help me understand a few things as I come up to speed:

* In general (not just this PR) I see a lot of complex types inline in code in lots of places, e.g `List[Union[HTTPPolicy, SansIOHTTPPolicy]]` Should/could we define type aliases more aggressively?

* also seeing more `type: ignore` on things like imports than I might naively expect to need. Are these temporary, and could be removed later as more modules are updated for mypy?

**Comment by rakshith91** [comment]
> @rakshith91 I am actually extremely new to MyPy, had been waiting to learn about it until later this year when other projects I run move to Python 3.5+. So you can help me understand a few things as I come up to speed:
> 
> * In general (not just this PR) I see a lot of complex types inline in code in lots of places, e.g `List[Union[HTTPPolicy, SansIOHTTPPolicy]]` Should/could we define type aliases more aggressively?
> * also seeing more `type: ignore` on things like imports than I might naively expect to need. Are these temporary, and could be removed later as more modules are updated for mypy?

@bryevdv 
1) AFAIK, I don't think it's possible to define type aliases more aggressively. I can look more into it.

2) Those imports don't have stubs in [typeshed](https://github.com/python/typeshed/). Writing our own stubs for 3rd party libraries would definitely be overkill. One alternative is we can ignore these in the command line arguments while setting it up in the CI and then remove these magic comments or wait till typeshed supports these libraries.

**Comment by bryevdv** [comment]
@rakshith91 

By type more aggressively define type aliases, I mean only use this functionality more than we currently do: https://mypy.readthedocs.io/en/latest/kinds_of_types.html#type-aliases

So, in the specific case above,  maybe: `PolicesList = List[Union[HTTPPolicy, SansIOHTTPPolicy]]` so that then we can use `PoliciesList` in place of the complicated expression in the actual code. 

Thanks for the explanation re: typeshed, personally I think judiciously turning off some checks for certain things is useful (I wouldn't want to have to add some noisy comment just to import `urllib`) but that might be something for a wider discussion.

**Comment by rakshith91** [comment]
Moved to #5466 

Closing this as a duplicate.

**Pull request closed without merging**
