### PR TITLE
[Service Bus] Deprecate Internal _Accesstoken

### LINKED ISSUE #13638: [ServiceBus] Deprecate historical _AccessToken workaround now that AccessToken is imported from core.
**Is your feature request related to a problem? Please describe.**
We previously used _AccessToken to work around not needing to import AccessToken.  However, we're now importing AccessToken from azure.core anyway to implement other credentials, so we might as well nix the custom standin.

**Describe the solution you'd like**
Convert instances of _AccessToken to use AccessToken instead, then remove _AccessToken.

**Describe alternatives you've considered**
N/A

**Additional context**
This originated in [the discussion here.](https://github.com/Azure/azure-sdk-for-python/pull/13627#discussion_r485179684)
(Note: since this is internal, my use of the word "Deprecate" is colloquial, there is no additional process outside of simply yanking out the old utilization and making sure everything is still happy/tests pass.)

### PR DESCRIPTION
**Pull request by egelfand**
Replaced references to internal _Accesstoken with the Accesstoken itself, now that its available. Closes #13638.

### CODE REVIEW

**Comment by KieranBrantnerMagee** [comment]
I don't know if you're able to view the CI output so I've pasted the current exception below, should be a simple fix (just addressing the async import for this same stanza) otherwise this approach looks solid.

`
ImportError while importing test module '/home/vsts/work/1/s/sdk/servicebus/azure-servicebus/tests/async_tests/test_sessions_async.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/async_tests/test_sessions_async.py:17: in <module>
    from azure.servicebus.aio import ServiceBusClient, ReceivedMessage, AutoLockRenew
azure/servicebus/aio/__init__.py:7: in <module>
    from ._servicebus_sender_async import ServiceBusSender
azure/servicebus/aio/_servicebus_sender_async.py:14: in <module>
    from ._base_handler_async import BaseHandler
azure/servicebus/aio/_base_handler_async.py:17: in <module>
    from .._base_handler import _generate_sas_token, _AccessToken, BaseHandler as BaseHandlerSync
E   ImportError: cannot import name '_AccessToken' from 'azure.servicebus._base_handler' (/home/vsts/work/1/s/sdk/servicebus/azure-servicebus/azure/servicebus/_base_handler.py)
`

**Comment by yunhaoling** [comment]
hey @egelfand , thanks for the PR :) we're very close to merging it with just three minor mypy/pylint issue:

mypy is reporting:
```
azure/servicebus/_base_handler.py:96: error: Name '_AccessToken' is not defined
azure/servicebus/_base_handler.py:150: error: Name '_AccessToken' is not defined
```

action: `_AccessToken` ->  `AccessToken`

pylint is reporting:
```
azure/servicebus/_base_handler.py:5: [W0611(unused-import), ] Unused import collections
```

action: we could simply remove the import

**Comment by yunhaoling** [comment]
hey @egelfand, your PR looks good to me, could you sign the agreement mentioned by microsoft-cla:
https://github.com/Azure/azure-sdk-for-python/pull/14450#issuecomment-717520097

so that we could merge your PR.

**Comment by egelfand** [comment]
Just did so, thanks for all of your help!

**Review by yunhaoling — APPROVED** [review]
thanks for the contribution!

**Pull request merged**
