### PR TITLE
[Communication]: Added unit tests to check if idempotence parameters are being set

### PR DESCRIPTION
**Pull request by lsundaralingam**

### CODE REVIEW

**Comment by beltr0n** [comment]
These are good, but is there a way to test the repeatabilityResponse coming back from the server as well? that's what we're testing in Java/.Net/JS

**Comment by lsundaralingam** [comment]
> These are good, but is there a way to test the repeatabilityResponse coming back from the server as well? that's what we're testing in Java/.Net/JS

There doesn't seem to be way in Python to get the raw HTTP response back in the live tests like we do for the other languages, butI don't see anything that we're missing here in terms of test coverage. We have live tests that would fail if there's something wrong with the repeatabilityResponse and we have these tests to ensure that the parameters are being set.

**Review by beltr0n — APPROVED** [review]

**Review by jbeauregardb — APPROVED** [review]

**Pull request merged**
