### PR TITLE
edit all authentication files and add a test

### PR DESCRIPTION
**Pull request by xiafu-msft**

### CODE REVIEW

**Comment by aviramha** [comment]
I was removed as an author 😢

**Comment by xiafu-msft** [comment]
@aviramha sorry that I should have gave you a heads up that I didn't merge your pr, and thanks for the commit! 
I didn't merge your PR because at that time the CI in your PR failed https://github.com/Azure/azure-sdk-for-python/pull/13346, and I wasn't sure what caused the failure, plus I added a commit to your PR and I was worried my change broke the CI, so I created a new PR to play around with. (If I use your PR to play around you will get a lot of notifications)
Finally it turned out that the changes in our dependency, and the CI failure was blocking other people's pr, so once I got the approval I didn't think too much and merged the fix.

**Comment by aviramha** [comment]
Hmm it's a bit tricky but you could rebase and amend author for the commit
https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit

**Comment by xiafu-msft** [comment]
@aviramha I've partially reverted the commit and merged it to master.
You can rebase against master and we will merge your pr later

**Comment by aviramha** [comment]
@xiafu-msft Thanks, I really appreciate it. Sorry for being "annoying" :)

**Comment by xiafu-msft** [comment]
@aviramha for sure. Not at all, I should have noticed that, thanks for your understanding!

**Pull request merged**
