### PR TITLE
Trigger template instead of core for eng/common

### PR DESCRIPTION
**Pull request by sima-zhu**
# Description

Please add an informative description that covers that changes made by the pull request and link all relevant issues.

**Current workflow for eng work:**
For work under `eng/common` like PR: https://github.com/Azure/azure-sdk-tools/pull/2861.

It will trigger 9 PRs like below:
image

For PR to lang repo, they trigger core pipeline for testing the changes. Like sync PR here: https://github.com/Azure/azure-sdk-for-python/pull/23507

Java has switched to template already and run for a while. The PR is to align with Java trigger branch and path.
If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [ ] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by benbp** [comment]
Are you planning on doing c, c++, android, ios and go as well? I think this will be a great improvement, but am trying to think if there's any important coverage we may be losing.

**Review by benbp — APPROVED** [review]

**Review by weshaggard — APPROVED** [review]

**Review by scbedd — APPROVED** [review]
🚀 🚀 🚀 🚀

**Review by lmazuel — APPROVED** [review]
LGTM

**Pull request merged**
