### PR TITLE
[metricsadvisor] shorten recording names

### PR DESCRIPTION
**Pull request by kristapratico**
@swathipil is seeing "Filename too long" for these files when trying to pull the latest main

### CODE REVIEW

**Review by xiangyan99 — COMMENTED** [review]
why only async tests?

**Review by swathipil — APPROVED** [review]
LGTM!

**Comment by kristapratico** [comment]
> why only async tests?

The async paths are longer.

This is the error she is seeing:

> error: cannot stat 'sdk/metricsadvisor/azure-ai-metricsadvisor/tests/recordings/async_tests/test_detection_config_async.pyTestMetricsAdvisorAdministrationClientAsynctest_update_detection_config_with_model_and_kwargs[APIKey].json': Filename too long

**Comment by xiangyan99** [comment]
> > why only async tests?
> 
> The async paths are longer.
> 
> This is the error she is seeing:
> 
> > error: cannot stat 'sdk/metricsadvisor/azure-ai-metricsadvisor/tests/recordings/async_tests/test_detection_config_async.pyTestMetricsAdvisorAdministrationClientAsynctest_update_detection_config_with_model_and_kwargs[APIKey].json': Filename too long

How about making sync/async test names consistent?

**Comment by kristapratico** [comment]
> > > why only async tests?
> > 
> > 
> > The async paths are longer.
> > This is the error she is seeing:
> > > error: cannot stat 'sdk/metricsadvisor/azure-ai-metricsadvisor/tests/recordings/async_tests/test_detection_config_async.pyTestMetricsAdvisorAdministrationClientAsynctest_update_detection_config_with_model_and_kwargs[APIKey].json': Filename too long
> 
> How about making sync/async test names consistent?

Sure, I can do that!

**Review by xiangyan99 — APPROVED** [review]

**Pull request merged**
