### PR TITLE
FIx comment for lab services client enums

### PR DESCRIPTION
**Pull request by ianhays**
PTAL: @dendeli-msft @lmazuel

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by dendeli-msft** [comment]
LGTM from a docs perspective.

**Comment by ianhays** [comment]
Thanks @dendeli-msft, feel free to merge whenever.

**Pull request merged**
