### PR TITLE
[Cosmos] Added HttpLoggingPolicy to pipeline

### PR DESCRIPTION
**Pull request by annatisch**
Resolves issue #8309 
Also cleans up some old files in the repo and fixed some deprecation warnings in the tests.
Some test files have been renamed to be in keeping with pytest convention.

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by annatisch** [comment]
Need to investigate if this is needed. If so, will rebase and reopen.

**Comment by annatisch** [comment]
Looks like this is still needed - not sure why it wasn't merged before.
Will fix the conflicts.

**Comment by annatisch** [comment]
Reopened as #10295

**Pull request closed without merging**
