### PR TITLE
Change content type to application/octet-stream

### PR DESCRIPTION
**Pull request by briglx**
detect_image was using multipart/form-data when it should be application/octet-stream.

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by briglx** [comment]
Any update on this?

**Comment by lmazuel** [comment]
@areddish should this be a Swagger fix?

**Comment by areddish** [comment]
@lmazuel We allow both in the swagger as our endpoint consumes both types. It looks like autorest defaults to multi-part if present.

**Comment by lmazuel** [comment]
@areddish Autorest will use the first one in the list of "consumes", unless there is one that contains "json" then it will use this one.
If that's a problem for you, might deserve an autorest issue "feature request"

**Comment by areddish** [comment]
Ah, we've been supporting both for awhile so there's no issue on our side. REST clients can send either and SDK clients have been sending multi-part.

Also this change isn't changing the code to the autorest template for octet-stream, it's overloading the form param to send a binary body. So this should not be accepted. These types of changes should all be driven from swagger thru autorest.

**Comment by lmazuel** [comment]
@areddish I agree, all changes must come from Swagger.
However, my point was if you would want SDK to support both, then it would require an autorest change. If you don't care as long at least one of them is supported, then that's fine.

@briglx I'm closing your PR since:
1- Changes would be in the generator that creates this code, not the code itself
2- We are not even sure the change is needed, since multipart or form works equally

If you have a scenario where it's not working as expected, please open an issue to describe the problem you have, so we can plan a feature request or anything to fix your scenario.
Thank you for the contribution!

**Pull request closed without merging**
