### PR TITLE
Update release date for core

### PR DESCRIPTION
**Pull request by xiangyan99**

### CODE REVIEW

**Review by kashifkhan — APPROVED** [review]

**Comment by kashifkhan** [comment]
`macoslatest_pypy39_azureidentityazurekeyvaultkeysazuremgmtcomputeazuremgmtcoreazureservicebusazurest` - this has to be an error ?

**Comment by xiangyan99** [comment]
Per the error message:

Traceback (most recent call last):
  File "/Users/runner/work/1/s/scripts/devops_tasks/use_pypy_version.py", line 85, in <module>
    discovered_installer_location = find_pypy_version(version_from_spec)
  File "/Users/runner/work/1/s/scripts/devops_tasks/use_pypy_version.py", line 52, in find_pypy_version
    discovered_locations = walk_directory_for_pattern(spec)
  File "/Users/runner/work/1/s/scripts/devops_tasks/use_pypy_version.py", line 22, in walk_directory_for_pattern
    discovered_tool_folders = os.listdir(pypy_tool_cache)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/runner/hostedtoolcache/PyPy'

It is a pipeline error.

**Comment by scbedd** [comment]
> Per the error message:
> 
> Traceback (most recent call last): File "/Users/runner/work/1/s/scripts/devops_tasks/use_pypy_version.py", line 85, in discovered_installer_location = find_pypy_version(version_from_spec) File "/Users/runner/work/1/s/scripts/devops_tasks/use_pypy_version.py", line 52, in find_pypy_version discovered_locations = walk_directory_for_pattern(spec) File "/Users/runner/work/1/s/scripts/devops_tasks/use_pypy_version.py", line 22, in walk_directory_for_pattern discovered_tool_folders = os.listdir(pypy_tool_cache) FileNotFoundError: [Errno 2] No such file or directory: '/Users/runner/hostedtoolcache/PyPy'
> 
> It is a pipeline error.

Yeah this popped up yesterday due to agent changes on the macos agent. I'm working on a solution, feel free to check-enforcer ignore.

**Pull request merged**
