### PR TITLE
[pylint checker] Checker for dependency version changes

### PR DESCRIPTION
**Pull request by kristapratico**

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by Petermarcu** [comment]
@kristapratico does this still need to go in?

**Comment by kristapratico** [comment]
@xiangyan99 I know you requested this awhile ago, is this still something we want pylint to check?

**Comment by lmazuel** [comment]
After thinking about this, pylint is not designed to check setup.py (I made a few attempt of invalid setup.py, and pylint escapes the question, but if I rename to another name, suddenly it finds issues...). I guess it explains why the code here is complex, and read the code manually with an "open" (which is hacking the pylint parser).

If we ever want to do this, I would suggest to do that on the CI side, since we have the tooling now to parse the setup.py and there is checks there already.

Conclusion: closing not on the idea itself, but on the implementation to do it should not use pylint

**Pull request closed without merging**
