### PR TITLE
[CognitiveLanguage] update samples to use asyncio.run

### PR DESCRIPTION
**Pull request by wonhyeongseo**
# Description

As https://github.com/Azure/azure-sdk-for-python/issues/21207 mentions, some samples are using a loop variable for simple callbacks when this can be done by using the new run method of asyncio. This PR remedies the issue for the cognitive-language library.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Review by kristapratico — COMMENTED** [review]
Hey @wonhyeongseo thanks for your contribution! This looks good to me, but I noticed in CI pipeline that it's failing because it detected a misspelled word in one of the samples. I'm not sure why this wasn't caught by cspell before on your other PR, but would you mind fixing it here so the PR will be green? Looks like it's failing on "occured" here: https://github.com/Azure/azure-sdk-for-python/blob/9c8a7e037a0f6bdfe9b782faa19cf51a18b2e85b/sdk/cognitivelanguage/azure-ai-language-conversations/samples/async/sample_conv_pii_transcript_input_async.py#L103

**Comment by wonhyeongseo** [comment]
Woopshie, sorry missed your message about running the pipeline. I am looking into why local cspell didn't pick up that typo. Nice to meet you again, Krista! Happy thanks giving from Korea 🦃

**Comment by kristapratico** [comment]
> Woopshie, sorry missed your message about running the pipeline. I am looking into why local cspell didn't pick up that typo. Nice to meet you again, Krista! Happy thanks giving from Korea 🦃

No worries! It's running here: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1838584&view=results

Happy Thanksgiving! Hope you're enjoying the holiday.

**Review by kristapratico — APPROVED** [review]

**Pull request merged**
