### PR TITLE
Revert changes to disable apistubgen

### PR DESCRIPTION
**Pull request by praveenkuttappan**
Revert temporary change to disable apistubgen and create stub file for packages.

### CODE REVIEW

**Comment by praveenkuttappan** [comment]
@scbedd Travis has merged fix in api stub generator to resolve issue we were getting earlier for azure-core-tracing-opencensus package. This PS is to revert my temporary change to disable api stub generator.

**Review by tjprescott — APPROVED** [review]

**Comment by tjprescott** [comment]
Does the fact that this passed mean that when it's merged things won't be broken?

**Comment by tjprescott** [comment]
@praveenkuttappan sorry I broke this. Here's the fix: https://github.com/Azure/azure-sdk-tools/pull/2763

**Pull request closed without merging**
