### PR TITLE
[DO NOT MERGE]update doc tool

### PR DESCRIPTION
**Pull request by xiangyan99**
This is a tool to parse rst file and update module/package names with better look

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by scbedd** [comment]
@bryevdv @lmazuel you're both right. Sphinx extension is definitely the way to go here.

I was having a conversation with Mayuri about this as well. If we publish our own sphinx extension that adjusts the `api-doc` output to match what we want, that is a very easy integration point with _their_ doc gen as well. It's much easier to conditionally use a sphinx extension then add new configuration to their builds :)

**Comment by bryevdv** [comment]
FWIW I have a fair amount of experience creating Sphinx extensions so please let me know if there is anything I can do to help.

**Comment by lmazuel** [comment]
Closing the PR since:
- The way the TOC is defined nowadays is entirely different, and then there is no problem of left TOC:
image

The "dot" syntax only appears in the individual TOC, where it's actually not a problem:
image

- As discussed, if we ever want to do it, we should consider to embed that as a Sphinx extension anyway, and then re-do the PR

Anyway, nothing is lost in Github, we can easily resurrect this code if necessary, the PR doesn't *need* to stay open.

**Pull request closed without merging**
