### PR TITLE
resolveFewCommentsForChangeFeedChange

### PR DESCRIPTION
**Pull request by xinlian12**
- For read_feed_ranges in aio package, change return type of `Iterable` -> `AsyncIterable`
- For the changeFeedMode in the changeFeed continuation, change from `Incremental` -> `LatestVersion`

### CODE REVIEW

**Review by tvaron3 — APPROVED** [review]
LGTM

**Review by FabianMeiswinkel — APPROVED** [review]
LGTM thanks!

**Comment by xinlian12** [comment]
Pipeline timed out, not caused by changes in this PR

**Pull request merged**
