### PR TITLE
Solved Bing Search API "Resource Not Found" error

### PR DESCRIPTION
**Pull request by lorenzobalzani**
# Description
I solved [this issue](https://learn.microsoft.com/en-us/answers/questions/173628/bing-search-api-returns-the-resource-not-found-err). I just changed `url = self._client.format_url(url, **path_format_arguments)` to `url = path_format_arguments['Endpoint']` and the problem has been resolved. 

# All SDK Contribution checklist:
- [X] **The pull request does not introduce [breaking changes]**
- [X] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [X] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [X] Title of the pull request is clear and informative.
- [X] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by kristapratico** [comment]
@lorenzobalzani thanks for looking into this. The code in this PR is auto-generated (you can tell by the header at the top of the file) and so we cannot edit it directly since it will be overwritten the next time the code is generated. Adding @msyyc to comment on if this fix is needed in the generator to address the issue.

**Comment by lorenzobalzani** [comment]
@msyyc

**Comment by msyyc** [comment]
@kristapratico According to github history, the code was generated several years ago and not updated for 5 years. I feel OK for this fix.

**Comment by kristapratico** [comment]
@lorenzobalzani I'm trying to understand the fix - is it the /bing/ in the path that's the problem? Looking [here](https://learn.microsoft.com/en-us/bing/search-apis/bing-web-search/bing-web-upgrade-guide-v5-to-v7#endpoints) it seems like we should be building the URL as `https://api.bing.microsoft.com/v7.0/search`. I want to make sure that if we accept a manual change, it doesn't require the user to pass in the full URL as `endpoint=https://api.bing.microsoft.com/v7.0/search` (as that's inconsistent with how all other Azure client libraries work). 

Would removing `/bing` on this line fix the issue?

https://github.com/Azure/azure-sdk-for-python/blob/89fb20c33835d99e665e4a8c5ba9ed6ed1c7c8fa/sdk/cognitiveservices/azure-cognitiveservices-search-websearch/azure/cognitiveservices/search/websearch/_configuration.py#L38

I think this change would be preferable since it would allow for a client to still be created like:

client = WebSearchClient(endpoint="https://api.bing.microsoft.com", credentials="apiKey")

**Comment by kristapratico** [comment]
@lorenzobalzani I followed up on this and unfortunately this library is deprecated and so we won't be making any code changes or releases in the future. Apologize for the inconvenience.

**Pull request closed without merging**
