### PR TITLE
Use b"" instead of bytes(). Don't use str on a string.

### PR DESCRIPTION
**Pull request by atombrella**
# Description

https://docs.astral.sh/ruff/rules/native-literals/

Fixed using
```sh
ruff check --exclude="script*" --exclude="tools*" --select "UP018" --fix
```

Performance improvements:
```
In [1]: %timeit b""
6.85 ns ± 0.222 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)

In [2]: %timeit bytes()
41.1 ns ± 0.245 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)

In [3]: %timeit "Azure"
6.75 ns ± 0.037 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)

In [4]: %timeit str("Azure")
25.8 ns ± 0.124 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
```

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [ ] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by l0lawrence** [comment]
Hi @atombrella thank you for the pr! For SB/EH this looks good to me

The CI failures seem to be pre-existing failures in the confidential-ledger pipeline.

**Review by kashifkhan — APPROVED** [review]

**Comment by atombrella** [comment]
@l0lawrence @kashifkhan Just to remind you, I do not have merge rights

**Review by vincenttran-msft — COMMENTED** [review]
LGTM for Storage side in regards to `bytes()` -> `b""`, thanks for this!

**Review by kristapratico — APPROVED** [review]
Thanks @atombrella! This looks good to me

**Comment by kristapratico** [comment]
/check-enforcer override

Pylint failure in confidential ledger is unrelated

**Pull request merged**
