### PR TITLE
[formrecognizer] add testcases for labeled tables - fixed/variable rows

### PR DESCRIPTION
**Pull request by kristapratico**

### CODE REVIEW

**Review by iscai-msft — APPROVED** [review]

**Review by catalinaperalta — APPROVED** [review]
LGTM! My only nit would be that `formrecognizer_label_table_variable_rows_storage_container_sas_url` is super long, but I dont see how to shorten it unless we use shorter versions of the words themselves. It's still fine if you merge it as is though.

**Comment by kristapratico** [comment]
> LGTM! My only nit would be that formrecognizer_label_table_variable_rows_storage_container_sas_url is super long, but I dont see how to shorten it unless we use shorter versions of the words themselves. It's still fine if you merge it as is though.

I could drop the "label" and "storage" part? formrecognizer_table_variable_rows_container_sas_url

**Comment by catalinaperalta** [comment]
> I could drop the "label" and "storage" part? formrecognizer_table_variable_rows_container_sas_url
Yeah that works for me! The name still seems pretty clear to me without those words. I like it 👍

**Review by maririos — APPROVED** [review]
Thank you!

**Pull request merged**
