### PR TITLE
[Communication] - Chat - Bug: Fixed chat tests issue token renaming issue

### PR DESCRIPTION
**Pull request by jbeauregardb**

### CODE REVIEW

**Comment by lsundaralingam** [comment]
Looks good, could u also run the live tests?

**Comment by sacheu** [comment]
Do you need to run the E2E tests there were mentioned in the thread in the Chat team channel?

**Review by sacheu — APPROVED** [review]
LGTM.

**Review by RezaJooyandeh — APPROVED** [review]

**Review by minnieliu — APPROVED** [review]

**Review by lsundaralingam — APPROVED** [review]

**Pull request merged**
