### PR TITLE
Add a flag to allow the analyze-deps script to export dependency data

### PR DESCRIPTION
**Pull request by bsiegel**
The data is exported in a format that will be consumed by the client side dependency graph (currently available in Azure/azure-sdk-tools#278)

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by bsiegel** [comment]
https://gist.githack.com/bsiegel/89047bb3b914073fdb62026eacd5038b/raw/a5d28c16cdaee7a61b1995135a0e78152f651f06/index.html?data=python.js

**Comment by bsiegel** [comment]
> I'd like to understand why we are fine with including management libraries in the html report, but not in the data.

The main reason was for usability. With the management libs the graph gets HUGE and hard to see / navigate. We could just exclude them from both the report and the graph if the team is fine with that.

**Pull request merged**
