### PR TITLE
creating custom sphinx sources that reflect the documentation that azure-cosmos wants to show

### PR DESCRIPTION
**Pull request by scbedd**
This should end up generating the same (different skin of course) content for our greater `all docs` build that the cosmos team has specified in their project specific doc/ folder.

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by bryevdv** [comment]
@scbedd there are some things in here there AFAIK the cosmos team would rather just have hidden completely (`consistent_hash_ring` as one example) Should I just open a new PR against this current approach, or are things expected to change in any way soon?

**Comment by scbedd** [comment]
I generated these sphinx sources using the method described in `sdk/cosmos/azure-cosmos/doc/index.rst`, then made certain that the ToC for azure-cosmos that I have is the same as the ToC that shows for the cosmos-specific site.

If we want to hide consistent_hash_ring, we totally can, but that is NOT what currently happens with site generated from within the azure-cosmos doc folder.

Build process: 
image

Screenshot from site: 
image

I am glad to adjust, but I confirmed that I don't show anything that doesn't show on the azure-cosmos specific sphinx site (in my understanding at least).

**Comment by bryevdv** [comment]
> Can you show me what you do differently to gen the site? 

Do you mean the files in https://github.com/Azure/azure-sdk-for-python/pull/6232/files ? I created those by hand. AFAIK that's about all that Chris would like to be shown (i.e. no big ToC at the top linking to things users will not need to see)

**Pull request merged**
