### PR TITLE
[EventHub] fix pylint plugin errors

### PR DESCRIPTION
**Pull request by swathipil**
fix new pylint rules:
- C4747: enum-must-inherit-case-insensitive-enum-meta
- C4748: client-accepts-api-version-keyword

### CODE REVIEW

**Review by kristapratico — APPROVED** [review]

**Comment by l0lawrence** [comment]
azure/eventhub/_consumer_client.py:34: [E0012(bad-option-value), ] Bad option value 'client-accepts-api-version-keyword'
 This is popping up b/c that specific checker doesn't exist yet in main, once it is merged you can #pylint: disable

**Pull request merged**
