### PR TITLE
Fixing the test and increment version

### PR DESCRIPTION
**Pull request by chiragg4u**
Changes for publishing the GA version of the SDK using the new version being published.

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by chiragg4u** [comment]
@demyanenko can you please review from PG team.

**Comment by chiragg4u** [comment]
Closing this PR as we'd another older PR; I'll fix the test in that branch and push the changes.

**Pull request closed without merging**
