### PR TITLE
Azure Backup version 2019-05-13 update

### PR DESCRIPTION
**Pull request by SanjayHukumRana**

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by pvrk** [comment]
@zikalino :
Just want to provide an update on the importance of this one.

We made an announcement of [API version deprecation](https://azure.microsoft.com/updates/recovery-services-rest-api-version-deprecation-notice/) to customers but realized that the python SDK has to be published to point to the latest API. We already got double-digit support cases overall and the customers have no way out since the older SDKs do not point to the latest API versions.
So, request you to kindly do whatever is required to expedite the release of this SDK.

**Comment by pvrk** [comment]
@zikalino : Can you please acknowledge/respond to the request? This is very important for us to get the SDK out as soon as possible.

**Comment by zikalino** [comment]
closing this pr. i think this was probably already released with different pr.
if not, please submit appropriate release request.

**Pull request closed without merging**
