### PR TITLE
[SchemaRegistry] add avroserializer package back for deprecation

### PR DESCRIPTION
**Pull request by swathipil**
Adding back the azure-schemaregistry-avroserializer package for deprecation and documentation purposes.

Related to: #23057

### CODE REVIEW

**Review by scbedd — APPROVED** [review]
Approving this. We probably should add the artifact to the artifact list in `schemaregistry/ci.yml`, but frankly it doesn't really matter as this won't release successfully anyway due to the `.post1` version suffix.

**Comment by scbedd** [comment]
Well I wasn't expecting that failure! I guess revert? I'll manually release this sometime today.

**Comment by swathipil** [comment]
Sounds good - will remove it from artifacts in ci.yml, then merge. Thanks @scbedd!

**Comment by scbedd** [comment]
> Sounds good - will remove it from artifacts in ci.yml, then merge. Thanks @scbedd!

I'm sorry for the revs @swathipil 😞 . Honestly didn't anticipate the error there.

**Comment by swathipil** [comment]
no worries at all! @scbedd I actually felt that the process was going _too_ smoothly, so glad to see things being righted 🙂

**Pull request merged**
