### PR TITLE
Add license files consistently for all packages

### PR DESCRIPTION
**Pull request by major**
Ensure each python package uploaded to pypi contains a `LICENSE.txt`
file along with an `include` line in the `MANIFEST.in`.

Related to azure/azure-cli#17909

### CODE REVIEW

**Review by LarryOsterman — APPROVED** [review]
Attestation looks fine. Thank you very much.

**Comment by major** [comment]
> Attestation looks fine. Thank you very much.

Thanks! This helps a bunch for Fedora RPM packaging! 🎉

**Comment by major** [comment]
I just rebased this PR since it was pretty far behind the `main` branch.

**Review by LarryOsterman — APPROVED** [review]
Attestation looks fine.

**Comment by major** [comment]
Closing in favor of #20193 instead.

**Pull request closed without merging**
