### PR TITLE
updating generated code

### PR DESCRIPTION
**Pull request by seankane-msft**

### CODE REVIEW

**Comment by xiangyan99** [comment]
Did you generate the code with credential support?

**Comment by seankane-msft** [comment]
> Did you generate the code with credential support?

No, we should discuss this later. Does the appconfig generated code need to be updated? I only discovered the discrepancies while working on [this](https://github.com/Azure/azure-sdk-for-python/pull/16667) PR.

**Comment by xiangyan99** [comment]
try add --add-credentials in your autorest command and let's see the difference. :)

**Review by xiangyan99 — APPROVED** [review]

**Pull request merged**
