### PR TITLE
Only create temporary folder if local storage is enabled without storage directory

### LINKED ISSUE #33962: Unable to use azure.monitor.opentelemetry.configure_azure_monitor on read only file system
- **Package Name**: azure-monitor-opentelemetry
- **Package Version**: 1.1.1
- **Operating System**: python:3.8.18-slim docker image
- **Python Version**: Python 3.8.18

**Describe the bug**
The `azure.monitor.opentelemetry.configure_azure_monitor` triggers the creation of a temp directory even though I configured `disable_offline_storage` to be `True`

**To Reproduce**
1. Configure container file system to be read only
2. Start Python script by call `configure_azure_monitor` with `disable_offline_storage=True`

**Expected behavior**
Only create the temp storage directory when `disable_offline_storage=False`

**Screenshots**
image

**Additional context**
image

### PR DESCRIPTION
**Pull request by jeremydvoss**
# Description

Fixes #33962

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [x] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by yli02** [comment]
Hi @jeremydvoss, thanks for the quick bug fix.

Hi @lmazuel, @lzchen and @hectorhdzg, may I ask when could I expect a newer version will be released? I have currently a pending task in my project that I could proceed further due to this bug, therefore, would like to get an approximate date for the new release. Thanks a lot.

**Review by lzchen — APPROVED** [review]

**Comment by yli02** [comment]
@jeremydvoss sorry for disturbing you frequently. May I ask whether a newer version could be released this week? Thanks.

**Comment by lzchen** [comment]
@yli02 

We will have this version released by the end of this week.

**Comment by yli02** [comment]
@lzchen thanks.

**Pull request merged**
