### PR TITLE
Add skip_token parameter at costmanagement.query.usage()

### PR DESCRIPTION
**Pull request by ImMin5**
# Description

Please add an informative description that covers that changes made by the pull request and link all relevant issues.

This PR is relevant  
* #30603 

This PR is aimed at adding new features and expanding functionality.

In my opinion, with the addition of this parameter, users will be able to easily implement pagination for non-iterable results.

If an SDK is being regenerated based on a new swagger spec, a link to the pull request containing these swagger spec changes has been included above.

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by ImMin5** [comment]
@microsoft-github-policy-service agree

**Comment by ImMin5** [comment]
> @ImMin5 please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by kristapratico** [comment]
@ImMin5 thanks for your issue and contribution. The `azure-mgmt-costmanagement` client library source code is generated from its service specification. Any code changes we make (like in this PR) will be overwritten the next time the library code is generated. In this case, I suspect the service spec will need to be updated to support this feature, but I defer to @msyyc.

**Comment by msyyc** [comment]
> @ImMin5 thanks for your issue and contribution. The `azure-mgmt-costmanagement` client library source code is generated from its service specification. Any code changes we make (like in this PR) will be overwritten the next time the library code is generated. In this case, I suspect the service spec will need to be updated to support this feature, but I defer to @msyyc.

Hi @ImMin5, as kristapratico said, SDK is generated with [swagger](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cost-management/resource-manager). I infer that you want skipToken for this operation https://github.com/Azure/azure-rest-api-specs/blob/0d41e635294dce73dfa99b07f3da4b68a9c9e29c/specification/cost-management/resource-manager/Microsoft.CostManagement/stable/2023-03-01/costmanagement.json#L950-L1039 and you want new parameter `SkipTokenQueryParameter`. If you want this feature, please make an issue with detailed context in https://github.com/Azure/azure-rest-api-specs/issues.

**Pull request closed without merging**
