### PR TITLE
Add generated code

### PR DESCRIPTION
**Pull request by turalf**

### CODE REVIEW

**Review by RezaJooyandeh — APPROVED** [review]

**Comment by jsntcy** [comment]
@turalf , it's still track1 SDK for mgmt. plane and we need generate track2 SDK.

**Comment by usvoyager** [comment]
ARM SDK updated to track2

---
In reply to: [696499250](https://github.com/Azure/azure-sdk-for-python/pull/13920#issuecomment-696499250) [](ancestors = 696499250)

**Comment by weshaggard** [comment]
I believe the failures in master have been addressed so I retriggered the build pipelines. If those turn green then I think we should be good to merge this into master.

**Review by weshaggard — APPROVED** [review]

**Comment by weshaggard** [comment]
CI is green. The one build was an internal test build that was canceled so this is ready to merge. I'm going to override check-enforcer.

**Pull request merged**
