### PR TITLE
[translation] update target container permissions

### PR DESCRIPTION
**Pull request by kristapratico**

### CODE REVIEW

**Review by maririos — APPROVED** [review]
Can u queue the live tests to verify that with the change they are all passing?

**Comment by maririos** [comment]
>Can u queue the live tests to verify that with the change they are all passing?

Just saw u already did :P

**Comment by kristapratico** [comment]
> Can u queue the live tests to verify that with the change they are all passing?

I did on the previous commit and they all passed. Most recent commit was just docs.

**Review by mohamedshabanofficial — APPROVED** [review]

**Pull request merged**
