### PR TITLE
Added azure-mgmt-keyvault to dev requirements.

### PR DESCRIPTION
**Pull request by mitchdenny**
This should fix the PR/CI validation pipeline build errors we are getting with HDInsight.

### CODE REVIEW

**Comment by adxsdk6** [comment]
Can one of the admins verify this patch?

**Comment by mitchdenny** [comment]
@scbedd I setup a whole bunch of Python pipelines last week and there were a few failures. This change fixes one of those build failures by adding the right keyvault and msi libraries in as dev dependencies. This doesn't impact the big build because these dependencies get installed by other tests so this never showed up previously.

**Comment by mitchdenny** [comment]
Hey @scbedd based on some of the chatter in the office yesterday - have you already dealt with this issue? I'm wondering whether I should merge this or abandon it.

**Comment by scbedd** [comment]
Abandon. This is dealt with as of last night.

**Pull request closed without merging**
