### PR TITLE
Let the transport handles bad urls

### PR DESCRIPTION
**Pull request by lmazuel**
See https://github.com/Azure/azure-sdk-for-python/issues/11048

If a bad combination of parametrized host + incorrect client creation happen, do not crash while trying to build the Url, but build something, and let the transport decides what to do.

For requests, the new trace is now:
```python
  File "c:\users\lmazuel\git\azure-sdk-for-python\sdk\core\azure-core\azure\core\pipeline\transport\_requests_basic.py", line 284, in send
    raise error
azure.core.exceptions.ServiceRequestError: Invalid URL 'text/analytics/v3.0/krpratic-textanalytics.cognitiveservices.azure.com//text/analytics/v3.0/sentiment?showStats=false': No schema supplied. Perhaps you meant http://text/analytics/v3.0/krpratic-textanalytics.cognitiveservices.azure.com//text/analytics/v3.0/sentiment?showStats=false?
```

For aiohttp:
```python
aiohttp.client_exceptions.InvalidURL: text/analytics/v3.0/krpratic-textanalytics.cognitiveservices.azure.com//text/analytics/v3.0/sentiment?showStats=false
```

which is way better than the current error you can see on issue #11048 
```python
File "C:\Users\krpratic\azure-sdk-for-python\env\lib\site-packages\azure\core\pipeline\transport\_base.py", line 695, in format_url
    base = self._base_url.format(**kwargs).rstrip("/")
KeyError: 'Endpoint'
```

EDIT: Will now raise an exception 
>"The value provided for the url part Endpoint was incorrect, and resulted in an invalid url"

### CODE REVIEW

**Comment by xiangyan99** [comment]
If the input kwargs do not satisfy template, why not raise error?

I have some concerns if we modify the template silently.

Maybe we should just give a more descriptive error message?

**Comment by lmazuel** [comment]
What error would you raise? You don't have enough information other that "something is wrong", building the url leniently and let the transport decide if it's malformed sounds fair to me. What are your concerns?

**Comment by xiangyan99** [comment]
My concern is the case that after we skip some components, it is still a valid URL but returns different response. e.g. api_version_number. Because we skip it silently for user, it may confuse users.

**Comment by lmazuel** [comment]
@xiangyan99 if I catch the error, only thing I know is that _something_ the customer provided is not right. I don't know if it's a client parameter (like endpoint), I don't know if it's an operation parameter, I don't know if it's both.

I could raise something like this:
> Unable to build a valid Url, one of your client parameter or operation parameter is invalid, and doesn't allow to build a correct url.

Thoughts?

**Comment by annatisch** [comment]
We can likely include the contents of `kwargs` in the error - as I think these values will mostly be user-supplied, with some values added by the generator, but still potentially useful in debugging.

**Comment by xiangyan99** [comment]
I think the point is if there is something wrong, we would like it to fail on compile time (when building the url) than un-deterministic result (may or may not fail when sending it to server). Your ideas?

**Comment by lmazuel** [comment]
`kwargs` is empty, the only thing we know is that `Endpoint` (the Swagger template part) was invalid. I don't have the Python related to that Swagger template part (it's likely the lower casein snake case, like FooBar template part would be `foo_bar`)

> The value provided for the url part Endpoint was incorrect, and resulted in an invalid url

Thoughts?

**Comment by kristapratico** [comment]
I've seen users run into this error in two ways:

1) accidentally chop off https
2) define the endpoint ending with a comma (making it a tuple) e.g.:
`endpoint = "https://python-textanalytics.cognitiveservices.azure.com/",`

In the first case, we do get a good error back from the transport. In the second case, we get this:

```
azure.core.exceptions.ServiceRequestError: No connection adapters were found for 'text/analytics/v3.0/('https://python-textanalytics.cognitiveservices.azure.com/',)/text/analytics/v3.0/sentiment?showStats=false'
```

... which is not so good. 

So in that case I would be happy with this:

> The value provided for the url part Endpoint was incorrect, and resulted in an invalid url

**Comment by rakshith91** [comment]
accidentally chop off https is often handles individually by clients - we do it in storage, search etc.

**Comment by lmazuel** [comment]
@annatisch @rakshith91 @kristapratico @xiangyan99 I pushed an update, how does it sound?

**Pull request merged**
