### PR TITLE
[Search] Update Similarity property metadata

### PR DESCRIPTION
**Pull request by mrwbarg**
Rename property values for _subtype_map under Similarity.

### CODE REVIEW

**Comment by tjprescott** [comment]
Hi @mrwbarg is there a particular issue you are fixing with this change?

**Comment by mrwbarg** [comment]
Hello,

Yes! There are no keys on the "objects" dictionary corresponding to the
current names. Both have the "Algorithm" suffix.

**Comment by tjprescott** [comment]
@mrwbarg the change you made was in the _generated folder, which cannot be manually modified. If you are encountering an issue with serialization, please open a bug report and I can take a look to address it.

**Pull request closed without merging**
