### PR TITLE
[ML] Apply `black` to `ml`

### PR DESCRIPTION
**Pull request by kdestin**
# Description

Related to #28742
Related to #28782

This PR runs `black` on the `azure-ai-ml` in preparation for #28756 which is scheduled to be merged on 2023-02-15.

Methodology: `black --config eng/black-pyproject.toml sdk/ml`  (`eng/black-pyproject.toml` was introduced in #28835 )

cc: @scbedd 

# All SDK Contribution checklist:
- [x] **The pull request does not introduce [breaking changes]**
- [x] **CHANGELOG is updated for new features, bug fixes or other significant changes.**
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md).**

## General Guidelines and Best Practices
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/cleaning-up-commits.md).

### [Testing Guidelines](https://github.com/Azure/azure-sdk-for-python/blob/main/CONTRIBUTING.md##building-and-testing)
- [ ] Pull request includes test coverage for the included changes.

### CODE REVIEW

**Comment by needuv** [comment]
PR looks good, but I'm wondering if we should skip `_restclient`? It's anyways autogenerated code, so I don't think we need to worry about formatting it. However, if the PR check doesn't allow for exclusions, then I guess we have no choice.

**Comment by kdestin** [comment]
> PR looks good, but I'm wondering if we should skip `_restclient`? It's anyways autogenerated code, so I don't think we need to worry about formatting it. However, if the PR check doesn't allow for exclusions, then I guess we have no choice.

Is there any harm in keeping `_restclient` included? There's a one-time cost every time the restclient is regenerated to run black, but otherwise it's not obvious to me what the negative is. 

---

From what I've seen of the CI infrastructure for formatting, there isn't currently a mechanism for a package to specify formatting exclusions. So if we _really_ wanted to exclude `_restclient`, this PR would be blocked until that's implemented.

**Comment by kdestin** [comment]
> > Is there any harm in keeping `_restclient` included? There's a one-time cost every time the restclient is regenerated to run black, but otherwise it's not obvious to me what the negative is.
> 
> These days, our partners are usually the ones to onboard new API versions, and there tends to be quite a bit of churn in `_restclient` code until the API is finalized. I'm not sure if expecting them to run black every time they regenerate something is too much to ask, so maybe we should have a quick internal discussion about it. If we decide that `_restclient` will be included (since it was excluded from any formatting in the internal repo), we should make it clear in our documentation so that partners aren't confused about the change in rules.

Made a PR ( #28835 ) that should configure `black` to exclude the _restclient from formatting. That PR needs to be merged before this one, but I've already re-run black with those exemptions.

**Review by needuv — APPROVED** [review]

**Pull request merged**
