### PR TITLE
Update Batch SDK to version 2018-03-01.6.1.

### PR DESCRIPTION
**Pull request by xingwu1**

### CODE REVIEW

**Comment by lmazuel** [comment]
Since you're moving to a major version, I would suggest to use Autorest.Python 3.x series, that introduces a few breaking changes to improve the SDK.
Complete list of these changes here (in the general breaking changes section of release 2.0.0rc1:
https://pypi.python.org/pypi/azure-mgmt-network/2.0.0rc1

**Comment by xingwu1** [comment]
Discussed with @lmazuel  by mail, since we change to minor version update, so we continue to use old code gen.

**Comment by xingwu1** [comment]
@lmazuel our code is ready for merged.

**Comment by xingwu1** [comment]
@lmazuel  ping...

**Pull request merged**
