### PR TITLE
Update Matrix Storage

### PR DESCRIPTION
**Pull request by scbedd**
@seanmcc-msft for FYI

I know it looks like I'm adding 310 and 311 to your matrix, but I'm just encoding it there as  I'm not really certain how this is working _as is_ with the config. To be clear 310 and 311 were absolutely being run before this PR 👍 

image

### CODE REVIEW

**Review by jalauzon-msft — APPROVED** [review]

**Comment by seanmcc-msft** [comment]
@scbedd are we good to merge this?

**Comment by scbedd** [comment]
> @scbedd are we good to merge this?

I need to double check that codecov actually publishes >.< I'm doing that now.

**Comment by scbedd** [comment]
Windows py39 didn't publish coverage properly. I don't know why, especially when `core` [works just fine](https://dev.azure.com/azure-sdk/public/_build/results?buildId=2754036&view=results).

**Comment by scbedd** [comment]
I have no earthly idea why [this thing](https://dev.azure.com/azure-sdk/public/_build/results?buildId=2754332&view=logs&j=2707024c-316f-5c33-7a29-ca96bd21cb48&t=ee72343d-e64f-5c4b-4403-f3c5e2442e21) isn't publishing code cov. It clearly is processing it, generating a report, and successfully uploading it. Going to merge. Maybe it's to do with the fact that this is a merge commit build 🤷

**Pull request merged**
