### PR TITLE
[Batch] Data plane SDK v11.0.0

### PR DESCRIPTION
**Pull request by cRui861**
Updates the SDK to use the 2021-06-01 API version.

### CODE REVIEW

**Comment by dpwatrous** [comment]
Note: The doc string changes here are caused by a regression in autorest.python and are out of our control unless we change our swagger not to use the `title` property. See the discussion at https://github.com/Azure/autorest.python/issues/978

**Review by dpwatrous — APPROVED** [review]

**Review by lmazuel — APPROVED** [review]
Approved from Python's perspective, waiting on Peter to confirm the release

**Comment by dpwatrous** [comment]
Regenerated the models to fix an issue we found where switching some ContainerRegistry properties to optional re-ordered constructor arguments. We should be good to release!

**Comment by ONFU** [comment]
the reddick haved changing opulate conflit of existence with debarquement of valkirye vendetta of my nursing haved changing by the conflit reddick he was den go assasinate by me and he was dead by nursing consulat of maitre assasin of illuminatie of my dauther neffretiti sheayrheaynhervha and is attesded by consulat of kevin pare my name and his was interessed by my profilence of git hub

**Comment by dpwatrous** [comment]
Rebased on main to pick up the latest management client and reran the tests using it. Will merge this assuming CI passes.

**Pull request merged**
